src/main/webapp/WEB-INF/views/applications.jsp, src/main/webapp/WEB-INF/views/libraries.jsp
It was possible to perform an atribute based cross site scripting attack. 
The code was already protecting XSS attacks on HTML context, so it was not possible to exploit an XSS by setting the component or application name with the following payload:
```javascript
<script>alert(1)</script>
```
However, the code was also reflected on several attributes of the Edit button, and on some option tags. One of the possible payloads for exploiting this new XSS is:
```javascript
"onmouseover="alert(1)
```
Now, XSS cannot be performed on these fields:
* Application name
* Vendor
* Component name
* Component version
* License
* Language
=> Atribute based XSS fixed on components and applications views

src/main/java/org/owasp/dependencytrack/controller/DownloadController.java
dependency-check-maven plugin is sending HEAD requests when it checks for updates
=> Enable HEAD request and add Last-Modified header for nist cache

src/main/java/org/owasp/dependencytrack/controller/DownloadController.java
required for dependency-check-maven plugin to be able to use custom cve cache - cveUrl properties
=> enable HEAD method and add Last-Modified header

src/main/resources/application.properties
Added an optional LDAP configuration improvement needed for some type of servers.
Specifies how to map the username identifier entered by the user to that passed through to LDAP.
If is configured to a non-empty value, the substring %s in this value will be replaced with the entered username.
The recommended format of this value depends on your LDAP server(Active Directory, OpenLDAP, etc.).
Examples:
alpine.ldap.auth.username.format=%s
alpine.ldap.auth.username.format=%s@example.com
alpine.ldap.auth.username.format=uid=%s,ou=People,dc=example,dc=com
alpine.ldap.auth.username.format=userPrincipalName=%s,ou=People,dc=example,dc=com
=> Specifies how to map the user identifier entered by the user to that passed through to LDAP

src/main/java/org/dependencytrack/model/NotificationRule.java, src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
This pull request fixes an issue where `NotificationRule#notifyOn` was not deserialized correctly, which caused the *Notify On* preferences in Dependency-Track's *Alerts* settings to be dysfunctional.
* Navigate to D-Track's *Adminstration* settings
* Select the *Notifications* -> *Alerts* section
* Create a new alert - settings don't matter
* Select the new alert in the alerts table
* Select any of the *Notify On* checkboxes
* Wait for the page to reload, notice that the checkbox has been de-selected
In my case, the payload being sent by the frontend was:
```json
{
"uuid": "0ca4a989-5f78-44bf-9ceb-fd7616a30a35",
"name": "Test Alert",
"notificationLevel": "WARNING",
"publisherConfig": "{\"destination\":\"http://my-destination.local/notification\"}",
"notifyOn": [
"NEW_VULNERABILITY"
]
} …
```
=> Fix NotificationRule#notifyOn not being deserialized

src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
So this is just a minor thing: Currently, Dependency-Track sends out WebHook notifications with Content-Type `text/plain;charset=UTF-8`, which is probably done implicitly by unirest. Dependency-Track should clearly indicate that the Payload is in fact of Content-Type `application/json`, which is what this change does.
=> Set Content-Type header in AbstractWebhookPublisher

src/main/docker/Dockerfile
This change updates the Dockerfile so that the JDBC drivers are fetched over a secure channel via HTTPS.  This prevents a MITM attack against these dependencies which might result in a compromised docker container.
=> Fetch JDBC drivers over HTTPS

src/main/java/org/dependencytrack/parser/dependencycheck/model/DateAdapter.java, src/test/java/org/dependencytrack/parser/dependencycheck/model/DateAdapterTest.java
At some point [Dependency Check](https://github.com/jeremylong/DependencyCheck/blob/55d8f6659746e71b00f1f480d683b9660a5679d7/core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java#L204) moved to using [DateTimeFormatter.ISO_INSTANT](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_INSTANT) to generate the scan date inside the XML report.  This format reports dates in UTC without a timezone and causes Dependency Track to fail to parse these reports (and thus throw a NPE when one is ingested via the API).
This patch updates the date parsing code so that both the old and new formats are tried.  It should allow Dependency Track to parse reports from both versions.
=> Parse latest date format from dependency-check XML reports

src/main/java/org/dependencytrack/util/NotificationUtil.java
This fixes an issue where `GLOBAL_AUDIT_CHANGE` notifications would not include an array of affected projects.
`NotificationUtil` used the project that's attached to an `Analysis` object in a [branch of execution where this project is always `null`](https://github.com/DependencyTrack/dependency-track/blob/3.5.0/src/main/java/org/dependencytrack/util/NotificationUtil.java#L119).
=> Fix GLOBAL_AUDIT_CHANGE notifications not including affected projects

src/main/webapp/project/functions.js
This PR fixes an issue where removing a Dependency from a Project was not possible via web UI. The UI was submitting `null`s as Component UUIDs to the backend, which responded with HTTP 500. 
Turns out that simply one word was missing. `selections` contains objects of type `Dependency`, not `Component`.
=> Fix "Remove Dependency" functionality in project view

src/main/java/org/dependencytrack/parser/spdx/json/SpdxLicenseDetailParser.java, src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
This PR fixes the URL encoded path lo licenses and publishers that prevents those from being read when the path contains at least a space character. See #482 for details.
This has only been tested in the environment described in the aforementioned issue.
=> Fixed URL encoded path to licenses and publishers 

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
When an existing component is detected whilst processing a BOM most fields are updated to reflect the latest value from the BOM.  The `Cpe` field appears to be missing from this list.  This makes it difficult to update the `Cpe` and thus match against NVD vulnerabilities.
This patch adds the `Cpe` field to the list updated from the BOM.
=> Update the CPE field on components from BOM

src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java, src/test/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzerTest.java
This PR fixes an issue where Dependeny-Track couldn't check Scala components for their latest version using `MavenMetaAnalyzer`. 
The issue was that the analyzer would replace all dots (`.`) in a components name with slashes (`/`). The names of Scala components are always suffixed with `_<COMPILER_VERSION>`, e.g. `_2.12`.
For `pkg:maven/com.typesafe.akka/akka-actor_2.13@2.5.23?type=jar`, the analyzer would produce the Maven GAV URL `http://central.maven.org/maven2/com/typesafe/akka/akka-actor_2/13/maven-metadata.xml`.
I removed the replacement of dots with slashes from the component name. As far as I understand, only the groupId / namespace is split into "folders" inside maven repos.
=> Fix building of Maven GAV URL in MavenMetaAnalyzer

src/main/java/org/dependencytrack/resources/v1/BomResource.java
"If a UUID is not specified, than the projectName and ..." --> "If a UUID is not specified then the projectName and ..."
=> bom endpoint: grammar fix in api operation notes

src/main/resources/templates/notification/publisher/email.peb
When a BOM is consumed or processed, it is good to tell the email receiver the affected project.
=> Revise the email template for BOM consumed and processed

src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/PolicyResource.java, src/test/java/org/dependencytrack/ResourceTest.java, src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
This PR fixes an issue where it wouldn't be possible to delete a policy as long as there were violations associated with at least one of the policy's conditions. 
```
ERROR [Transaction] Operation commit failed on resource: org.datanucleus.store.rdbms.ConnectionFactoryImpl$EmulatedXAResource@39e78fc7, error code UNKNOWN and transaction [DataNucleus Transaction, ID=134478005-188223, enlisted resources=[org.datanucleus.store.rdbms.ConnectionFactoryImpl$EmulatedXAResource@39e78fc7]] : ERROR: update or delete on table "POLICYCONDITION" violates foreign key constraint "POLICYVIOLATION_FK2" on table "POLICYVIOLATION"
Detail: Key (ID)=(1) is still referenced from table "POLICYVIOLATION".
```
This is also reproducable by checking out b9dcc880094c68257d30a27fbff68dd910d63736 and running …
=> Fix error on policy deletion

src/main/docker/Dockerfile
in order to make it work in corporate Dockers that must set the `http_proxy` environment variable for their containers
=> don't use a proxy for HEALTHCHECK

src/main/java/org/dependencytrack/model/Project.java
This caused Jackson to trim the serialized value instead of using the PackageURL constructor, resulting in a type mismatch error when trying to call the setter.
=> Remove @JsonDeserialize annotation from Project's purl field

docs/_docs/getting-started/deploy-docker.md
The list without commas did not work for me (which is what I expected after uncommenting it).
The list with commas works in both Firefox and Chrome.
=> ALPINE_CORS_ALLOW_METHODS list separated by commas

src/main/java/org/dependencytrack/model/PolicyCondition.java, src/main/java/org/dependencytrack/policy/CoordinatesPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/main/java/org/dependencytrack/policy/VersionPolicyEvaluator.java, src/test/java/org/dependencytrack/policy/CoordinatesPolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/VersionPolicyEvaluatorTest.java
This PR adds a new *Version* policy condition that allows for matching of specific component versions or version ranges:
Additionally, as suggested by @stevespringett in Slack, the *Coordinates* condition was extended to support version operators as well:
All numeric comparison operators are supported (`<`, `<=`, `>`, `>=`, `==`, `!=`). If a coordinate's version does not start with any of those operators, DT will fall back to the default `contains` logic.
=> Add support for version policy conditions

src/main/java/org/dependencytrack/tasks/scanners/BaseComponentAnalyzerTask.java
This PR fixes an issue where notifications wouldn't be sent when applying analyses from cache.
This should fix #1051.
=> Send notifications when applying analysis from cache

docs/_docs/getting-started/configuration.md, docs/_docs/getting-started/deploy-docker.md, src/main/docker/docker-compose.yml
We regularly see users being confused that DT doesn't work when deploying the default `docker-compose.yml` to a server. 
Updated `docker-compose.yml` and related documentation pages to indicate that external addresses need to be used.
=> Clarify that API_BASE_URL needs to be modified for server deployments

src/main/java/org/dependencytrack/util/NotificationUtil.java
Affected projects haven't been detached from the persistence context before adding them to a `Notification` and dispatching it.
This caused all kinds of weird errors in when processing the notification, e.g.:
```
21:02:20.447 INFO [OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
21:02:21.960 WARN [Persistence] Exception thrown by StateManager.isLoaded for field=19 of StateManager[pc=org.dependencytrack.model.Project@cf8bee2, lifecycle=P_NONTRANS] : Somehow org.datanucleus.store.rdbms.fieldmanager.ParameterSetter.fetchObjectField() was called, which should have been impossible
21:02:21.961 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDOFatalInternalException: Somehow …
```
=> Detach projects before notification dispatching

src/main/java/org/dependencytrack/tasks/repositories/GoModulesMetaAnalyzer.java, src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java, src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java, src/test/java/org/dependencytrack/tasks/repositories/GoModulesMetaAnalyzerTest.java
Sorry, should've seen those before submitting https://github.com/DependencyTrack/dependency-track/pull/1110:
```
Error:  Failures: 
Error:    DefaultObjectGeneratorTest.testContextInitialized:33->testLoadDefaultRepositories:71 expected:<12> but was:<13>
Error:    DefaultObjectGeneratorTest.testLoadDefaultRepositories:71 expected:<12> but was:<13>
Error:    RepositoryResourceTest.getRepositoriesTest:63 expected:<1[2]> but was:<1[3]>
```
=> Fix tests; Add license headers

docs/_docs/FAQ.md, docs/_docs/datasources/npm.md, docs/_docs/datasources/ossindex.md, docs/_docs/datasources/private-vuln-repo.md, docs/_docs/datasources/repositories.md, docs/_docs/terminology.md, docs/_docs/usage/cicd.md
Just fixing a few typos that I spotted in the documentation website.
=> Fix a few typos

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
Fixes #1132 
The query is malformed if `teamSize > 1`. In this case, the resulting query was
`accessTeams.contains(:team0) accessTeams.contains(:team1)`
instead of
`accessTeams.contains(:team0) || accessTeams.contains(:team1)`
=> Fixes query construction in preprocess ACL

src/main/java/org/dependencytrack/parser/ossindex/OssIndexParser.java, src/main/java/org/dependencytrack/parser/ossindex/model/ComponentReportVulnerability.java, src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
OSS Index API added recently a new property to their API responses called externalReferences which contains the references that are visible on their website. This PR adds these references to Dependency Track as well. I have never written any Java code so feedback is appreciated. Also I have not tested this as I have no clue how to do that and I do have to admit that I was too lazy to learn how to do that.
Relevant links:
https://github.com/OSSIndex/vulns/issues/193
https://ossindex.sonatype.org/rest
=> Parse externalReferences property from OSS Index API response

src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java
used `PackageURL.StandardTypes.HEX` in `org.dependencytrack.tasks.repositories.IMetaAnalyzer::build()` for hex purl
=> use proper HEX const in `IMetaAnalyzer`

src/main/docker/docker-compose.yml
As described in the changelog, the `ALPINE_OIDC_CLIENT_ID` is now mandatory.
=> Added ALPINE_OIDC_CLIENT_ID to docker-compose

src/main/resources/logback.xml
The console output is used by Docker containers.
Since log entries do not include a date, it is unclear to which date an entry belongs.
=> use a full date in console output

docs/_docs/integrations/community-integrations.md
https://github.com/nscuro/dependency-track-client was archived and is superseded by https://github.com/nscuro/dtrack-client
=> Update link to community-maintained Go client

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/test/java/org/dependencytrack/task/BomUploadProcessingTaskTest.java
For manually created projects or when updating a project, a classifier is required and set to the default value "APPLICATION".
However, when creating a project as part of the BOM upload, the classifier is not set.
This fix reads the classifier from the BOM and updates the project as needed. If no classifier is specified in the BOM (old version), the default "APPLICATION" is used.
=> fix: during BOM upload auto-created projects do not have a classifier

src/test/java/org/dependencytrack/notification/publisher/ConsolePublisherTest.java
The system-dependent line separator should be used instead.
=> fix: ConsolePublisherTest fails on Windows

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Add a project to the list of projects of a tag only if the list does not contain the project yet.
fixes #1165
=> fix: Duplicate tag is created upon updating a project

.gitignore, README.md, pom.xml
Adding this just as a quick start to any devs who want to be able to quickly fix an issue they find. They should just be able to test their changes locally by running `mvn jetty:run`. The added bonus is that any changes you make it will poll every 10 seconds and re-deploy automatically, as well as it seems to work with debug mode too in intellij.
Also while trying to set this up and test it I managed to corrupt the database but thought it was something wrong with the way I was configuring the setup stages. So I will just post a reference in case anyone is searching for a fix.
This goes for any way of running with the dev h2 database. Just adding this in case someone starts searching for JdbcSQLNonTransientException or chunk not found errors while doing dev as I've seen an issue also …
=> Added jetty maven plugin for easy command line start

docs/_docs/triage/auditing-basics.md, docs/_posts/2021-xx-xx-v4.4.0.md, src/main/java/org/dependencytrack/auth/Permissions.java, src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java, src/main/java/org/dependencytrack/resources/v1/FindingResource.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v440/v440Updater.java, src/test/java/org/dependencytrack/auth/PermissionsTest.java, src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java, src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
This PR addresses #338 by adding the new `VIEW_VULNERABILITY` permission.
`VIEW_VULNERABILITY` grants read access to `/api/v1/analysis` and `/api/v1/finding`.
This enables users to *see* vulnerabilities a project or component is affected by, as well as the audit trail, but no do any audit decisions. A nice side-effect is that this can be used to reduce the permissions granted to CI integrations like the Jenkins plugin.
To ensure compatibility with older DT versions, all users and teams who previously had the `VULNERABILITY_ANALYSIS` permission are automatically granted the `VIEW_VULNERABILITY` permission.
I was torn whether to call this `VIEW_VULNERABILITY` or `VIEW_FINDING`. `VIEW_VULNERABILITY` fits better into the current naming scheme, but `VIEW_FINDING` is more accurate. After all, …
=> Add `VIEW_VULNERABILITY` permission

docs/_docs/usage/cicd.md
Hi!
This change adds the backslashes to the last curl command on the usage/cicd page. This is useful for people copying and pasting the code block.
@stevespringett Thank you so much for this great project!
=> Add backslash to docs cicd multiple line curl command

src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java, src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
This PR enriches the state change comments in the analysis trail with a prefix of which state was changed.
Without this, changes are kinda ambiguous for the untrained eye.
Such a prefix is not added for suppression changes.
=> Distinguish state changes in analysis trail comments

.github/dependabot.yml, .github/workflows/maven.yml, src/main/docker/Dockerfile
I props these changes as I stumbled over this great tool while dealing with the aftermath that was the Log4Shell hell week and noticed that the Dockerfile could be improved. I did so since we would deploy dtrack to our OpenShift cluster which uses arbitrary UIDs, which is currently already supported by the fronted container yet not by the API server. And while I have made similar changes to packaging for an internal draft container to test deploy dtrack I wanted to offer these changes upstream as well.
Additionally, I noticed that there is the motivation to use the Eclipse-Temurin JVM based on the comment in https://github.com/DependencyTrack/dependency-track/issues/1213#issuecomment-978807113, so I took the liberty and migrated the Container to that alongside the other changes.
To answer …
=> packaging: Overhaul Containerfile and use Temurin JRE

src/main/docker/Dockerfile
The container health check is currently failing due to the move from Alpine to Debian slim as base image:
```shell
$ docker inspect --format "{{json .State.Health }}" dtrack-apiserver | jq
{
"Status": "starting",
"FailingStreak": 2,
"Log": [
{
"Start": "2022-02-18T10:55:15.588984439+01:00",
"End": "2022-02-18T10:55:15.69434158+01:00",
"ExitCode": 1,
"Output": "/bin/sh: 1: wget: not found\n"
}
]
}
```
`wget` does not come preinstalled on Debian slim. Additionally, the syntax of disabling proxies differs from the `wget` provided by Alpine vs. Debian.
Downside is that installing `wget` via apt affects the reproducability of the image built. 
We could pin `wget` to a specific version, but then we'd have to keep up with updating it regularly.
=> Fix container image health check

src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java, src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
The NPE was caused by calling `.name()` on `null` values. 
I took the chance to add `NOT_SET ->` transitions for *Justification* and *Vendor Response* as well.
Addresses #1409
=> Fix NPE when updating an analysis that was created with DT y= 4.3.6

src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
According to this [post](https://github.com/DependencyTrack/dependency-track/issues/249#issuecomment-754725274), I have added a call to performPolicyEvaluation during the portfolio analysis. Otherwise, policy analysis is not done every 24 hours
=> Perform policy evaluation during portfolio analysis

src/main/java/org/dependencytrack/tasks/MetricsUpdateTask.java
I was profiling the `MetricsUpdateTask` class due to some folks reporting performance concerns and managed to identify a few screws we could tighten to make the task more resource efficient.
* DT 4.4.2 running on Temurin 11 on macOS.
* Postgres database running in Docker, using the `postgres:14.2-alpine` image.
* 50 projects, all using the DT API Server 4.4.2 BOM. 7850 components in total.
* `MetricsUpdateTask` running in a `JerseyTest` without any resources deployed. The task is running pretty much isolated.
* Because no other tasks are running, no data is changing, thus the metrics update task won't perform any `INSERT`s, just `UPDATE`s.
* Using *Async Profiler* in IntelliJ.
The current implementation is performing a lot of allocations in the `updateComponentMetrics` method. Profiling …
=> Tweak `MetricsUpdateTask` performance

docs/_docs/usage/policy-compliance.md
I suggest to make users/readers aware of the fact policies are only evaluated on SBOM uploads (and not immediately after creating a policy)
=> docs: policies are evaluated on sbom upload

src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java, src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/tasks/MetricsUpdateTask.java, src/test/java/org/dependencytrack/TaskTest.java, src/test/java/org/dependencytrack/tasks/MetricsUpdateTaskTest.java
This PR adds tests for `MetricsUpdateTask`, making it easier to debug and verify its functionality when stuff gets changed.
* The count of audited and suppressed findings was off, as their queries still included `project == null` expressions. Probably leftovers from the global component model before v4.
* The count of audited findings was off, because it didn't account for suppressed findings. If a finding is suppressed, the overall finding count is reduced as well. Until now however, suppressed findings were considered "audited" as well, which could result in situations where more findings are audited than even exist.
* The audited/unaudited counts of policy violations were off, because the count of audited violations was never populated.
* Suppressed policy violations were not reflected …
=> Add tests for `MetricsUpdateTask` and squash some bugs along the way

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
**Changes**
When Project is autocreated during BOM upload and Portfolio Access Control is enabled, the ACL of the new Project should contain the Team that created the Project. fixes #1435 
The same cannot yet be done for Users autocreating a Project as we don't know which Team should be added to the ACL. Users can be in 0 or more Teams.
**Unit tests**
I was planning on updating the unit tests to reflect this scenario. But there are no unit tests around Portfolio Access Control it seems. It would to be too big a change for me here to add them in this PR.
**Notes**
There already was some duplicate code in the `BomResource`. I didn't want to refactor too much, but tried to avoid creating more duplicate code.
=> Project (auto)create: Add Team to ACL for ApiKey principals

docs/_docs/getting-started/openidconnect-configuration.md
I noticed some people having trouble setting up OIDC for popular cloud providers like GCP and Azure AD. I thought I would add some documentation on how I set up OIDC with my Azure AD tenant. Hopefully, someone will contribute documentation for GCP (#1556) and AWS too.
=> Add example OIDC setup for Azure Active Directory

docs/_posts/2022-xx-xx-v4.5.0.md, src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java, src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java, src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java, src/test/java/org/dependencytrack/resources/v1/ViolationAnalysisResourceTest.java
Also add more tests for `AnalysisResource` and `ViolationAnalysisResource`. Additionally test notifications being sent.
Before (in v4.4.2):
After (this PR):
=> Fix unnecessary creation of audit trail entries for `Justification` and `Response`

src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java, src/main/java/org/dependencytrack/upgrade/v450/v450Updater.java, src/main/resources/services.bom.json
The Atlassian package repository has been moved.  While this address still works with a 301 permanent redirection, anyone using this file as documentation for allow-listing egress to these endpoints (like me) needs the accurate addresses.  Since this one has been moved by Atlassian, I thought I'd send this PR to update it at source.
```shell
curl -v  "https://maven.atlassian.com/content/repositories/atlassian-public/"
*   Trying 104.192.143.13:443...
* Connected to maven.atlassian.com (104.192.143.13) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, …
```
=> Updated Atlassian package repository address

src/test/java/org/dependencytrack/assertion/Assertions.java, src/test/java/org/dependencytrack/assertion/AssertionsTest.java, src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java, src/test/java/org/dependencytrack/resources/v1/ViolationAnalysisResourceTest.java
The tests assert the existence of notifications, which are sent asynchronously by DT's event system. While locally this happens fast enough, it seems like it's delayed when executed in CI, causing test failures.
=> Fix flaky `AnalysisResource` and `ViolationAnalysisResource` tests

src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
This eases project management by removing the need to fetch a project at first, modifying the parts of interest and updating the project in total.
For example , it is now possible to change the `active` property from `true` to `false` without touching other properties.
Please note that I had to change the behavior of `Project#isActive` to return `null` if `active` is actually `null`. In order not to change the API response, `null` is serialized as `true` with a custom `JsonSerializer`, thus keeping the behavior the same externally.
=> Add PATCH method to the project resource for partially updating an existing project

docs/_posts/2022-xx-xx-v4.5.0.md, src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java, src/main/java/org/dependencytrack/tasks/scanners/BaseComponentAnalyzerTask.java, src/main/java/org/dependencytrack/tasks/scanners/InternalAnalysisTask.java, src/main/java/org/dependencytrack/upgrade/v450/v450Updater.java, src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskTest.java
This PR does two things:
1. Handle component versions prefixed with `v` in `InternalAnalysisTask` when performing lookups in `VULNERABLESOFTWARE`. Both GHSA and NVD do not include this prefix in their versions. As `VULNERABLESOFTWARE` is populated by multiple sources, this change will need to be revisited when another source is added. 
2. Correct the PURL building for Go modules in `GitHubAdvisoryMirrorTask`. See https://github.com/DependencyTrack/dependency-track/issues/1574#issuecomment-1114307576 for details on this issue. Go module names are a little special when it comes to PURL and need extra care.
Additionally, the changes in 2. are applied to existing `VULNERABLESOFTWARE` rows as well during the v4.5.0 upgrade.
Fixes #1574.
=> Fix GHSA vulnerabilities not being matched for Go modules

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/main/java/org/dependencytrack/search/IndexManager.java
Upon project deletion, the search index was updated but never committed, preventing the change from taking effect immediately.
While debugging, I noticed that `/api/v1/search` worked once, shortly after restarting DT, but then didn't update anymore, regardless of whether resources would be added, updated or deleted. This turned out to be caused by DT reusing the same `IndexSearcher` instance. The `IndexSearcher` documentation says:
> For performance reasons, if your index is unchanging, you should share a single IndexSearcher instance across multiple searches instead of creating a new one per-search. **If your index has changed and you wish to see the changes reflected in searching, you should use DirectoryReader.openIfChanged(DirectoryReader) to obtain a new reader and then create a new …
=> Fix portfolio changes not being reflected in search API results

docs/_docs/integrations/file-formats.md
If you want to export the FPF format findings via the `/api/v1/finding/project/{uuid}/export` API, the documentation says that you need the VULNERABILITY_ANALYSIS permission for the accompanying API key. After some debugging, i found out that the source requires VIEW_VULNERABILITY:
https://github.com/DependencyTrack/dependency-track/blob/beda0ce2a594302b6ef976187967b0c4ea12cd91/src/main/java/org/dependencytrack/resources/v1/FindingResource.java#L111
This is a fix to patch the documentation to state the correct permissions needed.
Signed-off-by: Tonimir Kisasondi <kisasondi@gmail.com>
=> Documentation fix for export endpoint permissions

.github/workflows/_meta-build.yaml, .github/workflows/ci-build.yaml
A slight oversight on my previous PR resulted in pull requests only triggering the test-ci workflow, and while that sounds alright it ignores the fact that the test-ci wont build and thereby test the full build and the container builds.
This PR aims to fix this oversight.
* only run login action and push when triggered on the default branch
* also trigger the build-ci workflow to test the general build and the container files
* n/a
=> ci: improve pull request testing

docs/_docs/integrations/notifications.md, docs/_posts/2022-xx-xx-v4.5.0.md, src/main/java/org/dependencytrack/util/NotificationUtil.java
Example notification:
```json
{
"notification": {
"level": "INFORMATIONAL",
"scope": "PORTFOLIO",
"group": "POLICY_VIOLATION",
"timestamp": "2022-05-12T23:07:59.611303",
"title": "Policy Violation",
"content": "A operational policy violation occurred",
"subject": {
"project": {
"uuid": "7a36e5c0-9f09-42dd-b401-360da56c2abe",
"name": "Acme Example",
"version": "1.0.0"
},
"component": {
"uuid": "4e04c695-9acd-46fc-9bf6-ed23d7eb551e",
"group": "apache",
"name": "axis",
"version": "1.4"
},
"policyViolation": {
"uuid": "c82fcb50-029a-4636-a657-96242b20680e",
"type": "OPERATIONAL",
"timestamp": "2022-05-12T20:34:46Z",
"policyCondition": {
"uuid": "8e5c0a5b-71fb-45c5-afac-6c6a99742cbe",
"subject": "COORDINATES",
"operator": "MATCHES",
"value": …
```
=> Include `policy` field in `POLICY_VIOLATION` notification

docs/_docs/integrations/file-formats.md, docs/_docs/integrations/notifications.md, docs/_posts/2022-xx-xx-v4.5.0.md, src/main/java/org/dependencytrack/model/Finding.java, src/main/java/org/dependencytrack/model/Vulnerability.java, src/main/java/org/dependencytrack/util/NotificationUtil.java, src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java, src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Addresses concerns with 3rd party integrations, e.g. https://github.com/DependencyTrack/dependency-track/issues/1467#issuecomment-1128161152
=> Ensure backwards-compatibility by including an additional `cwe` field in API objects and notifications

docs/_docs/integrations/file-formats.md, src/main/java/org/dependencytrack/model/Finding.java, src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
It was `cweId` and `cweName` before, instead of a `cwe` object.
=> Fix cwe field names for findings API and FPF

.github/release-workflow.adoc, .github/workflows/_meta-build.yaml, .github/workflows/ci-build.yaml, .github/workflows/ci-publish.yaml, .github/workflows/ci-release.yaml, docs/_posts/2022-05-18-v4.5.0.md
> this is the backport PR
This PR aims to fix and introduce the `latest` tag logic from my prior CI PRs, sorry for any inconvenience that this error may have caused.
* fixes #1644 on default branch (the default branch PR is here #1645)
=> fix: latest tag logic in meta workflow

.github/workflows/ci-test.yaml
The workflow is currently run twice for PRs. Tests take quite a while, and we really only care about tests on our main branches.
=> Run Tests CI only for pushes or PRs to default- or release branches

.github/workflows/ci-publish.yaml, .github/workflows/ci-release.yaml
Builds upon https://github.com/DependencyTrack/dependency-track/pull/1645. `Publish CI` is not triggered automatically when creating releases with `GITHUB_TOKEN`. The bot account needs write access to the repository. The bot's PAT (`BOT_RELEASE_TOKEN`) only requires the `public_repo` scope.
=> Use bot account to create releases

.github/workflows/ci-publish.yaml, .github/workflows/ci-release.yaml
Builds upon https://github.com/DependencyTrack/dependency-track/pull/1645. `Publish CI` is not triggered automatically when creating releases with `GITHUB_TOKEN`. The bot account needs write access to the repository. The bot's PAT (`BOT_RELEASE_TOKEN`) only requires the `public_repo` scope.
=> Backport #1668 to 4.5.x

src/main/java/org/dependencytrack/model/Policy.java, src/main/java/org/dependencytrack/model/Tag.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/TagQueryManager.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/main/java/org/dependencytrack/resources/v1/PolicyResource.java, src/main/java/org/dependencytrack/resources/v1/TagResource.java, src/test/java/org/dependencytrack/ResourceTest.java, src/test/java/org/dependencytrack/model/PolicyTest.java, src/test/java/org/dependencytrack/policy/PolicyEngineTest.java, src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java, src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Changes for new feature to support 'Limit to Tags' in policy management.
This includes:
endpoint to add new tag/s in a policy
endpoint to remove tag/s from a policy
endpoint to get all tags available in all projects or specific projects under a policy
changes in policy evaluation to limit scanning of components against policies having these tags (if, added in 'Limit to Tags')
Unit tests for above
Issue: https://github.com/DependencyTrack/dependency-track/issues/1565
Frontend changes -> https://github.com/DependencyTrack/frontend/pull/160
https://github.com/DependencyTrack/frontend/pull/162
=> Issue #1565 : new policy tag feature

src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
Closes #1173
Companion PR to https://github.com/DependencyTrack/frontend/pull/171
It turned out that enabling/disabling notifications was already implemented in the API server, it just wasn't possible to set the `enabled` field via REST API. This is now possible, and disabling notifications works as expected.
=> Allow notifications to be deactivated

src/main/java/org/dependencytrack/notification/NotificationRouter.java
#1429 
* An INFORMATIONAL sink/publisher will receive INFO, WARN, ERROR events
* A WARNING sink/publisher will receive WARN, ERROR events
* An ERROR sink/publisher will receive ERROR events
This creates the ablitity to publish mirror events only when in error as
opposed the the current "everything is okay" alarms we now get daily on ERROR scoped
Alerts.
Signed-off-by: Drew Thompson <drew.michael.thompson+ghdco@gmail.com>
=> flips level logic to mirror root logger

src/main/java/org/dependencytrack/model/Analysis.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v460/v460Updater.java
Fixes #1661
Tested by:
1. Launching a new DT instance (built from `master`)
2. Creating a new project, uploading a BOM with vulnerable components
3. Recording analysis for some findings, including the *Details* field
4. Stop the instance
5. Manually change `"SCHEMAVERSION"."VERSION"` in the DB to `4.5.0`
6. Rebuild DT from the `issue-1661` branch
7. Start DT again
8. Verify that the `"ANALYSIS"."DETAILS"` column was correctly updated
Tested with:
=> Change type of analysis details column to `CLOB`

src/main/docker/Dockerfile
Dependabot can't figure this update out on its own
=> Bump Temurin base image to 11.0.15_10

src/main/java/org/dependencytrack/persistence/CacheQueryManager.java, src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java, src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java, src/main/java/org/dependencytrack/persistence/MetricsQueryManager.java, src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java, src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java, src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java, src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java, src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
Translates into `LIMIT 1`, `TOP 1` etc. depending on the datastore.
Results in queries being executed faster in the datastore (at least when no index is used), reduces the amount of unnecessary data being loaded into RAM.
=> Use datastore-native limiting in queries where only a single result is desired

src/main/java/org/dependencytrack/notification/NotificationConstants.java, src/main/java/org/dependencytrack/util/NotificationUtil.java, src/test/java/org/dependencytrack/notification/NotificationConstantsTest.java
Fixes #1818
Resolved finding case was missing in NotificationUtil logic.
=> Notification email with 'null' subject when 'PROJECT_AUDIT_CHANGE' is enabled and analysis state is 'RESOLVED'

src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/main/java/org/dependencytrack/util/NotificationUtil.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Fixes #1866
Project deduplication in `NotificationUtil` is debatable as we can say it is not Dependency Track job to compensate input data quality (e.g : SBOM merge with duplicates). I agree for the most part (metrics calculation, vulnerability assignment...) but for notification, I feel that it is a sound compromise.
=> Restrict notification's affected project list when notification rule is limited to specific projects

.github/workflows/_meta-build.yaml, .github/workflows/ci-release.yaml, .github/workflows/ci-test.yaml, DEVELOPING.md, pom.xml, src/main/docker/Dockerfile, src/test/java/org/dependencytrack/ResourceTest.java, src/test/java/org/dependencytrack/integration/ApiClient.java
Depends on https://github.com/stevespringett/Alpine/pull/410
Note: The compilation target version is defined in Alpine (which is still 11 in `master`). This PR includes the necessary changes to build and run DT with compilation target 17.
=> Upgrade to Java 17

src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java, src/main/java/org/dependencytrack/tasks/TaskScheduler.java, src/main/java/org/dependencytrack/tasks/scanners/BaseComponentAnalyzerTask.java, src/main/webapp/WEB-INF/web.xml, src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
Enhancement request described in #1542.
Please find below related PRs to review :
- Frontend : [PR 214](https://github.com/DependencyTrack/frontend/pull/214)
**Design decisions :**
- Task are not rescheduled after period update because it would require updates on Alpine framework to be able to cancel a given task. It is also tricky because, if the task ran 5min ago, we don't want to run it again after a reschedule. With a restart, we don't have to handle all those edge cases
- I've introduced _scanner.analysis.cache.validity.period_ configuration property used in [BaseComponentAnalyzerTask](https://github.com/syalioune/dependency-track/blob/feature/configurable_period_for_tasks/src/main/java/org/dependencytrack/tasks/scanners/BaseComponentAna …
=> Make background tasks periodicity configurable

src/main/java/org/dependencytrack/event/InternalComponentIdentificationEvent.java, src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java, src/test/java/org/dependencytrack/tasks/InternalComponentIdentificationTaskTest.java
Instead of loading all components at once. Also use a dedicated fetch group to limit the data being fetched. Remove unused code from `InternalComponentIdentificationEvent`.
Fixes #1947 
Memory usage while the task is running on a portfolio with 466000 components (task execution marked with red arrow):
This PR
Current `master` (note that the JVM only has 8GB assigned to it)
=> Refactor `InternalComponentIdentificationTask` to use pagination

src/main/java/org/dependencytrack/model/Component.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Predefined RegexSequences only validate lower case hash notations. While this is usually the case it is not mandatory as hex values can be upper and lower case. Furthermore, tools like cyclonedx-dotnet provide uppercase hash values and boms generated by it can be imported but components can't be changed in UI. API will return an error for failed hash validation
Fixes: #1174, Partially: #1182 
Signed-off-by: awegg <alexander@weggerle.de>
=> Issue 1174: Fix component update due to uppercase hashes

src/main/java/org/dependencytrack/model/Vulnerability.java, src/main/java/org/dependencytrack/model/VulnerabilityAlias.java, src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java, src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
This functionality got lost when resolving merge conflicts in #1912. It has now been adapted to the new metrics calculation method.
=> Fix vulnerability aliases not being considered during metrics calculation

docs/_docs/integrations/notifications.md, src/main/java/org/dependencytrack/util/NotificationUtil.java, src/main/java/org/dependencytrack/util/VulnerabilityUtil.java, src/main/resources/templates/notification/publisher/email.peb, src/test/java/org/dependencytrack/util/VulnerabilityUtilTest.java
Based on #2011 because I needed some methods introduced in that PR.
Note: I've ran into an issue where aliases would be discarded when detaching the vulnerability "owning" them. Because the `Vulnerability#aliases` field is transient, DataNucleus just drops it during detachment. I worked around this for now by refreshing the aliases again whenever it's needed, but ultimately a more general solution would be good.
=> Include vulnerability aliases in notifications

docs/_docs/getting-started/deploy-docker.md, src/main/docker/Dockerfile, src/main/docker/docker-compose.yml
Sometimes it's useful to pass extra JVM options into the DT Java process.
While it is possible to override the `JAVA_OPTIONS`, this would mean the existing default value from `Dockerfile` has to be copied and maintained.
This PR adds a `EXTRA_JAVA_OPTIONS` environment variable that can be specified at runtime, while benefitting from the existing defaults in the `Dockerfile`.
=> Docker: Add optional EXTRA_JAVA_OPTIONS environment variable

docs/_posts/2022-10-13-v4.6.1.md, src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java, src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
DataNucleus would (in some, not all cases) falsely assume that the `violation.policyCondition.policy` field has already been loaded, and would not attempt to fetch it again. This then caused API responses to not contain the `policy` field (#2043).
The scenario is not reproducible in unit tests, even with regular cache eviction. It is reliably reproducible in running instances using the steps listed in #2043 though.
Instead of detachment like it's introduced in this PR, another cheap fix would've been to call `violation.getPolicyCondition().getPolicy().getName()` instead of `violation.getPolicyCondition().getPolicy()` in `PolicyQueryManager#getPolicyViolations`. That would force DN to fetch all fields of `Policy`, but I felt like that was too hacky to rely on it.
Fixes #2043 …
=> Ensure that policy is part of policy violations API response

docs/files/grafana-dashboard.json
The sample Grafana dashboard misses a datasource property for the `instance` dropdownlist. This causes the dropdown (and possible options in the dropdown) to be empty. This results in a (Javascript) error when importing the dashboard. 
This PR fixes this.
=> Grafana: Use datasource for dropdown population

docs/_docs/getting-started/configuration.md, docs/_docs/getting-started/deploy-docker.md, docs/_docs/getting-started/monitoring.md, src/main/docker/docker-compose.yml, src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java, src/main/resources/application.properties
Also, give it a name and provide the same `uncaughtExceptionHandler` that is used by Alpine's event services.
=> Include SnykAnalysisTask thread pool in Prometheus metrics

src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/main/java/org/dependencytrack/notification/vo/AnalysisDecisionChange.java, src/main/java/org/dependencytrack/util/NotificationUtil.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java, src/test/java/org/dependencytrack/notification/vo/AnalysisDecisionChangeTest.java
... to now also include the following subjects:
* `PolicyViolationIdentified`
* `AnalysisDecisionChange`
* `ViolationAnalysisDecisionChange`
Fixes https://github.com/DependencyTrack/dependency-track/issues/975
=> Extend "limit to" functionality for notifications

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java, src/main/java/org/dependencytrack/resources/v1/vo/CloneProjectRequest.java, src/main/java/org/dependencytrack/tasks/CloneProjectTask.java, src/test/java/org/dependencytrack/event/CloneProjectEventTest.java
Adds an `includeACL` parameter to the project clone api. And an extra `/acl/enabled` endpoint for the front-end to query ACL enabled status.
Fixes #1534 and option 1 of #1632
Front-end PR linked below.
Signed-off-by: Valentijn Scholten <valentijnscholten@gmail.com>
=> Allow cloning of ACL during Project cloning

src/main/java/org/dependencytrack/resources/v1/FindingResource.java, src/main/java/org/dependencytrack/tasks/scanners/InternalAnalysisTask.java
This PR adds `/api/v1/findings/project/{uuid}/analyze` to trigger a reanalysis of a project's components.
This will perform an asynchronous analyis, returning a token to check for completion.
The vulnerability analysis is identical to the scheduled vulnerability analysis, so any cached results that haven't expired will be used.
Front-end part with button on Project view is linked below.
Fixes #2116 
Questions:
- Does it have enough value if it's using the cache?
Signed-off-by: Valentijn Scholten <valentijnscholten@gmail.com>
=> Add reanalyze button for projects

pom.xml
As we migrated to Java 17 in 4.6.0, we should should use the distribution of the MSSQL JDBC driver for Java 17.
This PR performs this switch.
N/A
N/A
=> Switch to `jre17` distribution of `mssql-jdbc`

docs/_docs/analysis-types/known-vulnerabilities.md, docs/_posts/2022-11-18-v4.6.3.md, src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v463/v463Updater.java
Port changes from v4.6.3 to v4.7.0-SNAPSHOT.
#2115
N/A
=> Port changes from v4.6.3 to v4.7.0-SNAPSHOT

src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java, src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
Sign-off-by kekkegenkai: kekkegenkai@gmail.com
The current implementation of the /api/v1/analysis endpoint returns the Statuscode 200 without any content in case no analysis is running/exists.
In this PR I changed this behavior. If no analysis is running the application returns a 404.
#1932
=> Issue 1932: Empty response on /api/v1/analysis endpoint

docs/_docs/getting-started/configuration.md, docs/_docs/getting-started/deploy-docker.md, src/main/java/org/dependencytrack/common/ConfigKey.java, src/main/java/org/dependencytrack/event/RepositoryMetaEvent.java, src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/persistence/CacheQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/main/java/org/dependencytrack/tasks/ClearComponentAnalysisCacheTask.java, src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v463/v463Updater.java, src/main/java/org/dependencytrack/upgrade/v470/v470Updater.java, src/main/java/org/dependencytrack/util/CacheStampedeBlocker.java, src/main/resources/application.properties, src/test/java/org/dependencytrack/event/RepositoryMetaEventTest.java, src/test/java/org/dependencytrack/util/CacheStampedeBlockerTest.java
Leverage the `COMPONENTANALYSISCACHE` table already used by vulnerability analyzers (See #1943)
- If a `RepositoryMetaComponent` entry exists for the current component and has been created in the last `scanner.analysis.cache.validity.period` (check performed using the `LAST_CHECK` column), the analysis is skipped
- For every repository, if there is an entry for the current `purl` in the  `COMPONENTANALYSISCACHE` table younger than `scanner.analysis.cache.validity.period`, the meta model built from the external call result is reused
-  For every repository, if there is an entry for the current `purl` in the  `COMPONENTANALYSISCACHE` table older than `scanner.analysis.cache.validity.period` or no entry, an external call is made and the `COMPONENTANALYSISCACHE` table is updated
- Even though …
=> Feature: Implementing caching for Repository metadata analyzer

docs/_docs/getting-started/deploy-docker.md, docs/_docs/getting-started/deploy-exewar.md, src/main/java/org/dependencytrack/RequirementsVerifier.java, src/main/java/org/dependencytrack/common/ConfigKey.java, src/main/resources/application.properties
In this PR, I added a new environment variable called **system.requirement.check.enabled** that allow users to disable Dependency-Track requirements startup check.
Fixes DependencyTrack/dependency-track#2197
=> Issue 2197: Allow to bypass starting requirements

.github/workflows/_meta-build.yaml, .github/workflows/ci-release.yaml, .github/workflows/ci-test.yaml
Revert #2236 due to https://github.com/actions/setup-java/issues/422
N/A
N/A
=> Revert "Bump actions/setup-java from 3.6.0 to 3.7.0"

src/main/java/org/dependencytrack/model/PortfolioMetrics.java, src/main/java/org/dependencytrack/model/ProjectMetrics.java, src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/main/java/org/dependencytrack/resources/v1/vo/BomUploadResponse.java, src/main/java/org/dependencytrack/resources/v1/vo/IsTokenBeingProcessedResponse.java
I was working on generating a typescript client using Swagger (happy to contribute the client also!) and I noticed some APIs does not have well defined responses.
I am not sure how I should test it, so happy to get some feedback on the change!
=> chore: added swagger types for BOM operations

src/main/java/org/dependencytrack/policy/LicensePolicyEvaluator.java, src/test/java/org/dependencytrack/policy/LicensePolicyEvaluatorTest.java
If you want to set up a license policy where the license is blank or null, it is currently only possible by creating a license policy which includes every single license. This is tedious to set up and needs to be maintained if new licenses are added.
To simplify setting up this license policy, it is now possible to choose `unresolved` as the value for a policy condition. This condition then checks, if a component does not have a license.
#1518
[Frontend PR](https://github.com/DependencyTrack/frontend/pull/339)
=> Enable to set unresolved license for license policy

src/main/java/org/dependencytrack/event/IndexEvent.java, src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java, src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java, src/main/java/org/dependencytrack/resources/v1/SearchResource.java, src/main/java/org/dependencytrack/search/ComponentIndexer.java, src/main/java/org/dependencytrack/search/CpeIndexer.java, src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java, src/main/java/org/dependencytrack/search/IndexConstants.java, src/main/java/org/dependencytrack/search/IndexManager.java, src/main/java/org/dependencytrack/search/IndexManagerFactory.java, src/main/java/org/dependencytrack/search/IndexSubsystemInitializer.java, src/main/java/org/dependencytrack/search/LicenseIndexer.java, src/main/java/org/dependencytrack/search/ProjectIndexer.java, src/main/java/org/dependencytrack/search/SearchManager.java, src/main/java/org/dependencytrack/search/ServiceComponentIndexer.java, src/main/java/org/dependencytrack/search/VulnerabilityIndexer.java, src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java, src/main/java/org/dependencytrack/tasks/IndexTask.java, src/main/java/org/dependencytrack/tasks/TaskScheduler.java, src/main/webapp/WEB-INF/web.xml, src/test/java/org/dependencytrack/event/IndexEventTest.java, src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java, src/test/java/org/dependencytrack/resources/v1/SearchResourceTest.java, src/test/java/org/dependencytrack/search/CpeIndexerTest.java, src/test/java/org/dependencytrack/search/VulnerableSoftwareIndexerTest.java
Fix : Restoring lucene index build during startup by having a dedicated listener
The following features/fixes are introduced as part of this PR
1. Index healthcheck at startup using a servlet listener. Healthcheck consist of index directory existence check and corruption check using lucene API. Any failure trigger rebuild of corresponding index
2. A new configurable background task to perform health and consistency check. Healthcheck is the same one performed during startup. Concistency check consist of computing a delta ratio between DB and Lucene and comparing it to a configurable threshold. Any failure trigger rebuild of corresponding index
3. Any Lucene `CorruptIndexException` will trigger a rebuild of the corresponding index
4. A REST API (and corresponding GUI admin screen) is …
=> Fix: Restoring lucene index build during startup & allow rebuild through UI

src/main/java/org/dependencytrack/resources/v1/vo/AffectedComponent.java, src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java, src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java, src/test/java/org/dependencytrack/resources/v1/vo/AffectedComponentTest.java
=> Fix: AffectedComponent mapping from VulnerableSoftware in case of purl with no namespace

src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java, src/test/resources/bom-1.xml
#1200
Frontend PR https://github.com/DependencyTrack/frontend/pull/347
~~- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~~
=> Feature: Add External References from BOM Metadata to Project

docs/_docs/integrations/community-integrations.md
Signed-off-by: Edouard Shaar <edouard.shaar@gsoft.com>
Add the Azure DevOps Extension to the list of Community integrations.
Adds a missing community integration for Azure DevOps.
=> Add Azure DevOps Extension to community integrations

src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskTest.java
https://github.com/DependencyTrack/dependency-track/discussions/2188
See https://github.com/DependencyTrack/dependency-track/pull/1929#issuecomment-1331223525
This PR fix a bug making `cpe:2.3:a:xiph:speex:1.2:-:*:*:*:*:*:*` not equal to `cpe:2.3:a:xiph:speex:1.2:-:*:*:*:*:*:*` when performing internal analysis. Special cases (`NA` and `ANY` on each part) are handled before making the simplest of comparison.
Right now, the relation 6 in the picture below from [NIST CPE matching spec](https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7696.pdf) is correctly handled for CPE's update part.
N/A
~~- [] This PR implements an enhancement, and I have provided tests to verify that it works as intended~~
~~- [ ] This PR introduces changes to the database model, and I have added corresponding [update …
=> Fix: Exact match between CPE with NA (-) update part

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
This PR adds a `project` query parameter to the `GET /api/v1/component/identity` endpoint. 
Filtering by project makes lookups more efficient on both sever- and client-side when only components of a certain projects are of interest.
Closes #2228
N/A
=> Add support for filtering by project in component identity lookups

.github/workflows/_meta-build.yaml, .github/workflows/ci-publish.yaml, pom.xml, src/main/resources/services.bom.json
This PR adds an execution of the CycloneDX CLI to the build in order to merge the generated `bom.json` with the manually-maintained `services.bom.json`.
The services OSV and Snyk have been added to `services.bom.json` in order to reflect our new integrations.
Relates to #1559
Closes #2125 
As the merge step requires the CycloneDX CLI to be installed, it is disabled by default.
In order to keep things simple, generation and distribution of the BOM in XML format is disabled.
Focusing on just the JSON BOM should suffice. Users who need a different format can convert on their end.
=> Merge generated BOM with services BOM

docs/_docs/integrations/notifications.md, src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java, src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java, src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
Signed-off-by: Mvld3r <Mvld3r@users.noreply.github.com>
Set Jira URL for Jira notifications globally rather than in alerts
Fixes #2297.
=> Set Jira URL for Jira notifications globally rather than in alerts

src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
If the active status of a project is `null` and someone tries to update that project, a `NullPointerException` will be thrown because that case is currently not handled.
This PR checks if the active status of a project is `null` when trying to update the project, and handles the case, resulting in no `NullPointerException` being thrown.
Closes #2317
~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
~- [ ] This PR introduces new or alters existing behavior, and I have updated the …
=> Fix `NullPointerException` when updating a project

docs/_docs/datasources/github-advisories.md
Update the documentation on Github Advisories regarding the new (beta) fine-grained tokens, which are not usable, yet.
Closes: #2344
(even though it's not really closing it, I guess updating the documentation should be good for now)
=> Docs: Github Advisories and fine-grained tokens

src/main/java/org/dependencytrack/persistence/QueryManager.java
c.f issue. Double quoting the table just like the column in the native sql query.
#2374 
N/A
=> Fix: Double quoting table to avoid PG "relation does not exist"

src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/SnykAnalysisTaskTest.java
At Snyk we noticed that requests being made by Dependency-Track send the default Unirest user agent header; this change adds Dependency-Track’s user agent string to requests made by the Snyk analysis task.
Since this change is quite small, I did not open an issue for this. Please let me know if this changes requires a prior issue to be created and discussed.
Thank you!
=> Fix: add user-agent header to Snyk requests

src/main/java/org/dependencytrack/policy/PackageURLPolicyEvaluator.java, src/test/java/org/dependencytrack/policy/PackageURLPolicyEvaluatorTest.java
Validating purl-policies should now only return 1 violation.
Fixes #1925
Fixes #2212
Discussion of the solution can be found in #2330. Small change from the proposed solution there because of an already existing check for `null` on the `purl`.
=> Validating purl-policies should now only return 1 violation

src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
Checking the actual number of policies violated instead of the number of violations found, since this can be different and it broke policy that are configured for ALL conditions to (not) match.
Fixes #1924
Using the return-value of 'List.addAll' to check if any violations were added by the evaluator to add 1 to the counter. Changed the check on 'ANY' to also use this counter for a little performance-gain.
Also found a bug in the method `evaluate(List)`, which until now only returned the **last** list of violations instead of all -- found this because my new test wasn't failing on the old code although it should have.
=> Checking policies violated instead of violations to fix ALL-policy

src/main/java/org/dependencytrack/policy/CoordinatesPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/CpePolicyEvaluator.java, src/main/java/org/dependencytrack/policy/Matcher.java, src/main/java/org/dependencytrack/policy/PackageURLPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/SwidTagIdPolicyEvaluator.java, src/test/java/org/dependencytrack/policy/MatcherTest.java, src/test/java/org/dependencytrack/policy/PackageURLPolicyEvaluatorTest.java
Changed purl-policy validation to use 'matches()' instead of 'contains(), so RegExes can be used
Fixes #2144
In order to not need any changes in the database, all values will get turned into RegExes if needed --> previous behavior was 'String contains', so the values will get '.*' both pre- and appended, unless the new value is a RegEx that already has this (although this wouldn't really make a difference) or if they use anchors ('^' for start-of-line and '$' for end-of-line).
Branch includes the changes from #2333, so it should be merged first!
=> Changed purl-policy validation to use 'matches()' instead of 'contains(), so RegExes can be used

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
The information about the version status of a component is currently not displayed in the dependency graph, forcing users to switch to a different project tab, if they want to know about the version status.
This PR enhances the dependency graph to optionally display the version status information of a component on its corresponding node.
Frontend: [#358](https://github.com/DependencyTrack/frontend/issues/358)
[Frontend PR](https://github.com/DependencyTrack/frontend/pull/359)
**Note:** For the sake of better readability, the version status icon will only be shown for outdated components.
~- [ ] This PR introduces changes to the database model, and I have added corresponding [update …
=> Show version status information on dependency graph nodes

docs/_docs/getting-started/monitoring.md
Fix a typo in the monitoring section in README. Took me some hours to find this missing `d`
=> Fix Monitoring README

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
Modified the behaviour of ModelConverter to handle nested child components when processing dependencies. This prevents dependency information being lost, for example after a hierarchical merge using `cyclondx-cli`.
Closes #2411 
As requested I did add the ability to recurse in `ModelConverter.getComponentFromBomRef`, but ditched using that ability for a `HashMap` keyed on `bom-ref`.
I have tested this when deployed to check that it works. Below is the result of a hierachical merge between CycloneDX and Docker (Snyk) SBoMs:
I decided to not pass `flattenedComponents` to do other changes that would have affected external logic as I did not want to create more problems. The changes are focused the second part of `generateDependencies` where the transitives are processed.
Unfortunately I was …
=> Improved handling of hierarchical dependencies

src/main/java/org/dependencytrack/model/PolicyCondition.java, src/main/java/org/dependencytrack/policy/ComponentAgePolicyEvaluator.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/test/java/org/dependencytrack/policy/ComponentAgePolicyEvaluatorTest.java
This PR implements a policy condition for component age.
The age can be provided in [ISO-8601 period format](https://en.wikipedia.org/wiki/ISO_8601#Durations), e.g.:
* `P1Y`: 1 year
* `P2Y3M`: 2 years, 3 months
* `P7D`: 7 days
Lowest allowed time unit is days. Specifying hours, minutes, or seconds is not allowed.
This limitation is enforced by Java's [`Period`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Period.html) class, which is used behind the scenes.
The frontend will show a tooltip to let users know about the format.
Closes #772
We have to rely on external package repositories to provide the publish date of components. 
Not all repositories support this. In particular, for Rubygems and NPM components we currently do not get the publish date.
=> Add support for component age policy conditions

src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
Remove a superfluous dispatch of a `ComponentMetricsUpdateEvent` in `OSSindexAnalysisTask`.
The `OSSindexAnalysisTask` is emitting a `ComponentMetricsUpdateEvent` for each component that was analyzed.
This seems to be superfluous because `OSSindexAnalysisTask` is only triggered from a `VulnerabilityAnalysisTask` and that already triggers a `ProjectMetricsUpdateEvent` when analysis is complete. The latter will also update all metrics for all components in that project.
If my reasoning is correct, this PR will reduce the load on the event system. The `ComponentMetricsUpdateEvent` is the most frequently ocurring event, at least in my instance (7days):
It should go to zero as the `ProjectMetricsUpdateEvent` doesn't emit individual `ComponentMetricsUpdateEvent` instances, it performs the …
=> remove superfluous ComponentMetricsUpdate event dispatch

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Signed-off-by: Valentijn Scholten <valentijnscholten@gmail.com>
Handle deleted projects gracefully during `BomUploadEvent` (fixes #2458)
Handle deleted projects gracefully during `BomUploadEvent` (fixes #2458)
Should be rare, but still nice to not get ERRORs in your logs.
=> Bom Upload: don't choke on removed project

src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
This change correctly fixes the handling of the 'AND'-operator in policies, even if the policy consists of multiple conditions of the same type.
#1924
#2455
Seeing how the first fix did not take in consideration that multiple conditions of the same type were handled in a single evaluator, it only actually counted the number of evaluators that found violations.
This implementation actually checks how many conditions per evaluator where violated and compares those with the number of actual conditions defined for a policy.
=> Correctly fix the handling of operator 'AND' in policies

pom.xml
Adds the `log4j-over-slf4j` logging bridge which is needed to see `DataNucleus` log output.
Currently all DataNucleus logging is not logged. With the above dependency DataNucleus logs *can be* outputted.
In the default config no logs appear as the log level is WARN for the DataNucleus category by default.
This addition is usefule because:
- If there are WARN or ERROR log line outputted by DN, they will no longer be hidden from the log output;
- If a user wants to troubleshoot something around DN, they can now do that without having to build a custom container image;
The `log4j-over-slf4j.jar` is about `25kb` in size.
For those who want to log DN, they can add something like this to their `logback.xml`:
<logger name="DataNucleus" level="DEBUG" additivity="false">
<appender-ref ref="STDOUT" …
=> DataNucleus: Add logging bridge

src/main/java/org/dependencytrack/model/VulnerabilityAlias.java, src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java, src/main/java/org/dependencytrack/resources/v1/OsvEcosytemResource.java, src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java, src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java, src/test/java/org/dependencytrack/resources/v1/OsvEcosystemResourceTest.java, src/test/java/org/dependencytrack/tasks/OsvDownloadTaskTest.java
Signed-off-by: sahibamittal <sahiba.mittal@citi.com>
While selecting ecosystems for OSV mirroring, same ecosystem can be selected multiple times. This may cause duplicate downloading of one ecosystem (large files) from OSV client, which may result in repeated processing of already processed vulnerabilities.
Issue: https://github.com/DependencyTrack/dependency-track/issues/2473
1. Fix the selection of ecosystems to be unique list. Handle the list of ecosystems to be unique in backend.
2. Add a missing check in switch block for SNYK in VulnerabilityAlias.java (not related to this issue).
=> Issue-2473 : fix OSV ecosystem to be unique

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
See #2493 for details
Fixes a wrong check when cloning project. ACL where propagated only if they were none...
Fixes #2493
N/A
=> Fix: Cloning ACL when cloning project

src/main/java/org/dependencytrack/event/EpssMirrorEvent.java, src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java, src/main/java/org/dependencytrack/event/NistMirrorEvent.java
This PR slightly reduces the overall memory footprint of DT while NVD mirroring is taking place. 
It also enables search index updates while NVD and EPSS mirroring are running.
N/A
Because `IndexTask` also runs on `SingleThreadedEventService`, `IndexEvent`s queue up in the hundreds of thousands until the `NistMirrorTask` completes. As every `IndexEvent` may additionally contain objects of type `Project`, `Component`, `Vulnerability`, etc., keeping so many events in memory has a noticeable impact on heap utilization.
`IndexTask` *must* run on the single-threaded event service, as it's operations are spread across multiple events (create -> update -> commit), and they must be executed in sequence.
For NVD and EPSS mirroring however, they can be executed on the multi-threaded event service …
=> Execute `NistMirrorTask` and `EpssMirrorTask` on multi-threaded event service

src/main/java/org/dependencytrack/model/Vulnerability.java, src/main/java/org/dependencytrack/parser/epss/EpssParser.java, src/main/java/org/dependencytrack/parser/nvd/NvdParser.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java, src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
This PR lowers the memory footprint of mirroring operations, by disabling the "Second Level" cache of the object relational mapper we use (DataNucleus). **The cache is only disabled for mirroring operations, other areas of DT are not impacted**.
Prior to this change, heap usage would kreep up to almost 5.5 GB while mirroring the NVD and EPSS. Even after a manual GC invocation at the end, ~2.8 GB would still remain in heap.
After disabling L2 caching, overall heap usage stays lower (peaks at  ~4.2 GB), and a manual GC shows that pretty much the entire heap can be reclaimed.
N/A
Objects that are persisted (created, updated) are put into DN's second level cache. Per default, the cache keeps soft references to objects.
https://www.datanucleus.org/products/accessplatform_6_0/jdo/persistence.htm …
=> Disable DataNucleus L2 cache for mirroring tasks

src/main/java/org/dependencytrack/model/PolicyCondition.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/main/java/org/dependencytrack/policy/VulnerabilityIdPolicyEvaluator.java, src/test/java/org/dependencytrack/policy/VulnerabilityIdPolicyEvaluatorTest.java
The policy feature should support the vulnerability ID in a policy so that organisations can create policy related to particular vulnerability ID.
https://github.com/DependencyTrack/dependency-track/issues/2557
=> Issue-2557 : add vulnerability id in policy condition

src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
added bugfix for isPolicyAssignedToProjectTag to scan through all project tags
Currently the isPolicyAssignedToProjectTag method in the policyEngine class takes the first project tag and compares it with all the policy tags and if there is a match it returns true.
Expected behaviour is that all the tags of a project would be compared with all the tags of a policy and if there is a match this method would return true. This PR provides this fix
Fixes below issue:
Currently the isPolicyAssignedToProjectTag method in the policyEngine class takes the first project tag and compares it with all the policy tags and if there is a match it returns true.
=> Minor bugfix for PolicyEngine

src/main/java/org/dependencytrack/parser/snyk/SnykParser.java, src/test/java/org/dependencytrack/tasks/scanners/SnykAnalysisTaskTest.java
Remedies info in vulnerabilities reported by Snyk are not mapped currently. It is an additional and helpful info which can be used in DT. Map the remedies from Snyk (if available) to the recommendations in vulnerabilities in DT.
https://github.com/DependencyTrack/dependency-track/issues/2571
=> Issue-2571 : map Snyk remedies to recommendation

src/main/java/org/dependencytrack/exception/MetaAnalyzerException.java, src/main/java/org/dependencytrack/tasks/repositories/CargoMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/GemMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/GoModulesMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/HexMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/NpmMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/PypiMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java, src/main/java/org/dependencytrack/util/CacheStampedeBlocker.java, src/test/java/org/dependencytrack/util/CacheStampedeBlockerTest.java
Trivial exceptions around metadata analysis (component not found in unrelated repositories) were logged with error level and swallowed stacktraces. Moreover due to resilience4j configuration, this caused excessive retries slowing down the BOM upload process. This enhancement provides :
- Ability to provide `CacheStampedeBlocker` with a list of exceptions to ignore
- An unique and specific exception `MetaAnalyzerException` for repository metadata fetch unhandled issues
- `RepometadataAnalyzerTask` enhancement to instruct `CacheStampedeBlocker` to ignore `MetaAnalyzerException`
- Better exception logging with appropriate level and stack propagation
See #2456 
N/A
- ~This PR introduces changes to the …
=> Feature: Handle repository meta analyzers errors gracefully

src/main/java/org/dependencytrack/parser/snyk/SnykParser.java, src/test/java/org/dependencytrack/tasks/scanners/SnykAnalysisTaskTest.java
Mapping for publication time of vulnerability is missing while paring Snyk results. 
Added the missing mapping.
NA
=> Map Snyk publication time

docs/_docs/getting-started/monitoring.md, src/main/docker/Dockerfile, src/main/java/org/dependencytrack/health/HealthCheckInitializer.java, src/main/webapp/WEB-INF/web.xml
This PR utilizes https://github.com/stevespringett/Alpine/pull/480 to provide a meaningful health endpoint.
It currently only uses a readiness check for database connections, but may / should be extended in the future with more checks.
Closes #1001
The default health check interval in `Dockerfile` has been reduced from 5min to 30sec. 5min is way too long to identify unhealthy services.
=> Add health endpoint

src/main/resources/templates/notification/publisher/msteams.peb
The MSTeams notification shows blank entries:
This PR replaces the "dependency" key with "component" just like the Slack integration does it.
#2638
Manually tested
=> Change dependency to component to show info again

src/main/java/org/dependencytrack/upgrade/v480/v480Updater.java
This PR fixes an issue where existing config properties are not migrated correctly from the `jira` to the `integrations` namespace.
Upgrades are executed before `ConfigProperty` defaults are populated. The current upgrade logic attempts to `UPDATE` properties that don't exist yet when the upgrade is executed.
Tested on H2, Postgres 14, and MSSQL 2022
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency …
=> Fix migration of Jira config property group name

src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
This PR fixes a defect where `POLICY_VIOLATION` notifications were sent not only for newly identified violations, but also for already existing ones.
Fixes #2655
N/A
=> Fix redundant notifications for existing policy violations

src/main/java/org/dependencytrack/parser/nvd/NvdParser.java, src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java, src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
This PR makes further improvements to the resource efficiency of the NVD mirroring task.
Relates to #2524 
I was able to identify multiple memory hogs and causes of excessive allocations.
* The DataNucleus query compilation cache was bypassed for fetch methods that were called *very* frequently (see #2540)
* Some HTTP response and file streams were kept open for the entire duration of their respective processing, preventing related objects to be GC'd
* NVD feed files were previously parsed using [JSON-P](https://javaee.github.io/jsonp/). Uncompressed feed files can be ~100mb in size. Loading and parsing them into memory at once caused a lot of objects to be created that, for some reason, couldn't be GC'd in a timely manner. Switching to [Jackson …
=> Reduce heap usage during NVD mirroring

src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
The task works in such a way that a single `QueryManager` (and thus DN `ExecutionContext` and associated transaction) is shared across analyses of multiple components. Failure to analyze one component does not abort the overall analysis for all components.
Due to missing transaction rollbacks, the `RepositoryMetaAnalyzerTask` could end up in a situation where the `QueryManager`s active transaction failed to commit for one component, such that persisting of results for all following components would fail with `NucleusTransactionException: Invalid state. Transaction has already started`.
This fix is a mere workaround for the missing rollback of the `persist` method. https://github.com/DependencyTrack/dependency-track/issues/2677 has been raised to address this for the entire application. …
=> Fix potential `Invalid state. Transaction has already started` in `RepositoryMetaAnalyzerTask`

src/main/java/org/dependencytrack/policy/CoordinatesPolicyEvaluator.java
Fixes #2135 (at least the original opening exception in there)
Fixes a possible nullpointer during policy evaluation.
The other `matches` method in this class seems to default to `true` for when the condition or part is empty, so I added that check for `versionMatches` as well. Not sure if this is the best/final/ultimate solution. But I am not actually using policies, just wanted to get rid of this NullPointer that can interfere with processing / policy evaluations. Maybe some checks should be added to not allow policies with empty fields? Or it should be made more clear what empty fields mean and handle them better.
There's another exception mentioned in #2135 around license policy evaluation, but I don't know what should be the result if the license group is empty (true or false).
- [] …
=> Policy Evaluator: add null check to versionMatches

src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
Common/harmless errors should be logged on a reasonable log level, for example `WARN`
Currently common errors like no response are logged as `ERROR`
Also th eexception details were not logged, making it time consuming to deduce the exact cause of the exception.
~~- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~~
~~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~~
~~- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic]~~(https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
~~- [ ] This PR introduces new or alters existing behavior, and I have updated the …
=> repo meta analyzer: lower log level, do not swallow exception details

src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java, src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
When an email alert is configured without populating the *Destination* field, but by assigning teams to it, sending of alerts would fail with a `NullPointerException`.
The cause was the code expecting the *Destination* to never be not set. This PR fixes the issue by adding additional `null` checks.
Fixes #2698
N/A …
=> Fix NPE for email alerts without explicit destination

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
This PR fixes a defect where policy violations listed for a project are not searchable. The fix adds missing filtering logic based on policy name or any specific component name.
Fixes #2622
N/A
=> Fix policy violation search

DEVELOPING.md
fixed minor typo in url linking to dt documentation
Found a broken link (docs.dependecytrack.org instead of docs.depende**n**cytrack.org) when checking out the DEVELOPING.md.
=> Fixing broken link in DEVELOPING.md

src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoClient.java, src/test/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploaderTest.java
This PR fixes NPEs in the DefectDojo integration, which occurred when the `scan_type` field in DD responses was `null` or not set at all.
Fixes #2628
=> Fix NPE in `DefectDojoClient` when `scan_type` of a test is `null`

src/main/docker/Dockerfile
`java` is currently executed from within a shell (default `ENTRYPOINT` of the base image). This is required because the `CMD` makes use of variable substitution not available outside a shell.
The problem is that in doing so, the JVM process does not receive a `SIGTERM` signal when the container runtime stops the container (e.g. via `docker stop`). This prevents Dependency-Track from performing a graceful shutdown.
See also:
* https://stackoverflow.com/a/31840306
* https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/
Credit to @valentijnscholten for discovering this. https://owasp.slack.com/archives/C6R3R32H4/p1684243000301239
N/A
N/A
- ~This PR implements an enhancement, and I have …
=> Use `exec` to launch JVM process in container

.github/workflows/_meta-build.yaml, .github/workflows/ci-publish.yaml, .github/workflows/ci-release.yaml, docs/Gemfile, docs/_docs/getting-started/configuration.md, pom.xml, src/main/docker/Dockerfile, src/main/resources/application.properties
ORIGINAL PR #2725 
Consolidated dependency updates
| Package | Type | Update | Change |
|---|---|---|---|
|'~mysql:mysql-connector-java '~| compile | patch | '~8.0.29 -> 8.0.33 '~|  
|org.glassfish.jaxb:jaxb-runtime (source) | compile | patch | 2.3.6 -> 2.3.8 | 
|org.postgresql:postgresql (source) | compile | minor | 42.5.1 -> 42.6.0 | 
|eclipse-temurin | stage | patch | 17.0.6_10-jre-focal -> 17.0.7_7-jre-focal | 
|com.microsoft.sqlserver:mssql-jdbc | compile | major | 11.2.3.jre17 -> 12.2.0.jre11 | 
|'~jekyll '~|   | major | '~3.8 -> 4.0 '~ | 
|'~org.eclipse.jetty:jetty-maven-plugin (source) '~| build | major | '~10.0.15 -> 11.0.15 '~| 
Upgrades not compatible at this time:
- [mysql:mysql-connector-java ](#1970 )
- [org.eclipse.jetty:jetty-maven-plugin](#2727  )
Postponed:
- jekyll per …
=> Consolidated Dependency Updates (Take2)

src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java, src/main/java/org/dependencytrack/event/PolicyEvaluationEvent.java, src/main/java/org/dependencytrack/event/RepositoryMetaEvent.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/main/java/org/dependencytrack/resources/v1/FindingResource.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/main/java/org/dependencytrack/tasks/PolicyEvaluationTask.java, src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java, src/main/java/org/dependencytrack/tasks/scanners/VulnDbAnalysisTask.java, src/test/java/org/dependencytrack/event/PolicyEvaluationEventTest.java, src/test/java/org/dependencytrack/event/RepositoryMetaEventTest.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Separate policy evaluation into its own task
closes #2423 
I've chained the VulnerabilityAnalysisEvent and the RepositoryMetaEvent as both are needed for example when evaluating an VersionDistancePolicyEvaluator (#2528 )
N.B. no new tests added. I assume it's covered in excisting tests as there is no logical change? Will check on this...
=> Separate policy evaluation into its own task

src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/model/ProjectVersion.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Added transient List of ProjectVersions and set Metrics in Project to minimize the number of round trips a client needs to make
fixes: https://github.com/DependencyTrack/frontend/issues/397
Used by: https://github.com/DependencyTrack/frontend/pull/440
=> Added transient List of ProjectVersions and set Metrics in Project

src/main/java/org/dependencytrack/policy/AbstractPolicyEvaluator.java, src/test/java/org/dependencytrack/policy/ComponentHashPolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/CoordinatesPolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/CpePolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/LicensePolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/PackageURLPolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/SwidTagIdPolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/VersionPolicyEvaluatorTest.java
In `org.dependencytrack.policy.AbstractPolicyEvaluator`, there is a `QueryManager` created while instance initialization, https://github.com/DependencyTrack/dependency-track/blob/a7e512235c33b650decc90a8c12ceedc5234c6d9/src/main/java/org/dependencytrack/policy/AbstractPolicyEvaluator.java#L37-L41
and later overwrite by it's setter which is called in `VulnerabilityAnalysisTask` execution, therefor the older instance of `QueryManager` will never get closed, so it leads to a memory leak.
https://github.com/DependencyTrack/dependency-track/blob/a7e512235c33b650decc90a8c12ceedc5234c6d9/src/main/java/org/dependencytrack/policy/PolicyEngine.java#L88
https://github.com/DependencyTrack/dependency-track/issues/2785#issuecomment-1621497318
=> Fix memory leak issue in policy evaluation

src/main/java/org/dependencytrack/exception/PolicyException.java, src/main/java/org/dependencytrack/model/PolicyCondition.java, src/main/java/org/dependencytrack/policy/ComponentAgePolicyEvaluator.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java, src/main/java/org/dependencytrack/util/VersionDistance.java, src/test/java/org/dependencytrack/policy/VersionDistancePolicyEvaluatorTest.java, src/test/java/org/dependencytrack/util/VersionDistanceTest.java
Dependenct Track now supports a Component Age policy and a Component Version policy, but both are unsuitable to detect outdated components. For this the distance between the current component version and it's latest version needs to be analysed.
The VersionDistancePolicyEvaluator evaluates the VersionDistance between a Component's current and it's latest version. The policy "greater than 0:1.?.?" for example, means  a difference of only one between the curren version's major number and the latest version's major number is allowed.
Combining VersionDistances is also supported: "greater than 1:1.?.?". This way multiple parts (epoch or major) number can be considered in one go, combining them with a Boolean OR. Not sure yet if this will be supported in the UI...
closes #2528, addresses #208, …
=> New VersionDistance policy to check and report outdated components

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java, src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java, src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java, src/main/java/org/dependencytrack/resources/v1/vo/DependencyGraphResponse.java, src/test/java/org/dependencytrack/ResourceTest.java, src/test/java/org/dependencytrack/resources/v1/DependencyGraphResourceTest.java
In this PR I create two new endpoints `GET /api/v1/dependencyGraph/project/{uuid}/directDependencies` and 
`GET /api/v1/dependencyGraph/component/{uuid}/directDependencies`.
The purpose of this endpoint it's to avoid the frontend from doing multiple requests to the backend to fetch each node of the Dependency Graph. With this endpoint, you can get all directDependencies of a project or a component by providing his UUID.
fixes https://github.com/DependencyTrack/dependency-track/issues/2255
The frontend changes are available in this PR : https://github.com/DependencyTrack/frontend/pull/455
=> Issue 2255: create endpoint to fetch many components and services

docs/_docs/getting-started/database-support.md, pom.xml
Adds database connectors to facilitate securely connecting to Cloud SQL with IAM and MTLS encryption. This is the easiest way to connect securely when running Dependency Track on GCP.
This includes Cloud SQL for Postgres, MySQL, and SQL Server.
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory
This socket factory also adds to capability to connect to databases through unix sockets: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc-postgres.md#connection-via-unix-sockets
Closes #2650
=> Include Cloud SQL database connectors

src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v490/v490Updater.java
This changes the default version for new DT deployments, and updates the version for existing ones, **if the version has not been changed already**.
`2023-06-22` is the most recent stable version according to apidocs.snyk.io. Tested and confirmed that it's working fine with DT's integration.
N/A
N/A …
=> Update Snyk API version to `2023-06-22`

.dockerignore, docs/_docs/getting-started/deploy-docker.md, docs/_docs/getting-started/monitoring.md, src/main/docker/Dockerfile, src/main/docker/docker-compose.yml, src/main/docker/logback-json.xml
With https://github.com/stevespringett/Alpine/pull/503, Alpine is capable to write logs in JSON format.
This PR adds an example Logback configuration to make use of this capability, together with accompanying documentation.
Closes #2517
N/A
=> Add logging documentation and provide example Logback config for logging in JSON format

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java, src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
This PR fixes the CycloneDX VDR export to not contain components that are not affected by any vulnerability.
Fixes #2788
=> Fix VDR export containing non-vulnerable components

docs/_docs/usage/policy-compliance.md, src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java, src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpression.java, src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpressionOperation.java, src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxOperator.java, src/main/java/org/dependencytrack/parser/spdx/expression/package-info.java, src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/LicensePolicyEvaluator.java, src/main/java/org/dependencytrack/upgrade/v490/v490Updater.java, src/test/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParserTest.java, src/test/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluatorTest.java, src/test/java/org/dependencytrack/policy/LicensePolicyEvaluatorTest.java
Hi, I am very interested in seeing SPDX expression support in dependency-track.
I implemented a SPDX expression parser and reimplemented the license group policy evaluator and license policy evaluator logic.
It also implements the logic for the policy operator ALL, where previously violations were added if any policy condition is violated, regardless of the choice of the policy operator.
Addresses https://github.com/DependencyTrack/dependency-track/issues/170
The parser is based on the shunting yard algorithm for infix operators and parentheses.
- AND and OR operators work as expected.
- WITH operator works by converting `GPL-2.0 WITH classpath-exception` into a `GPL-2.0-with-classpath-exception` license, which is available in the default license list
- `+` operator is interpreted as …
=> Implement SPDX expressions

pom.xml
When using java modules, it is forbidden to add classes to namespaces that are already taken by other modules. The javax.xml namespace is currently provided by the java runtime as well as the xml-apis dependency (depended on via the xercesImpl dependency). The functionality that xml-apis brings is fully provided by the runtime, making the dependency unnecessary.
Eclipse is strict about this restriction and was showing corresponding errors.
Exclude the xml-apis dependency while depending on xercesImpl to make eclipse happy.
Fixes #2970
=> Exclude xml-apis dependency

src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/model/validation/SpdxExpressionValidator.java, src/main/java/org/dependencytrack/model/validation/ValidSpdxExpression.java, src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java, src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpression.java, src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpressionOperation.java, src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxOperator.java, src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/main/java/org/dependencytrack/upgrade/v490/v490Updater.java, src/test/java/org/dependencytrack/PersistenceCapableTest.java, src/test/java/org/dependencytrack/model/validation/SpdxExpressionValidatorTest.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Building upon #2400, this PR adds missing functionality for setting license expressions via REST API, and adds expression validation for both REST API and BOM ingestion.
Invalid expressions submitted via frontend or REST API will result in an API error, whereas invalid expressions encountered during BOM ingestion will be logged and skipped.
N/A
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/m …
=> SPDX expression support improvements

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java
Adding proper logging to warn users when VEX data is not taken into account because either :
- Vulnerability source/id on VEX does not match the one in DT database
- Vulnerability source on VEX is missing
Fix #2977
N/A
- ~[] This PR fixes a defect, and I have provided tests to verify that the fix is effective~
- ~[] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
- ~[] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
- ~[] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) …
=> feature: Adding proper logging to warn users when VEX data is not taken into account

src/main/java/org/dependencytrack/resources/v1/PolicyResource.java, src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
Allow `operator` and `violationState` to be specified when create policy.
In addition, to keep backward compatibility, default values are provided.
Closes https://github.com/DependencyTrack/dependency-track/issues/2365
The `violationState` is problematic, but so is the `operator`.
Currently, sending the `operator` and `violationState` parameters is ignored and the hard-coded values are used.
If these are to be changed to other values, a policy update is required, which is inefficient.
This is a problem specific to create policy since it is a required parameter in the model layer.
In order to maintain backward compatibility of create policy, a default value has been added.
- ~This PR …
=> Fix: allow operator and violationState to be specified when create policy

src/main/java/org/dependencytrack/policy/ComponentAgePolicyEvaluator.java, src/main/java/org/dependencytrack/policy/CwePolicyEvaluator.java, src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/LicensePolicyEvaluator.java, src/main/java/org/dependencytrack/policy/SeverityPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java, src/main/java/org/dependencytrack/policy/VersionPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/VulnerabilityIdPolicyEvaluator.java
This PR fixes a defect where the new version distance policy was being evaluated despite not being configured by users.
This PR additionally adds checks to policy evaluators that ensure that no expensive or potentially failing computation is being performed, *unless* the policy actually needs to be verified. This was previously not always the case, causing unnecessary database queries to be performed etc.
Fixes #2979
N/A
- ~This PR introduces new or alters existing behavior, and I have …
=> Fix version distance policy being evaluated despite not being configured

pom.xml, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
This PR fixes a bug that allowed duplicate project versions to be created via the cloning feature.
It also fixes:
* services not being cloned, despite `includeServices` being set to `true`.
* ACLs not being enforced for the `/clone` endpoint
And adds tests for cloning that were previously missing.
Fixes #2958 
N/A …
=> Fix project cloning allowing for duplicate versions

pom.xml
Update cyclonedx-core-java to 8.0.0.  Previous version used was SNAPSHOT for this release, so changes have already been tested.
Resolves #2850
Testing was performed using 7.4.0-SNAPSHOT, which was then bumped to 8.0.0 for release.  This was done via PR #3010 which uodates `BomResourceTest.java`
Manual testing consisted of ensuring that CycloneDX 1.5 BOMs can be succesfully imported to Dependency-Track.  ie,  no Exception thrown.  
No CycloneDX 1.5 functionality is yet supported.  But that now becomes possible using the updated cyclonedx-core-java library. …
=> Update cyclonedx-core-java to 8.0.0

src/main/docker/Dockerfile
Bumps the version of the temurin base image to  `21_35`.
This merely bumps the runtime JRE to Java 21 LTS. The code itself is still targeting Java 17. It allows us to benefit from JVM improvements while we work on making the switch to Java 21 in our codebase.
N/A
N/A …
=> Use Java 21 JRE in container images

dev/docker-compose.mssql.yml, docs/_docs/getting-started/database-support.md
Adds a recommendation to enable `READ_COMMITTED_SNAPSHOT` transaction isolation, in order to avoid deadlock issues with Microsoft SQL Server.
Additionally applies this recommendation to the development Docker Compose setup.
Relates to #3133
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master …
=> Recommend `READ_COMMITTED_SNAPSHOT` isolation for MSSQL

docs/_docs/getting-started/deploy-docker.md, docs/_docs/getting-started/openidconnect-configuration.md
While deploying DependencyTrack I noticed a few areas where the documentation around OpenID Connect could save some time. The OpenID connect login button and lack of support in the bundled containers both required a trip to the issue tracker to confirm.
=> Improve OIDC documentation

pom.xml, src/main/java/org/dependencytrack/model/RepositoryType.java, src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java, src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java, src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java, src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java, src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java
Add support for GitHub as a component source.
- Currently this feature can't be configured to use a specific GitHub account.
- The according repository (`github.com`) is added by default
- UI for new repositories is not added
Addresses https://github.com/DependencyTrack/dependency-track/issues/1840
Closes https://github.com/DependencyTrack/dependency-track/issues/1825
~- [ ] This PR introduces new or alters existing behavior, and I have updated the …
=> feat: Add support for github component sources

src/main/java/org/dependencytrack/parser/osv/OsvAdvisoryParser.java, src/test/java/org/dependencytrack/parser/osv/OsvAdvisoryParserTest.java, src/test/resources/unit/osv.jsons/osv-CVE-2016-10012.json
Fixes a `NullPointerException` when the `affected` node in OSV does not define a `package`, as observed for https://osv.dev/vulnerability/CVE-2016-10012.
Fixes #3185
N/A
=> Fix NPE when `affected` node in OSV does not define a `package`

docs/_docs/analysis-types/known-vulnerabilities.md, docs/_posts/2023-xx-xx-v4.10.0.md, pom.xml, src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java, src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java, src/main/java/org/dependencytrack/tasks/scanners/InternalAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
Fixes false positives in CPE matching by discarding matches where relations of the *vendor* and *product* attributes are ambiguous.
Previously, the following component CPE:
```
cpe:2.3:a:*:zstandard:1.5.2:*:*:*:*:*:*:*
```
was getting matched with the following CVE CPEs:
```
cpe:2.3:h:amd:*:*:*:*:*:*:*:*:*
cpe:2.3:a:pascom_cloud_phone_system:*:*:*:*:*:*:*:*:*
cpe:2.3:h:intel:*:*:*:*:*:*:*:*:*
```
Due to the *vendor* comparison yielding a `SUBSET`, and the *product* comparison yielding a `SUPERSET` relation. Both `SUBSET` and `SUPERSET` on their own can be considered a match, but in combination they can cause ambiguities like above.
Fixes #3178
~Depends on https://github.com/stevespringett/CPE-Parser/pull/181~
- ~This PR implements an enhancement, and I have provided tests to verify that …
=> Fix false positives in CPE matching due to ambiguous vendor/product relations

docs/_docs/integrations/notifications.md, docs/_posts/2023-xx-xx-v4.10.0.md, src/main/java/org/dependencytrack/model/NotificationRule.java, src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java, src/main/java/org/dependencytrack/notification/publisher/ConsolePublisher.java, src/main/java/org/dependencytrack/notification/publisher/CsWebexPublisher.java, src/main/java/org/dependencytrack/notification/publisher/DefaultNotificationPublishers.java, src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java, src/main/java/org/dependencytrack/notification/publisher/MattermostPublisher.java, src/main/java/org/dependencytrack/notification/publisher/MsTeamsPublisher.java, src/main/java/org/dependencytrack/notification/publisher/PublishContext.java, src/main/java/org/dependencytrack/notification/publisher/Publisher.java, src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java, src/main/java/org/dependencytrack/notification/publisher/SlackPublisher.java, src/main/java/org/dependencytrack/notification/publisher/WebhookPublisher.java, src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java, src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/ConsolePublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java, src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
It's hard to debug missing notifications, because Dependency-Track only logs something when an error occurred during notification publishing. Further, error logs currently do not contain any information about the notification or alert rule involved, making it harder to pinpoint *where* something is broken.
This PR adds more information to log messages emitted during publishing. This is done in form of `PublishContext`, which includes:
* The group of the notification (e.g. `NEW_VULNERABILITY`)
* The level of the notification (e.g. `INFORMATIONAL`)
* The scope of the notification (e.g. `PORTFOLIO`)
* The timestamp of the notification
* The subjects of the notification
* This is limited to "affected" project(s) (UUID, name, version), component (UUID, group, name, version), and  vulns …
=> Improve logging for notification publishing

src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java, src/test/java/org/dependencytrack/tasks/VulnerabilityAnalysisTaskTest.java
The change fixes the issue that during the processing of the PortfolioVulnerabilityAnalysisEvent
which re-analyzes all existing projects one after other
every next project to analyze was leading to the analysis of its own components 
and additonaly of all the components of the projects analyzed before it.
The result was very bad performance in cases the Dependency Track instance contains many projects.
Fixes #3219
The issue was in the global declaration of the lists containing the components to analyse.
The fix declares the lists on the local level so they only exist for one project.
Additonaly a unit test was implemented which does not test explicit the fix but ensures
the PortfolioVulnerabilityAnalysisEvent processing functionalty generally. This test was missing before.
~- [ ] This PR …
=> fix: do not increment amount of components

src/main/docker/Dockerfile
Adds a start period of 60s. The container is allowed to have failing health checks for this period without being considered unhealthy. 
Additionally adds a timeout for the `wget` command, and disables retries for it. This should prevent `wget` processes staying around for too long, eventually becoming zombie processes.
#3243
- ~This PR introduces new or alters existing behavior, and I have updated …
=> Tweak container health check to prevent `wget` zombie processes on slow hosts

src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/EventResource.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Return a token when cloning projects which can be used to query clone processing status.
Add an endpoint to query clone processing status.
Closes #2842 
I did not find an obvious way to also implement wrapping cloning in a transaction while using the processing tokens, so this part is not implemented.
=> Return processing token when cloning project #2842

src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Fixes notifications not being sent for child projects where `active` is `null`.
Fixes #3296
N/A
=> Fix notifications not being sent for child projects where `active` is `null`

src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Backports #3305 to 4.10.x.
Fixes #3296
N/A
=> Backport: Fix notifications not being sent for child projects where `active` is `null`

src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java, src/test/java/org/dependencytrack/policy/VersionDistancePolicyEvaluatorTest.java
Backports #3307 to 4.10.x.
Fixes #3295
N/A
=> Backport: Fix NPE in VersionDistancePolicyEvaluator when project has no direct dependencies

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Fixes `ClassCastException` when updating an existing `ProjectMetadata#authors` field.
Fixes #3309
Appears to be another incarnation of https://github.com/datanucleus/datanucleus-core/issues/500
=> Fix `ClassCastException` when updating an existing `ProjectMetadata#authors` field

src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java, src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java
Fixes an issue that caused the "last modified" timestamp for NVD mirroring via REST API to not be effective, unless the application is restarted.
https://github.com/DependencyTrack/dependency-track/issues/3293#issuecomment-1860699842
The timestamp is created with value `null` in a context where L2 caching is enabled (`DefaultObjectGenerator`), but updated in one where L2 caching is disabled (`NistApiMirrorTask#updateLastModified`). What's more, it's queried in a context with L2 caching enabled (`NistApiMirrorTask#inform`). This causes the property to be updated, but the cache not being invalidated, thus still serving queries.
To not have similar inconsistencies in other areas of the application, re-enable L2 caching when updating the property.
Eventually, L2 caching should be disabled …
=> Fix NVD API's last modified timestamp requiring restart to be applied

src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java, src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java
Backports #3322 to v4.10.x.
https://github.com/DependencyTrack/dependency-track/issues/3293#issuecomment-1860699842
N/A
=> Backport: Fix NVD API's last modified timestamp requiring restart to be applied

src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
ACL: Add projects to team should only show not yet added projects
Required for Frontend PR: https://github.com/DependencyTrack/frontend/pull/662
https://github.com/DependencyTrack/frontend/issues/101
=> ACL: Add projects to team should only show not yet added projects

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/vo/CloneProjectRequest.java, src/main/java/org/dependencytrack/tasks/CloneProjectTask.java, src/test/java/org/dependencytrack/event/CloneProjectEventTest.java, src/test/java/org/dependencytrack/persistence/PolicyQueryManagerTest.java
This PR adds cloning logic for policy violations, violationanalysis and violationanalysiscomments. 
Also adds a new parameter to the /clone API endpoint for communication with the frontend.
this PR is related to https://github.com/DependencyTrack/frontend/pull/655
#2875
=> Project cloning logic for cloning policy violations and Violationanalysis

src/main/java/org/dependencytrack/model/Vulnerability.java, src/main/java/org/dependencytrack/parser/nvd/NvdParser.java, src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java, src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java, src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java, src/main/java/org/dependencytrack/upgrade/v4110/v4110Updater.java, src/test/java/org/dependencytrack/model/VulnerabilityTest.java, src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
Stores computed severities in the database, instead of calculating it in-memory.
This extends #3287 in the following ways:
* Alter the behavior of `Vulnerability#setSeverity` to *not* clear vectors and scores anymore
* Address more code areas that create or update vulnerability data, ensuring that severity is always being set
* During the migration from v4.10.x, update severities of existing vulnerabilities in batches of 500, drastically decreasing database round-trips
Closes #2474
N/A
=> Store computed severities in the database

src/main/java/org/dependencytrack/model/Vulnerability.java, src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java, src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java, src/main/java/org/dependencytrack/resources/v1/vo/AffectedProject.java
Enhance API to support feature enhancement: https://github.com/DependencyTrack/frontend/issues/722
=> feat(vulnerabilities): enhance API to support frontend changes for active/inactive affected projects

src/main/java/org/dependencytrack/parser/vulndb/VulnDbParser.java
Without this condition, parsing the `nvd_additional_information` field given as an empty array would fail. This fixes #3436.
A condition was added to DT's VulnDB parser that checks whether the `nvd_additional_information` field of a vulnerability record is empty and skips its processing. Otherwise, the parsing would fail as described in #3436.
=> Fix VulnDB parser being unable to import vulnerability records when 'nvd_additional_information' is empty

src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java, src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
- Email Subject Prefix is Hardcoded rightnow `.subject("[Dependency-Track] " + notification.getTitle())`, 
- This is a solution to allow the User to modify the Subject Prefix to its will  `.subject(smtpPrefix + " " + notification.getTitle() )`
This modification would be available in `Administration>Configuration>Email` 
and ` "[Dependency-Track]"` would be the first default value. 
If the User change the Subject Prefix, it will need to press Update button in order to save the changes.
Subject Prefix is **not a required field** so leaving the input box in blank is also an option.
**_This new feature helps to distinguish between several instances of Dependency-Track, e.g. prod and qual systems._**
This PR depends on its corresponding PR in the **frontend** repository …
=> Subject prefix

docs/_docs/integrations/notifications.md, src/main/java/org/dependencytrack/notification/NotificationConstants.java, src/main/java/org/dependencytrack/notification/NotificationGroup.java, src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java, src/main/java/org/dependencytrack/notification/publisher/Publisher.java, src/main/java/org/dependencytrack/resources/v1/UserResource.java, src/main/java/org/dependencytrack/util/NotificationUtil.java
This PR adds two new notification types (user_created and user_deleted) and the possibility of setting a token on the webhook alert
Closes #3255
Closes #3256
=> Webhook alert token and new user alerts

dev/scripts/data-nist-generate-dummy.sh, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java, src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
Adds possibility to enter an attribution date value when adding a vulnerability to a project, used in cloning operation.
attribution dates where not passed on when cloning a project. This lead to all cloned vulnerabilities having attribution dates equals to that of the action performed. The attribution date has been added to all necessary methods and can be nullified if not needed.
Fixes #3464
=> Finding Attributed On date is not retained when cloning projects

dev/monitoring/grafana/dashboards/apiserver.json, docs/_posts/2024-xx-xx-v4.11.0.md, docs/files/grafana-dashboard.json, src/main/java/org/dependencytrack/common/ConfigKey.java, src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java, src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java, src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/main/java/org/dependencytrack/util/RetryUtil.java, src/main/resources/application.properties, src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java
Aligns retry configuration and behavior across analyzers:
* Align property names
* Retry backoff durations are now specified in milliseconds instead of seconds
* Reduce retry attempts and retry durations for OSS Index; The previous defaults were excessive
* Ensure that retries are only performed under certain transient error conditions, not for *any* error
* Provide a common mechanism to log when retries are performed, when max attempts were exceeded, or errors were not considered for retries
Potentially relates to #2857
N/A
- ~This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/or …
=> Align retry configuration and behavior across analyzers

README.md
Current CI Build badge is incorrect - this change fixes it.
There is no separate Issue for that - because it is a simple fix.
=> Fix CI Build status badge

src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/model/Project.java
Adds a custom deserializer for pURL properties of Project and Component objects. This deserializer allows to describe pURL either as text value or object value in JSON payloads to better conform to the swagger api definitions.
Fixes: #3509
=> Fix type of `purl` fields in Swagger docs

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
On import of SBOMs with SPDX compliant license ID in the `name` field and with no `id` field, license resolution should first occur against standard licenses. 
If none found, only then should license resolution occur against custom licenses.
Fixes #3433 
On SBOM import, if the license candidate/license option did not have an `id` field and only a `name` field, we were assuming the license to lookup would be a custom license (whereas in fact, the `name` field could contain a standard license ID and not a custom one)
In this change, during BOM upload, if license does not have an `id`, then we call `qm.getLicense()` with the `name` field first. If it returns no results, only then do we call `qm.getCustomLicense()`
Sample SBOM used for testing is attached to this PR: …
=> Perform License Resolution On Name Field During SBOM Import

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
When an SBOM is re-uploaded with different license information on an already imported component, the component should be updated with the new license.
Similarly, if license information previously existed on a component but not on a subsequent SBOM upload, the resolved license should be deleted from the component
Fixes #3498 
In the V1 BomUploadProcessingTask, we were looking up licenses _only_ if the component does not have a `resolvedLicense` already.
In such a case, if a new SBOM with an updated license for the component was uploaded, `component.getResolvedLicense() == null` will be false, since the component already had a previously resolved license and we would ignore the new license. Hence, removed this null check for `getResolvedLicense()`.
On a similar note, the logic to lookup …
=> Update License Of Existing Components On BOM Upload

docs/_posts/2024-xx-xx-v4.11.0.md, src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/VexResource.java, src/main/java/org/dependencytrack/resources/v1/exception/JsonMappingExceptionMapper.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java, src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Provides a meaningful error message for `bom` and `vex` exceeding Jackson's character limit.
Also document the limitation in the OpenAPI spec of the respective `PUT` methods that accept JSON payloads.
Fixes #3182
Example response for the `PUT /api/v1/bom` endpoint:
```json
{
"status": 400,
"title": "The provided JSON payload could not be mapped",
"detail": "The BOM is too large to be transmitted safely via Base64 encoded JSON value. Please use the \"POST /api/v1/bom\" endpoint with Content-Type \"multipart/form-data\" instead. Original cause: String length (20000001) exceeds the maximum length (20000000) (through reference chain: org.dependencytrack.resources.v1.vo.BomSubmitRequest[\"bom\"])"
}
```
- ~This PR implements an enhancement, and I have provided tests to verify that it works as …
=> Provide meaningful error message for `bom` and `vex` exceeding Jackson's character limit

docs/_posts/2024-xx-xx-v4.11.0.md, src/main/java/org/dependencytrack/resources/v1/exception/NotFoundExceptionMapper.java, src/test/java/org/dependencytrack/resources/v1/exception/NotFoundExceptionMapperTest.java
Fix unhandled `NotFoundException`s causing a `HTTP 500` response
N/A
Previously, requests to routes that had no explicit servlet mapping ended up being handled by the `GlobalExceptionHandler` of Alpine, which logs the exception as `error`, and returns a `HTTP 500 Internal Server Error` response. This behavior was misleading and could flood the logs unnecessarily.
We now only return a `HTTP 404 Not Found` response, without emitting any logs. …
=> Fix unhandled `NotFoundException`s causing a `HTTP 500` response

docs/_posts/2024-xx-xx-v4.11.0.md, src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/model/ComponentAnalysisCache.java, src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/upgrade/v4110/v4110Updater.java
Extends length of `PURL` and `PURLCOORDINATES` columns from 255 to 786.
Because PURLs are also used to populate the `TARGET` column of `COMPONENTANALYSISCACHE`, that column's length also has to be extended.
Fixes #2076
The length of 786 was chosen as a middle ground between the current 255 and the more optimal 1024. Mainly because MSSQL versions before 2016 have a maximum index key length of 900 (https://github.com/DependencyTrack/dependency-track/issues/2076#issuecomment-2002606197).
We don't want to break anything in that respect at the moment, and 786 should still be plenty of space.
Running DT with MySQL already takes manual effort, due to MySQL's even more restrictive key length limits (https://github.com/DependencyTrack/dependency-track/issues/271#issuecomment-1108923693). We're not …
=> Extend length of `PURL` and `PURLCOORDINATES` columns from 255 to 786

docs/_docs/integrations/rest-api.md, src/main/java/org/dependencytrack/resources/v1/TeamResource.java, src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
API keys should not be generated automatically for teams. Instead they should be generated manually when needed.
Fixes part of issue #2552.
Added unit test.
=> Disable automatic API key generation for teams. Fixes part of issue #2552.

src/main/java/org/dependencytrack/resources/v1/FindingResource.java, src/main/resources/templates/findings/sarif.peb, src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
If request header `Accept: application/sarif+json` is provided to the GET Finding By Project UUID API, it will now return a SARIF file with the vulnerability findings in that project.
SARIF file is generated based on a pebble template.
Closes #909 
In the  GET `/v1/finding/project/{uuid}` API, added a new Media Type `application/sarif+json` to the `@Produces`, to indicate the new response `Content-Type`.
Added a `sarif.peb` template file to a new directory under `templates/findings/sarif.peb`
Sample `bom.json` and it's resulting `.sarif` file is attached below:
[bom-and-sarif.zip](https://github.com/DependencyTrack/dependency-track/files/14631413/bom-and-sarif.zip)
I have tried to include most of the fields from `Finding.java` into a meaningful field in the `SARIF` file based on the …
=> Generate SARIF File Of Project Vulnerability Findings

.gitignore, pom.xml, src/main/java/org/dependencytrack/model/RepositoryType.java, src/main/java/org/dependencytrack/tasks/repositories/HackageMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java, src/main/java/org/dependencytrack/tasks/repositories/NixpkgsMetaAnalyzer.java, src/test/java/org/dependencytrack/tasks/repositories/HackageMetaAnalyzerTest.java, src/test/java/org/dependencytrack/tasks/repositories/NixpkgsMetaAnalyzerTest.java
This solves part 2 of #3545 
#3545 
this depends on #3546 
the apache http client utils version 4 don't implement brotli decompression; I redid some of the common http client code to keep this scoped; a future refactoring could remove the extraneous code.
=> Implement the hackage and nixpkgs meta analyzers

docs/_posts/2024-xx-xx-v4.11.0.md, src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/model/ComponentProperty.java, src/main/java/org/dependencytrack/model/validation/EnumValue.java, src/main/java/org/dependencytrack/model/validation/EnumValueValidator.java, src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentPropertyResource.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java, src/main/resources/META-INF/persistence.xml, src/test/java/org/dependencytrack/model/ComponentPropertyTest.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java, src/test/java/org/dependencytrack/resources/v1/ComponentPropertyResourceTest.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java, src/test/resources/unit/bom-1.xml
Adds support for component properties, similar to how project properties are supported already.
On top of being manageable via REST API, component properties are also ingested upon BOM upload.
Closes #2560
Closes #2715
Closes #2717
Closes #2991
Frontend PR: https://github.com/DependencyTrack/frontend/pull/811
=> Add support for component properties

docs/_docs/getting-started/monitoring.md, docs/_posts/2024-xx-xx-v4.11.0.md, src/main/java/org/dependencytrack/search/ComponentIndexer.java, src/main/java/org/dependencytrack/search/IndexManager.java, src/main/java/org/dependencytrack/search/IndexManagerFactory.java, src/main/java/org/dependencytrack/search/LicenseIndexer.java, src/main/java/org/dependencytrack/search/LoggingInfoStream.java, src/main/java/org/dependencytrack/search/ObjectIndexer.java, src/main/java/org/dependencytrack/search/ProjectIndexer.java, src/main/java/org/dependencytrack/search/ServiceComponentIndexer.java, src/main/java/org/dependencytrack/search/VulnerabilityIndexer.java, src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java, src/main/java/org/dependencytrack/tasks/IndexTask.java
Collect basic metrics:
* Total number of index operations (`add`, `update`, `delete`, `commit`), grouped by index
* Number of index documents in RAM
* Number of bytes used by the index
* Total number of documents in the index
Also, integrate Lucene's `InfoStream` with Dependency-Track's logging system. Lucene output will now be included when configuring `LOGGING_LEVEL=DEBUG`, or when the respective logger is explicitly configured in `logback.xml`.
Relates to #3429
Logging of Lucene messages can be enabled on a per-index basis:
```xml
<logger name="org.dependencytrack.search.VulnerabilityIndexer.lucene" level="DEBUG" additivity="false">
<appender-ref ref="STDOUT"/>
</logger>
```
It is also possible to enable logging selectively for specific Lucene components (e.g. for IndexWriter `IW`): …
=> Improve Lucene observability

docs/_posts/2024-xx-xx-v4.11.0.md, src/main/java/org/dependencytrack/resources/v1/openapi/PaginatedApi.java
Includes sorting query parameters in OpenAPI spec.
These parameters are handled implicitly by Alpine and as such are not directly documented in the Dependency-Track code base.
The `sortName` and `sortOrder` parameters are now included in the OpenAPI spec for all endpoints that support them.
N/A
=> Include sorting query parameters in OpenAPI spec

docs/_posts/2024-xx-xx-v4.11.0.md, src/main/java/org/dependencytrack/common/ConfigKey.java, src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java, src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java, src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Add support for experimental configurations
=> support for experimental configurations

src/main/java/org/dependencytrack/model/FindingAttribution.java, src/test/java/org/dependencytrack/model/FindingAttributionTest.java
Fixes `JDOFatalUserException` for long reference URLs from OSS Index.
When a reference URL won't fit in the respective database column, try to drop its query parameters first, and if that doesn't help (unlikely), make a hard cut at 255 characters.
N/A
Example occurrence of the exception in question:
```
javax.jdo.JDOFatalUserException: Attempt to store value "https://ossindex.sonatype.org/vulnerability/CVE-2023-47108?component-type=golang&component-`name=go.opentelemetry.io%2Fcontrib%2Finstrumentation%2Fgoogle.golang.org%2Fgrpc%2Fotelgrpc&utm_source=dependency-track&utm_medium=integration&utm_content=v4.11.0-SNAPSHOT" in column "REFERENCE_URL" that has maximum length of 255. Please correct your data!at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:67 …
```
=> Fix `JDOFatalUserException` for long reference URLs from OSS Index

src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java, src/main/java/org/dependencytrack/tasks/scanners/BaseComponentAnalyzerTask.java, src/main/java/org/dependencytrack/util/PersistenceUtil.java
When uploading many BOMs in bulk, it can happen that vulnerability and repository metadata analysis is performed multiple times for the same component identity in parallel. It is more likely to happen when the BOMs being uploaded have big overlap in terms of components they contain.
This can lead to unique constraint violations when DT updates the `COMPONENTANALYSISCACHE` table. Occurrences of this are non-critical, and kind of expected. Instead of letting the task crash, simply "accept" the exception and consider the job done.
Note that DataNucleus will log a warning even when we handle the exception.
N/A
N/A …
=> Gracefully handle unique constraint violations

src/main/java/org/dependencytrack/integrations/fortifyssc/FortifySscUploader.java, src/main/java/org/dependencytrack/integrations/kenna/KennaSecurityUploader.java, src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java, src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java, src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java, src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java, src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java, src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java, src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/main/java/org/dependencytrack/tasks/scanners/VulnDbAnalysisTask.java, src/main/java/org/dependencytrack/util/DebugDataEncryption.java, src/test/java/org/dependencytrack/util/DebugDataEncryptionTest.java
Logs debug information upon possible secret key corruption.
I was not able to reproduce the issue in question, so it's impossible to know why some users are experiencing secret decryption failures out of the blue.
If for whatever reason the secret key in-memory gets corrupted, we now try to reload it from disk once, and log a warning about it.
If on the other hand the encrypted value itself got corrupted (perhaps due to some bug in DataNucleus), we log a warning about that as well.
In both cases, the warning logs contain a reference to issue #2366.
Relates to #2366
- ~This PR introduces changes to the …
=> Log debug information upon possible secret key corruption

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/main/resources/templates/notification/publisher/msteams.peb, src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
Previously, the user was only notified of the result of the BOM processing.
Now the user is told the name of the project for each notificication, and for processing errors, they are also given the project URL
#3637 
This change modifies all the bom processing notification rather than just MS Teams ones. Adding the URL to BOM_PROCESSED might also make sense.
=> Add the project name and project URL to bom processing notifications

DEVELOPING.md, docs/_posts/2024-05-07-v4.11.0.md, pom.xml
Bumps the bundled frontend to version 4.11.0.
N/A
N/A
=> Bump bundled frontend to v4.11.0

src/main/java/org/dependencytrack/model/ProjectVersion.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
In order for the frontend to distinguish between active or inactive project versions, we need to include the `active` boolean field to `ProjectVersion` model.
Required for https://github.com/DependencyTrack/frontend/issues/844
=> Add active Field To Project Versions

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java, src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Fixes failing JSON BOM validation when `specVersion` is not one of the first fields.
Problem was that the search for `specVersion` was aborted upon encountering a `}` token. It should be `EOF` (or `null` in case of `JsonParser#nextToken`) instead.
Fixes #3696
N/A
=> Fix failing JSON BOM validation when `specVersion` is not one of the first fields

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java, src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Fixes failing JSON BOM validation when `specVersion` is not one of the first fields.
Problem was that the search for `specVersion` was aborted upon encountering a `}` token. It should be `EOF` (or `null` in case of `JsonParser#nextToken`) instead.
Fixes #3696
Backports #3697 
N/A
=> Backport: Fix failing JSON BOM validation when `specVersion` is not one of the first fields

src/main/java/org/dependencytrack/model/Finding.java, src/main/java/org/dependencytrack/model/GroupedFinding.java, src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java
Fixes broken global vulnerability audit view for MSSQL.
Tested with MSSQL, PostgreSQL, and H2.
Fixes #3692
MSSQL does not support `DISTINCT` for columns of type `TEXT`, which `DESCRIPTION` and `RECOMMENDATION` are.
Because the database schema is controlled by DataNucleus, and DataNucleus doesn't allow us to customize column types for specific RDBMSes, changing the respective columns to `VARCHAR(MAX)` is not possible.
`DISTINCT` was needed because finding rows are joined with the `PROJECT_ACCESS_TEAMS` table, to support portfolio ACLs. If a user is member of multiple teams, the query would yield a duplicate row for each permitted team the user is a member of.
The need for `DISTINCT` is eliminated by converting the ACL check from a `LEFT JOIN` to an `EXISTS` subquery.
- ~This PR implements …
=> Fix broken global vuln audit view for MSSQL

src/main/java/org/dependencytrack/model/Finding.java, src/main/java/org/dependencytrack/model/GroupedFinding.java, src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java
Fixes broken global vulnerability audit view for MSSQL.
Tested with MSSQL, PostgreSQL, and H2.
Fixes #3692
Backports #3700
MSSQL does not support `DISTINCT` for columns of type `TEXT`, which `DESCRIPTION` and `RECOMMENDATION` are.
Because the database schema is controlled by DataNucleus, and DataNucleus doesn't allow us to customize column types for specific RDBMSes, changing the respective columns to `VARCHAR(MAX)` is not possible.
`DISTINCT` was needed because finding rows are joined with the `PROJECT_ACCESS_TEAMS` table, to support portfolio ACLs. If a user is member of multiple teams, the query would yield a duplicate row for each permitted team the user is a member of.
The need for `DISTINCT` is eliminated by converting the ACL check from a `LEFT JOIN` to an `EXISTS` subquery.
- …
=> Backport: Fix broken global vuln audit view for MSSQL

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Handles PkgType trivy property
Fixes #3721
=> fix os handling when trivy sets pkgType on properties

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Handles PkgType trivy property
Fixes #3721 
Backports #3727
N/A
=> Backport: fix os handling when trivy sets pkgType on properties

src/main/java/org/dependencytrack/model/PolicyCondition.java, src/main/java/org/dependencytrack/policy/EpssPolicyEvaluator.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/test/java/org/dependencytrack/policy/EpssPolicyEvaluatorTest.java
This change will allow users to use EPSS scores in their policies. 
closes #3703
=> Add EPSS conditions to policies

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
On the "Components" tab, search components also by group. Today it only searches by name but some components use generic names and differentiate themselves by group. For example, @angular/corehas group @angular and name core, so searching for "angular" I don't get all the Angular packages on the results.
Closes #3749
Obs: Couldn't find any documentation about component search
=> Search component by group

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Fixes licenses not being resolved by name.
The name was already considered for resolution, but the matching was only performed on license IDs.
Fixes #3781
N/A
=> Fix licenses not being resolved by name

src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java, src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java
Nuget Analyzer has list of two supported SimpleDateFormat which are allowed for parsing the dates being received from the repository, based on limited test data.
Now, as seen in logs, below date format is also received from the nugget repo. This date has offset dateTime and needs to be added to the list of supported formats in order to avoid the ParseException.
Date example: 1900-01-01T00:00:00+00:00
Format needed: yyyy-MM-dd'T'HH:mm:ss
Backports #3736
N/A
- ~This PR introduces new or …
=> Backport: Add date format to support offset in NuGet timestamps

docs/_docs/getting-started/configuration.md, docs/_docs/getting-started/database-support.md, src/main/resources/application.properties
Updates database support docs.
* Raise supported versions for PostgreSQL and SQL Server to non-EOL versions
* Add notice about deprecation of RDBMSes other than PostgreSQL in DT v5
Backports #3712
N/A
=> Update database support docs

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Fixes licenses not being resolved by name.
The name was already considered for resolution, but the matching was only performed on license IDs.
Fixes #3781
Backports #3782
N/A
=> Backport: Fix licenses not being resolved by name

src/main/resources/templates/notification/publisher/slack.peb, src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
Fixes Slack notifications failing when no base URL is configured.
See https://github.com/DependencyTrack/dependency-track/issues/3742#issuecomment-2143465872 for details.
If no base URL is configured, the *View Component*, *View Project*, and *View Vulnerability* buttons will be omitted from the notification. Because they are intended to link back to Dependency-Track, it doesn't make sense to include them without valid URL.
Fixes #3742
N/A …
=> Fix Slack notifications failing when no base URL is configured

src/main/resources/templates/notification/publisher/slack.peb, src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java, src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
Fixes Slack notifications failing when no base URL is configured.
See https://github.com/DependencyTrack/dependency-track/issues/3742#issuecomment-2143465872 for details.
If no base URL is configured, the *View Component*, *View Project*, and *View Vulnerability* buttons will be omitted from the notification. Because they are intended to link back to Dependency-Track, it doesn't make sense to include them without valid URL.
Fixes #3742
Backports #3791
N/A
- ~This PR introduces new or …
=> Backport: Fix Slack notifications failing when no base URL is configured

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
When I update a component's data I supply external references for the component, as specified in API spec for /v1/component endpoint. The update is processed and 200 OK is returned, but when I read the component again, I can see no external references.
Closes https://github.com/DependencyTrack/dependency-track/issues/3769
=> Issue-3769 : fix update component external references

src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
Non-active projects only are shown when you view the page and after clicking show non-active projects, both active and inactive show, it is inverted.
#3832
=> vulnerabilityAudit incorrectly displaying non-active projects

src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
To be able to upload a bom and auto-create the project with specific tags
https://github.com/DependencyTrack/dependency-track/issues/1674
I have added the optional property to the PUT method to upload BOM files, I have not programmed much in Java so any suggestion to improve this PR is welcome.
Thanks!!!
=> feat: autocreate project with tags

src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
Non-active projects only are shown when you view the page and after clicking show non-active projects, both active and inactive show, it is inverted.
Fixes #3832
Backports #3839
N/A
=> Backport: Fix inverted "show inactive" filter in vulnerability audit view

pom.xml, src/main/java/org/dependencytrack/util/XmlUtil.java, src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Fixes BOM validation failing when URL contains encoded `[` and `]` characters.
Fixes #3831
Backports #3865 
N/A
=> Backport: Fix BOM validation failing when URL contains encoded `[` and `]` characters

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Fixes external references not being updated via `POST /v1/component`.
Fixes #3769
Backports #3805
N/A
=> Backport: Fix external references not being updated via `POST /v1/component`

src/main/java/org/dependencytrack/model/Finding.java, src/main/java/org/dependencytrack/model/VulnIdAndSource.java, src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java, src/main/java/org/dependencytrack/util/PurlUtil.java
The `/v1/finding/{projectUuid}` endpoint has historically been slow to respond (#3811). While the "main" query behind it is somewhat optimized SQL already, it still suffered from various performance killers:
* Filtering of suppressed findings was done in-memory, and required fetching of individual `Analysis` records *for every single finding*.
* `Clob` fields were not mapped directly from the SQL query result, but instead by re-fetching `Component` and `Vulnerability` records *for every single finding*, such that the ORM would provide properly `String`-ified field values.
* Aliases were fetched *for every single finding* individually.
* Latest component versions were fetched *for every single finding* individually.
Performance was improved via the following changes:
1. Filtering of …
=> Improve performance of findings retrieval

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Fixes `BOM_CONSUMED` and `BOM_PROCESSED` notifications being dispatched with wrong scope.
N/A
N/A
=> Fix `BOM_CONSUMED` and `BOM_PROCESSED` notifications being dispatched with wrong scope

src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/TagQueryManager.java, src/main/java/org/dependencytrack/resources/v1/TagResource.java, src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Deprecates `/api/v1/tag/{policyUuid}` in favor of `/api/v1/tag/policy/{uuid}`.
The deprecated endpoint is ambiguous.
See https://github.com/DependencyTrack/dependency-track/issues/586#issuecomment-1867101927
Relates to https://github.com/DependencyTrack/dependency-track/issues/586
N/A
=> Deprecate `/api/v1/tag/{policyUuid}` in favor of `/api/v1/tag/policy/{uuid}`

src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java, src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Fixes NPE when querying component metadata for projects without findings.
The method to bulk query component metadata turned out to return metadata for all components when given an empty list is input. Trying to correlate the returned data with the non-existent findings caused a NPE.
Regression introduced in #3869 
N/A …
=> Fix NPE when querying component metadata for projects without findings

src/main/java/org/dependencytrack/model/validation/ValidUuid.java, src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/TagQueryManager.java, src/main/java/org/dependencytrack/resources/v1/TagResource.java, src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java, src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Adds REST endpoints for bulk tagging & un-tagging of projects.
Relates to #586 
Bulk operations are currently limited to 100 projects per request. We can raise this limit if users need it. But for a beginning it's better to stay conservative since limiting it later would mean a breaking change.
Both `POST` and `DELETE` endpoints are implemented to be atomic operations.
Portfolio ACLs are considered:
* Trying to tag projects the user has no access to is a no-op
* Trying to un-tag projects the user has no access to is a no-op
There will be no `HTTP 403` response if tagging or un-tagging of inaccessible projects is attempted.
- ~This PR introduces changes to the database model, and I have added …
=> Add REST endpoints for bulk tagging & un-tagging of projects

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
A valid SPDX is required when using the ID field for licenses. If the license is a custom license, use the name field instead.
#3897
=> Set license name instead of ID when using custom license

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Fixes `BOM_CONSUMED` and `BOM_PROCESSED` notifications being dispatched with wrong scope for BOM processing V2.
Fixes #3880
Backports #3877 
N/A
=> Backport: Fix `BOM_CONSUMED` and `BOM_PROCESSED` notifications being dispatched with wrong scope for BOM processing V2

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Sets license name instead of ID when using custom license.
Fixes #3897
Backports #3915 
N/A
=> Backport: Set license name instead of ID when using custom license

src/main/java/org/dependencytrack/model/Tag.java, src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Fixes missing `projectTags` parameter for `POST /v1/bom` endpoint.
#3843 added the parameter to the JSON-based `PUT /v1/bom` endpoint.
Relates to #1674
N/A
=> Fix missing `projectTags` parameter for `POST /v1/bom` endpoint

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Logs a warning when dependency graph is missing the root node.
Also clean up code that is no longer necessary since Alpine v3, and apply consistent formatting for long method signatures.
Fixes #3989
N/A
=> Log warning when dependency graph is missing the root node

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java, src/test/resources/unit/bom-issue4008.xml
This PR contains a bugfix for gh-4008. I have also added a testcase, which was created by copying the bom-1.xml from another testcase.
The commit fixes a validation error that occurs when multiple namespace declarations are present in the BOM (in the wrong order).
n/a
=> Fix validation error when XML BOM declares multiple namespaces

src/main/java/org/dependencytrack/parser/trivy/model/Options.java, src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Handles breaking change in Trivy v0.54.0 server API.
See https://github.com/DependencyTrack/dependency-track/issues/4021#issuecomment-2260758711 for details.
Fixes #4021
Backports #4023 
N/A
=> Backport: Handle breaking change in Trivy v0.54.0 server API

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Fixes the `parent` field occasionally missing in `/api/v1/project/{uuid}` responses.
> [!NOTE]
> This is already fixed in v4.12. Refer to https://github.com/DependencyTrack/dependency-track/issues/4048#issuecomment-2275716424 for details.
Fixes #4048
N/A
=> Fix `parent` field occasionally missing in `/api/v1/project/{uuid}` responses

src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Ports regression test for `parent` field occasionally missing in `/api/v1/project/{uuid}` responses from #4049.
> [!NOTE]
> The underlying issue is already fixed in v4.12 / Alpine v3. Refer to https://github.com/DependencyTrack/dependency-track/issues/4048#issuecomment-2275716424 for details.
Relates to #4048
N/A …
=> Port regression test for `parent` field occasionally missing in `/api/v1/project/{uuid}` responses

src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/model/ProjectMetadata.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Fixes `directDependencies`, `externalReferences`, and `metadata` missing from `/api/v1/project/{uuid}` response when not already cached.
Since #4049, the endpoint returns only properties that are part of the `ALL` fetch group. The fields mentioned above were missing from this fetch group, and thus were not returned by the API, **unless the project was previously created or updated**.
The API ended up returning the fields field after modification of the project, which happened because they were in the L2 cache at that point.
Besides fixing the issue at hand, this change also extends the existing endpoint test to ensure that **all** fields are returned as expected.
Fixes #4074
N/A
- ~This PR …
=> Fix `directDependencies`, `externalReferences`, `metadata` missing from `/api/v1/project/{uuid}` response when not already cached

src/main/resources/application.properties
Disables H2 shutdown hook.
H2 registers a JVM shutdown hook to close the database upon reception of `SIGTERM`. However, the hook executes before the servlet context has shut down, so event processing can still be going on at that time, causing a flood of "database already closed" exceptions.
The H2 database is already closed as part of Alpine's `PersistenceManagerFactory#contextDestroyed` method, thus making the additional shutdown hook of H2 redundant anyway.
N/A
N/A …
=> Disable H2 shutdown hook

dev/docker-compose.mssql.yml, src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java
Add `AUTHOR` -> `AUTHORS` database migration.
Required by #3969
N/A
=> Add `AUTHOR` -> `AUTHORS` migration

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Handles empty component and service names.
`component.name` and `service.name` are required as per CycloneDX specification, but the schema doesn't sufficiently enforce this requirement (https://github.com/CycloneDX/specification/issues/461).
Because DT trims names from the BOM during model conversion, empty or blank names end up becoming `null`. Since the respective database columns have a `NOT NULL` constraint on them, inserting or updating such components will always fail.
Usually we would not want to try to "repair" data, but the name being empty appears to be so common that there's no other sensible way for us to deal with it.
With this change, empty names will end up being saved as `-` instead, to signal the absence of a proper value.
Fixes #2821
N/A
- ~This PR implements an …
=> Handle empty component and service names

src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java, src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
Audit changes submitted over API Keys are now logged with the corresponding team name as well.
Fixes [#3333](https://github.com/DependencyTrack/dependency-track/issues/3333)
~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~
=> Include team name in audit trail for API-submitted audit changes

src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java, src/test/java/org/dependencytrack/resources/v1/PolicyConditionResourceTest.java
Fixes infinite recursion during policy condition serialization.
N/A
As of Alpine v3, objects are no longer unloaded and refreshed (with fetch groups) during `QueryManager#persist`.
In case of the `PolicyCondition` REST endpoints, the previous behavior caused `PolicyCondition#policy` to be unloaded, prior to serializing the `PolicyCondition` response.
With persistent objects no longer being unloaded and refreshed in `QueryManager#persist`, that behavior changed, leading to infinite recursion when serializing `PolicyCondition#policy`.
Resolved the issue by restoring the previous behavior of not returning policy data in any of the condition endpoints.
- ~This PR introduces changes to the …
=> Fix infinite recursion during policy condition serialization

src/main/java/org/dependencytrack/resources/v1/TeamResource.java, src/main/java/org/dependencytrack/resources/v1/vo/VisibleTeams.java
/team/visible Endpoints no longer returns hole team, but instead only name and uuid.
Fixes [#4176](https://github.com/DependencyTrack/dependency-track/issues/4176)
N/A
~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~
=> Visible Endpoint returns only Visible Teams(name, uuid)

src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Caches Trivy DB for integration tests.
Trivy integration tests are failing in CI more frequently now, mostly because the Trivy container keeps downloading its vulnerability from ghcr.io, and the registry enforces rate limiting.
Cache the database between tests to prevent redundant downloads.
N/A
N/A
=> Cache Trivy DB for integration tests

src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/main/java/org/dependencytrack/util/PersistenceUtil.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Fixes breaking change in `PUT /api/v1/project` endpoint.
With #4093, the `accessTeams` field became a required request parameter if portfolio ACL is enabled. While it does make sense to enforce team assignment, it is a breaking change in the REST API and as such cannot be done in a minor version release.
Make `accessTeams` optional. Also:
* Enable `accessTeams` to be specified by `name`, not only by `uuid`
* Document this feature in the OpenAPI spec
* Reduce nesting in the `ProjectResource#createProject` method
* Enhance tests to be more explicit and assert response content
Relates to #4092
N/A …
=> Fix breaking change in `PUT /api/v1/project` endpoint

src/main/java/org/dependencytrack/model/Policy.java, src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/PolicyResource.java, src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java, src/main/java/org/dependencytrack/resources/v1/vo/CloneProjectRequest.java, src/main/java/org/dependencytrack/tasks/CloneProjectTask.java, src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java, src/test/java/org/dependencytrack/ResourceTest.java, src/test/java/org/dependencytrack/event/CloneProjectEventTest.java, src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java, src/test/java/org/dependencytrack/policy/PolicyEngineTest.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Frontend PR: https://github.com/DependencyTrack/frontend/pull/1017
Implements #4148 : 
1. Allows projects to be marked as "latest version" via API endpoints allowing creation and updating of projects
2. It is ensured only 1 project version (per project name) is marked as latest, previously marked version is no longer set to latest after a new version is set to latest
3. Allows policies to be limited to project versions marked as latest (e.g. helpful to only apply the version distance policy to the latest development version)
4. Fixed Bug: ProjectQueryManager contains 2 createProject() Methods, but only one triggered a PROJECT_CREATED event. Refactored both methods to use same implementation to avoid such inconsistencies.
closes #4148
=> feat#4148 introduce is latest project flag & allow policies to be limited to latest version

docs/_docs/integrations/badges.md, src/main/java/org/dependencytrack/auth/Permissions.java, src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java, src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java, src/main/java/org/dependencytrack/resources/v1/BadgeResource.java, src/main/resources/openapi-configuration.yaml, src/test/java/org/dependencytrack/ResourceTest.java, src/test/java/org/dependencytrack/auth/PermissionsTest.java, src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java, src/test/java/org/dependencytrack/resources/v1/BadgeResourceTest.java, src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
Enables Dependency-Track to offer badges in a secure manner and change the `badge` API from an opt-in-able, unauthenticated one into one requiring authentication with the new permission `VIEW_BADGES`, either via HTTP header or URI query parameter.
In the currently implementation, this as a breaking change (see Additional Details.)
Closes #3596 
As a first for DT's API, badges will allow authentication via URI query parameter, as badges are often retrieved from/embedded in clients that do not easily support an injection of headers.
The securing of badges behind API authentication and ACL can be done in two ways, either as a breaking change or gracefully with backwards compatibility: implement authentication with a new permission and
1. remove current checkbox enabling unauthenticated …
=> Enhance badge API to require authorization

src/main/java/org/dependencytrack/resources/v1/ProjectResource.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Ensures modifying project endpoints are transactional.
The `/api/v1/project` endpoints used to modify `Project` resources have historically not been transactional, potentially causing inconsistencies or too frequent commits (since every object modification implicitly creates a transaction behind the scenes).
Wrap code in `runInTransaction` or `callInTransaction` to ensure the desired transactional behavior.
N/A
N/A …
=> Ensure modifying project endpoints are transactional

src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
Fixes redundant `ConfigProperty` queries in `BadgeResource`.
If unauthenticated badge access is enabled, the same `ConfigProperty` was previously queried three times. Since badges are embedded in public places, it'd be beneficial if the respective resources avoided unnecessary work.
N/A
N/A
=> Fix redundant `ConfigProperty` queries in `BadgeResource`

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/main/java/org/dependencytrack/tasks/PolicyEvaluationTask.java, src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java, src/main/java/org/dependencytrack/util/LockUtil.java, src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
Prevents duplicate policy violations.
Introduces project-level locking for BOM upload processing, policy evaluation, and vulnerability analysis. This prevents duplicate records from being created during any of the mentioned activities. The locking happens in-memory.
Refactors policy violation reconciliation to be more deterministic and able to remove duplicates.
In a later release, a `UNIQUE` constraint should be added to the `POLICYVIOLATION` table to prevent duplicate records on the database-level (already done in Hyades).
Fixes #4215
N/A …
=> Prevent duplicate policy violations

src/main/resources/application.properties
Fixes unintended manual flushing mode due to DataNucleus `ExecutionContext` pooling.
For BOM upload processing, we customize the `PersistenceManager` for better performance: https://github.com/DependencyTrack/dependency-track/blob/6f7c49c0f2f163895b95e5b80554a49a3ec500f8/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L231-L259
It turns out that the custom options are internally delegated to a DataNucleus `ExecutionContext`. Other than `PersistenceManager`s, `ExecutionContext`s are never really closed, but instead reused (https://github.com/datanucleus/datanucleus-core/blob/master/src/main/java/org/datanucleus/ExecutionContextPool.java). Per default, DN pools up to 20 ECs.
The issue with this behavior is that customizing a PM in code location A, can unintentionally …
=> Fix unintended manual flushing mode due to DataNucleus `ExecutionContext` pooling

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/policy/PolicyEngine.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/main/java/org/dependencytrack/tasks/PolicyEvaluationTask.java, src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java, src/main/java/org/dependencytrack/util/LockUtil.java, src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
Prevents duplicate policy violations.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4215
Backports https://github.com/DependencyTrack/dependency-track/pull/4216
N/A
=> Backport: Prevent duplicate policy violations

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
Enhances the policy violation de-duplication logic introduced in https://github.com/DependencyTrack/dependency-track/pull/4216.
Relates to https://github.com/DependencyTrack/dependency-track/issues/4215
Backports https://github.com/DependencyTrack/dependency-track/pull/4231
N/A
=> Backport: Enhance policy violation de-duplication logic

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Fixes inaccuracies of the Trivy analyzer, which could lead to both too many, or too few vulnerabilities being reported.
The primary issue revolved around the incorrect transmission of epoch information to the Trivy server.
Relates to #4164 
=> Fix inaccuracies of Trivy analyzer

docs/_docs/getting-started/deploy-docker.md, src/main/docker/docker-compose.yml
- Updated the Deploying Docker Container guide to use Compose v2, so `docker compose` instead of `docker-compose`. Also added guidance for installing compose.
- Added the `ALPINE_OIDC_CLIENT_ID` environment variable to the Docker Compose example.
- Removed the top-level version element from the example and the `docker-compose.yml` file because it is [obsolete](https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete).
Closes #3939.
=> Update Deploying Docker guide to Compose v2

pom.xml
Introduce support for Amazon JDBC Driver, this will enhance security by eliminating the need for hardcoded credentials and will also allow DependencyTrack to fully leverage the benefits of clustered databases like Amazon Aurora.
#4303
=> Provide support for AWS JDBC Driver

src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
Fixes excessive memory usage of portfolio repository meta analysis.
Backports https://github.com/DependencyTrack/dependency-track/pull/4311
N/A
=> Backport: Fix excessive memory usage of portfolio repository meta analysis

src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java, src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java, src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
Reduces memory usage of metrics update tasks.
Because the tasks iterated over large datasets (i.e. all projects, or all components of a project), the DataNucleus L1 cache kept growing. Prevent this from happening by evicting objects from the cache after every iteration.
Also, because setting a `FetchGroup` on `Query` level doesn't overwrite the `FetchGroup` on `PersistenceManager` level, too many fields were being loaded. Use `ScopedCustomization` to overwrite the PM's `FetchGroup` when querying objects for metrics calculation.
N/A
Based on the fixes for repository meta analysis introduced in #4311. …
=> Reduce memory usage of metrics update tasks

src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java, src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java, src/test/resources/unit/nvd/api/jsons/cve-2024-23113.json
This aligns the CPE matching logic for NVD between the _feed_ and the REST API. I believe that when the logic was ported the nodeOperator was not properly copied over.
I added an additional unit-test to demonstrate where it previously failed and changing the operator does not break the previous unit-test either.
Fixes #4255 
- [~] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [~] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [~] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/ …
=> Fix CPE matching logic for NVD Rest

src/main/java/org/dependencytrack/model/Vulnerability.java
Added annotation for OpenAPI description.
Fixes #4349 
Now produces:
```json
"Vulnerability" : {
"cwes" : {
"type" : "array",
"items" : {
"$ref" : "#/components/schemas/Cwe"
}
},
```
=> Fix incorrect CWE schema in OpenAPI spec

src/main/java/org/dependencytrack/policy/ComponentHashPolicyEvaluator.java, src/test/java/org/dependencytrack/policy/ComponentHashPolicyEvaluatorTest.java
This is for [Component Hash policy condition only supports positive matches #4230](https://github.com/DependencyTrack/dependency-track/issues/4230)
[Component Hash policy condition only supports positive matches #4230](https://github.com/DependencyTrack/dependency-track/issues/4230)
**Local Testing Screenshots:**
=> Fix component hash policy evaluator

src/main/java/org/dependencytrack/resources/v1/ComponentResource.java, src/test/java/org/dependencytrack/tasks/PolicyEvaluationTaskTest.java
Fixes #4373 as suggested in the issue.
#4373 
The test `PolicyEvaluationTaskTest` does not exactly check the fix.
But I found it valuable since there seems to be no test case yet for `PolicyEvaluationTask`. I used it to study the behavior, it asserts another aspect.
=> Fix policy evaluation not happening upon creation or update of individual components

src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java, src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java, src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
Reduces memory usage of metrics update tasks.
Backports https://github.com/DependencyTrack/dependency-track/pull/4325
N/A
=> Backport: Reduce memory usage of metrics update tasks

src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java, src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java, src/test/resources/unit/nvd/api/jsons/cve-2024-23113.json
Fixes CPE matching for NVD mirroring via REST API.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4255
Backports https://github.com/DependencyTrack/dependency-track/pull/4339
N/A
=> Backport: Fix CPE matching for NVD mirroring via REST API

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Fixes Trivy analyzer vulnerability matching for Go packages.
Fixes #4376
Backports #4394
=> Backport: Fix Trivy analyzer vulnerability matching for Go packages

src/main/java/org/dependencytrack/resources/v1/BomResource.java
This allows the `/v1/bom/cyclonedx/component/{uuid}` endpoint to accept the `application/vnd.cyclonedx+json` media type just as the `/v1/bom/cyclonedx/project/{uuid}` endpoint does. 
Fixes #4408
=> Add cyclonedx json media type when exporting components

dev/docker-compose.mysql.yml, src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/model/ProjectVersion.java, src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/search/ComponentIndexer.java, src/main/java/org/dependencytrack/search/ProjectIndexer.java, src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java, src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v4122/v4122Updater.java, src/test/java/org/dependencytrack/model/ProjectTest.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Fixes `project.active` being nullable.
Ensure the field defaults to `true`, both in Java and the database. During upgrade, migrate all values that are currently `null` to `true`.
Solidify this change by switching `project.active` from `Boolean` to `boolean`. Adjust logic that previously had to check for `null`.
Fixes #4410
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/ …
=> Fix `project.active` being nullable

src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
Fix GitHub Advisory Mirroring task triggering too many notifications.
#4400
N/A
=> Move GHAM notification logic outside recursion

src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
Moves GHSA notification logic outside recursion.
Fixes #4400 
Backports #4401
N/A
=> Backport: Move GHSA notification logic outside recursion

dev/docker-compose.mysql.yml, src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/model/ProjectVersion.java, src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/search/ComponentIndexer.java, src/main/java/org/dependencytrack/search/ProjectIndexer.java, src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java, src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v4122/v4122Updater.java, src/test/java/org/dependencytrack/model/ProjectTest.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Fixes `project.active` being nullable.
Fixes #4410
Backports #4415
N/A
=> Backport: Fix `project.active` being nullable

src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java, src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
Fixes notification tests not working for Jira.
Fixes #4237
Backports #4456
N/A
=> Backport: Fix notification tests not working for Jira

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java, src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java, src/test/resources/unit/bom-issue4455.json
Fixes component de-duplication potentially causing duplicate dependency graph entries.
Fixes #4455
Backport #4458
N/A
=> Backport: Fix component de-duplication potentially causing duplicate dependency graph entries

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Fixes component SWID tag ID not being considered in project cloning.
Fixes #4478
Backports #4480
N/A
=> Backport: Fix component SWID tag ID not being considered in project cloning

src/main/java/org/dependencytrack/model/Component.java, src/main/java/org/dependencytrack/model/ComponentIdentity.java, src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java, src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Reduce database round-trips during BOM processing.
In the previous implementation, a `SELECT` query was issued for every single component and service in a BOM, in order to find existing components that match their identity.
In retrospect, this causes a lot of unnecessary database round-trips and puts the database under unnecessary stress, in particular for new projects where no components and services exist yet.
Now, we query all existing components and services of the project once in bulk. In addition to better performance in most situations, it also allows for more flexibility for component de-duplication in the future (#3861).
A situation where this approach can perform worse, is when a BOM is uploaded to an existing project, and the content differs wildly between BOM and project. We …
=> Reduce database round-trips during BOM processing

docs/_docs/datasources/vulndb.md
Just added a little reference to Flashpoint as they have acquired Vulndb. It may help users to not confuse it with https://vuldb.com/
=> Docs: Mention Flashpoint as new owner of Vulndb

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java, src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Fixes onlyOutdated filter when listing a project's components missing any ungrouped (outdated) components, such as Python packages.
Fixes #4510
N/A
=> Fix onlyOutdated ungrouped component filtering

src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
Make it more clear where the cache config properties are used.
The validity period is used for both Vulnerability and Metadata analysis.
The clearing cadence is only used to clear the Vulnerability analysis cache.
=> Component Analyse Cache: make description more clear

docs/_docs/integrations/badges.md
Remove deprecation notice for unauthenticated access to the Badge API, as the use of API keys for authenticated access comes with risks too that the maintainer of the DT instance has to weigh against the use of unauthenticated access which does not use API keys.
Closes #4500
=> Postpone deprecation of unauthenticated access to Badge API

src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java, src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/main/java/org/dependencytrack/persistence/QueryManager.java, src/main/java/org/dependencytrack/persistence/TagQueryManager.java, src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Fixes REST endpoints for adding tags.
The `/tag/{name}/project` endpoint did not add the provided tag to projects which already had tags assigned to them.
The `/tag/{name}/policy` and `/tag/{name}/notificationRule` endpoints replaced existing tags with the provided tag, which is not the intended behavior. Since only one tag can be provided via path parameter, the tag should be *added* to existing tags, not replace them.
Fixes #4539
N/A …
=> Fix REST endpoints for adding tags

src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v4123/v4123Updater.java
Recreates outdated check constraints for `CLASSIFIER` columns.
Fixes #4446
N/A
=> Recreate outdated check constraints for `CLASSIFIER` columns

src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
Add some DEBUG log lines to help debugging (possible/future) problems.
=> composer meta analyzer: add DEBUG logging

docs/_docs/integrations/rest-api.md
Clarifies where the OpenAPI endpoint is available because it is not obvious that it is not available from the public endpoint.
Fixes #4555
=> docs: Clarify OpenAPI endpoint location

docs/_docs/integrations/badges.md, docs/_docs/usage/cicd.md, docs/_docs/usage/collection-projects.md
Fix miscellaneous typos.
While HTTP headers are case-insensitive, these changes align the examples with the rest of the documentation and source code.
None.
- ~[ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~
- ~[ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
- ~[ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
- ~[ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~
=> Fix miscellaneous typos

docs/_docs/integrations/community-integrations.md
The open source vulnerability management system SecObserve has an API integration, to load vulnerabilities from Dependency Track. This is the reason, SecObserve should appear in the documentation for the community integrations.
There is no issue at the moment. Do we need one for this?
=> Add SecObserve to community integrations

src/main/docker/Dockerfile
Bumps Debian and Temurin base images to latest digest.
Doesn't appear to resolve any CVEs, but doing it for good measure anyway.
N/A
N/A
=> Bump Debian and Temurin base images to latest digest

src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java, src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java, src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Fixes possible NPEs during tag binding.
Fixes #4593
Backports #4594 
N/A
=> Backport: Fix possible NPEs during tag binding

src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
Fixes false negatives in CPE matching for ANY and NA versions.
Fixes #4609
N/A
=> Fix false negatives in CPE matching for ANY and NA versions

src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
Fixes false negatives in CPE matching for ANY and NA versions.
Fixes #4609
Backports #4610
N/A
=> Backport: Fix false negatives in CPE matching for ANY and NA versions

src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
Analyzes all components of a project at once instead of in batches.
Unfortunately this is necessary to support Trivy properly, because it checks for the existence of `OPERATING_SYSTEM` components in a project. If we were to analyze components in batches, this logic might not work for large projects.
Backports #4670
N/A …
=> Backport: Analyze all components of a project at once instead of in batches

src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
When the API token header and/or API token has not been set when configuring an Outbound Webhook notification endpoint, the HTTP request will include an empty http header.
This does not conform with [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616#section-4.2)
Fixes issue #4344.
=> Fix notification webhook sending blank headers

src/main/java/org/dependencytrack/parser/snyk/SnykParser.java, src/test/java/org/dependencytrack/parser/snyk/SnykParserTest.java, src/test/resources/unit/snyk.jsons/ranges.json
This PR addresses #4714 by adding support for the current version of the Snyk API.
Attempting to use version `2024-10-15` of the API results in the following error during analysis due to the response from `/orgs/{org_id}/packages/{purl}/issues` having changed shape:
```
2025-02-24 04:29:48,547 ERROR [SnykAnalysisTask] Request failure
java.lang.NullPointerException: Cannot invoke "org.json.JSONArray.length()" because "representation" is null
at org.dependencytrack.parser.snyk.SnykParser.parse(SnykParser.java:86)
at org.dependencytrack.tasks.scanners.SnykAnalysisTask.handle(SnykAnalysisTask.java:368)
at org.dependencytrack.tasks.scanners.SnykAnalysisTask.analyzeComponent(SnykAnalysisTask.java:332)
at org.dependencytrack.tasks.scanners.SnykAnalysisTask.lambda$analyze$1(SnykAnalysisTask.java:2 …
```
=> Add support for Snyk API version 2024-10-15

src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
Fixes NPE during NVD mirroring via REST API when encountering invalid CPEs.
Fixes #4731
N/A
=> Fix NPE during NVD mirroring via REST API when encountering invalid CPEs

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Removes erroneous client-side caching in Trivy analyzer.
Trivy already acts as a cache, there is no rate limiting we need to be careful with, and our cache wasn't ever used prior to 4.12.4 anyway.
Fixes #4704
Fixes #4727
N/A
=> Remove erroneous client-side caching in Trivy analyzer

src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Fixes notification limiting to tags not working reliably.
The code assumed inspected projects to be in persistent state, which they were in unit tests, but not at application runtime.
Notification subjects are always in detached state. `NotificationRouterTest` was updated to reflect this fact.
Fixes #4661
N/A …
=> Fix notification limiting to tags not working reliably

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java, src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Removes erroneous client-side caching in Trivy analyzer.
Trivy already acts as a cache, there is no rate limiting we need to be careful with, and our cache wasn't ever used prior to 4.12.4 anyway.
Fixes #4704
Fixes #4727
Backports #4735 
N/A
=> Backport: Remove erroneous client-side caching in Trivy analyzer

src/main/java/org/dependencytrack/model/Project.java, src/main/java/org/dependencytrack/notification/NotificationRouter.java, src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Fixes notification limiting to tags not working reliably.
The code assumed inspected projects to be in persistent state, which they were in unit tests, but not at application runtime.
Notification subjects are always in detached state. `NotificationRouterTest` was updated to reflect this fact.
Fixes #4661
N/A …
=> Backport: Fix notification limiting to tags not working reliably

src/main/java/org/dependencytrack/resources/v1/TagResource.java, src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Adds an endpoint to create multiple tags.
Closes #4755
Closes #4463
Don't know whether a POST is the correct method here, but since this ignores already existing tags, it seems to be better than a PUT.
=> add endpoint to mass-create tags

pom.xml
Removes aws-advanced-jdbc-wrapper again.
The driver is pulling in the entirety of the AWS SDK, increasing our JAR file size by over 20%, and introducing a whole bunch of transitive dependencies that will inevitably cause more noise when users scan our container images for vulnerabilities.
Currently there are vulns being reported for Netty libraries introduced through the AWS SDK. There is no newer SDK version that resolves them, which leaves us the only possibility of overriding transitive dependency versions. Given the many modules of Netty, this is like playing whack-a-mole.
Including AWS libraries is really not justifiable given how absolutely gigantic their dependency tree is. They become technical debt as soon as they're included.
Effectively reverts #4304
N/A
- ~This PR fixes a …
=> Remove aws-advanced-jdbc-wrapper again

src/main/java/org/dependencytrack/upgrade/v4131/v4131Updater.java
Fixes missing `NONE` value in classifier check constraint.
Fixes #4844
Backports https://github.com/DependencyTrack/dependency-track/pull/4884
N/A
=> Backport: Fix missing `NONE` value in classifier check constraint

src/main/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTask.java, src/test/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTaskTest.java
Fixes summary notifications not sent when "skip if unchanged" is enabled.
N/A
N/A
=> Fix summary notifications not sent when "skip if unchanged" is enabled

src/main/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTask.java, src/test/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTaskTest.java
Fixes summary notifications not sent when "skip if unchanged" is enabled.
Backports #4910
N/A
=> Backport: Fix summary notifications not sent when "skip if unchanged" is enabled

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java, src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
Added the trigger, when cloning occurs on a project, the clone project will have metrics its metrics update rather than just empty unless explicitly updated through the UI by refreshing metrics.
```
2025-04-02 11:21:58,857 INFO [CloneProjectTask] Cloning project for version 5.0.1.2 [eventToken=3a8a439d-ce14-45a6-a4b2-ccb59ad614aa, projectUuid=563edfa5-ec55-4858-9e75-56c2a94f905d]
2025-04-02 11:22:03,177 INFO [CloneProjectTask] Cloned project for version 5.0.1.2 into project e66979c3-b8ca-4c72-914e-bce20795197f [eventToken=3a8a439d-ce14-45a6-a4b2-ccb59ad614aa, projectUuid=563edfa5-ec55-4858-9e75-56c2a94f905d]
2025-04-02 11:22:03,178 INFO [ProjectMetricsUpdateTask] Executing metrics update for project e66979c3-b8ca-4c72-914e-bce20795197f
```
The change fixes …
=> Add Metrics update trigger after cloning a project

src/main/java/org/dependencytrack/tasks/repositories/AbstractMetaAnalyzer.java
While the program is running, I receive this log:
```
2025-04-18 11:17:40,885 ERROR [MavenMetaAnalyzer] Request failure
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
at …
```
=> handleRequestException: add baseUrl to log

pom.xml, src/main/java/org/dependencytrack/model/Vulnerability.java, src/main/java/org/dependencytrack/parser/github/ModelConverter.java, src/main/java/org/dependencytrack/parser/nvd/NvdParser.java, src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java, src/main/java/org/dependencytrack/parser/osv/OsvAdvisoryParser.java, src/main/java/org/dependencytrack/parser/vulndb/ModelConverter.java, src/main/java/org/dependencytrack/resources/v1/CalculatorResource.java, src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java, src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java, src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java, src/main/java/org/dependencytrack/util/CvssUtil.java, src/test/java/org/dependencytrack/parser/vulndb/ModelConverterTest.java, src/test/java/org/dependencytrack/resources/v1/CalculatorResourceTest.java, src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java, src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java, src/test/java/org/dependencytrack/tasks/NistMirrorTaskTest.java, src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java, src/test/java/org/dependencytrack/util/CvssUtilTest.java
Uses metaeffekt CVSS implementation instead of us.springett.cvss-calculator.
Preparing step for #4707.
Also seems to fix a few bugs in NistMirrorTask, NistApiMirrorTask and OssIndexAnalysisTask where CVSS 3.1 vectors were silently replaced with 3.0 ones.
=> switch cvss handling to metaeffekt

src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java
The vendor and product String parameters passed to fuzzySearch() might contain spaces, as the frontend does not prevent inputting strings containing spaces when manually creating a component. As far as I know CycloneDX and SPDX also do not restrict this, so imported components could also contain spaces in their name and vendor properties (unless they are sanitized when importing).
As `fuzzySearch()` creates a new CPE object which validates the attributes inside the constructor, this will cause exceptions to be logged for all components that contain spaces in name and/or vendor.
I have added a simple replace before passing these strings to the CPE constructor to prevent the exceptions from being thrown.
I have also renamed the private method `escape()` to `escapeLuceneQuery()` to be more …
=> Add whitespace sanitization in fuzzySearch CPE to fix CPE validation errors

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java, src/main/java/org/dependencytrack/resources/v1/BomResource.java, src/main/java/org/dependencytrack/resources/v1/VexResource.java, src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java, src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Version Parameter for exporting BOM/VEX Resources see #5062
Added optional Version parameter for exporting BOM's in specific Versions.
Closes #5062
* Added a simple, additional paramater for `version`. Instead of expanding the `if-elseif-else` branches, opted for earlier argument checks with corresponding exits. 
* Expanded Tests which were already testing the changed endpoints.
* Added additional positive and negativ tests 
-  [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
=> Implement Version Parameter when exporting BOM's

docs/_docs/FAQ.md, src/main/java/org/dependencytrack/policy/CoordinatesPolicyEvaluator.java, src/test/java/org/dependencytrack/policy/CoordinatesPolicyEvaluatorTest.java
Fixes wrong negative matches with coordinate policies. Also adds a FAQ section about common policy value issues.
Related to #5158 #5142 #4444 (I think it's possible that this PR is enough to consider these issues being fixed)
Fixes #5136
Fixes #5135
Fixes #5109
Introduces some minor breaking changes for the `NO_MATCH` operator, but should work exactly the same otherwise, at least according to the unit tests. I wonder where to note that this changes behaviour and will introduce (probably) unexpected changes in some cases.
=> Fix inverted component matching

src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java, src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java
Improve detection if version is commit sha or release tag for github purl
Fixes #4945
=> improve detection if version is commit sha or release tag for github purl

src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
The GithubMetaAnalyzer was throwing NullPointerException at line 159 when analyzing certain GitHub Actions repositories (e.g., enricomi/publish-unit-test-result-action). This occurred because the GitHub API returns null for commit dates on some GitHub Actions repositories, particularly composite actions and repos with unusual commit histories. When the code attempted to log the null timestamp using String.format(), it caused the NPE and prevented successful repository metadata analysis.
This fix adds proper null checks before setting and logging the published timestamp in both COMMIT and RELEASE version handling paths.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5274
=> Fix NullPointerException in GithubMetaAnalyzer when analyzing GitHub Actions

src/main/java/org/dependencytrack/model/VulnerableSoftware.java, src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java, src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java, src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java, src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java, src/main/java/org/dependencytrack/upgrade/UpgradeItems.java, src/main/java/org/dependencytrack/upgrade/v4135/v4135Updater.java, src/test/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManagerTest.java, src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
This is an attempt to address issue #4663, to make CPE matching case-insensitive.
Fixes #4663
Since this touches areas I'm not familiar with, and since the issue is marked with size M, I'm pretty sure I missed quite a lot of things.
=> make CPE matching case-insensitive

src/main/docker/Dockerfile, src/main/docker/Dockerfile.alpine
Updates the JDK and JRE used to build the container images to Java 25, and enables the compact object headers feature (https://openjdk.org/jeps/519) for reduced CPU and memory overhead.
We will continue to build and test the application itself against Java 21 for the time being, and it will continue to be executable on Java 21 as well. This change purely affects the default image we distribute.
N/A
N/A
- ~This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrad …
=> Bump container images to Java 25

src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
Fixes NullPointerException in GithubMetaAnalyzer when analyzing GitHub Actions.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5274
Backports https://github.com/DependencyTrack/dependency-track/pull/5275
N/A
=> Backport: Fix NullPointerException in GithubMetaAnalyzer when analyzing GitHub Actions
