DependencyTrack/dependency-track

src/main/java/org/owasp/dependencytrack/controller/DownloadController.java

Reverts stevespringett/dependency-track#24

Revert "Enable HEAD request and add Last-Modified header for nist cache"

---

pom.xml
src/main/java/org/owasp/dependencytrack/app/DependencyTrackApp.java
src/main/java/org/owasp/dependencytrack/config/ApplicationConfiguration.java
src/main/java/org/owasp/dependencytrack/config/EventConfiguration.java
src/main/java/org/owasp/dependencytrack/dao/LibraryVersionDao.java
src/main/java/org/owasp/dependencytrack/dao/LibraryVersionDaoImpl.java
src/main/java/org/owasp/dependencytrack/listener/DefaultObjectGenerator.java
src/main/java/org/owasp/dependencytrack/tasks/AllTasks.java
src/main/java/org/owasp/dependencytrack/tasks/NistDataMirrorUpdateRequestedEvent.java
src/main/java/org/owasp/dependencytrack/tasks/NistDataMirrorUpdater.java
src/main/java/org/owasp/dependencytrack/tasks/ScheduledTasks.java
src/main/java/org/owasp/dependencytrack/tasks/VulnerabilityScanRequestedEvent.java
src/main/java/org/owasp/dependencytrack/tasks/VulnerabilityScanTask.java
src/main/resources/application.properties
src/test/java/org/owasp/dependencytrack/listener/DefaultObjectGeneratorTest.java
src/test/java/org/owasp/dependencytrack/tasks/ApplicationEventPublisherTest.java
src/test/java/org/owasp/dependencytrack/tasks/NistDataMirrorUpdaterTest.java

Noticed a long delay when adding libraries...
Made the request for a dependency analysis asynch to eliminate this delay.

Event scheduling

---

src/main/java/org/owasp/dependencytrack/Config.java
src/main/java/org/owasp/dependencytrack/tasks/NistDataMirrorUpdater.java
src/main/resources/application.properties

Add possibility to use HTTP proxy

---

src/main/resources/application.properties

fit the https://github.com/stevespringett/Alpine/pull/9

add optional to change the attribute that all queries use

---

src/main/resources/application.properties

Cofig the LDAP security authentication level used.

Config the LDAP security authentication level to use

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dependencytrack/dependency-track/607)

add docs for helm-chart

---

.gitignore
docs/.gitignore
docs/_docs/FAQ.md
docs/_docs/best-practices.md
docs/_docs/terminology.md

**What's the issue?**
DT users ask repetitive questions that are being answered over and over.
**What does the PR present?**
A new FAQ section in the documentation of the project.

FAQ documentation

---

src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java

add status code and destination in logs

---

docs/_docs/FAQ.md

As discussed on Slack, include this item.

Update FAQ to address temp-file issue

---

docs/_docs/integrations/notifications.md
src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java

Allow comma separated list of email addresses as destination

---

docs/_docs/getting-started/configuration.md
docs/_docs/getting-started/deploy-docker.md
src/main/docker/docker-compose.yml
src/main/java/org/dependencytrack/common/ManagedHttpClientFactory.java
src/main/resources/application.properties
src/test/java/org/dependencytrack/common/ManagedHttpClientFactoryTest.java

Adding No Proxy support which would be very useful in corporate environments. Closes https://github.com/DependencyTrack/dependency-track/issues/655. This requires no proxy field in the config file, hence it can be merged after https://github.com/stevespringett/Alpine/pull/105.

Add no proxy

---

docs/_docs/getting-started/database-support.md
docs/_docs/getting-started/deploy-docker.md
src/main/docker/Dockerfile
src/main/docker/docker-compose.yml

Updated postgresql JDBC driver from 42.2.5 to 42.2.11

Updated postgresql JDBC driver

---

src/main/docker/Dockerfile

Update the postgres jdbc version to 4.2.18

Update the postgres jdbc version to 4.2.18

---

docs/_docs/integrations/community-integrations.md

https://github.com/DependencyTrack/dependency-track/discussions/1063#discussioncomment-827656

Added Github action to community integrations

---

docs/_posts/2021-xx-xx-v4.x.x.md
src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java

Fix pagination in OssIndexAnalysisTask

---

docs/_docs/getting-started/openidconnect-configuration.md
docs/_posts/2021-xx-xx-v4.4.0.md

Update OIDC docs and changelog for https://github.com/DependencyTrack/frontend/pull/113

---

src/main/java/org/dependencytrack/resources/v1/TeamResource.java
src/main/java/org/dependencytrack/resources/v1/vo/TeamSelfResponse.java
src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java

returns subset of Team data
- uuid
- name
- permissions
fixes #861

Implement API endpoint team/self

---

src/main/java/org/dependencytrack/upgrade/v440/v440Updater.java

Using Alpine's query manager doesn't work as expected, so reverting to raw SQL statements instead.

Fix v440Updater

---

pom.xml
src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
src/main/java/org/dependencytrack/event/VexUploadEvent.java
src/main/java/org/dependencytrack/model/Vex.java
src/main/java/org/dependencytrack/notification/NotificationConstants.java
src/main/java/org/dependencytrack/notification/NotificationGroup.java
src/main/java/org/dependencytrack/notification/vo/VexConsumedOrProcessed.java
src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/VexQueryManager.java
src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/main/java/org/dependencytrack/resources/v1/VexResource.java
src/main/java/org/dependencytrack/resources/v1/vo/VexSubmitRequest.java
src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java
src/main/java/org/dependencytrack/util/AnalysisCommentUtil.java
src/main/resources/META-INF/persistence.xml

#1387 
Signed-off-by: Steve Springett <steve@springett.us>

Implemented VEX consumption and processing

---

docs/_config.yml
docs/_docs/usage/executive-order-14028.md
pom.xml

Doc update.

---

docs/_docs/analysis-types/known-vulnerabilities.md
docs/_docs/best-practices.md
docs/_docs/datasources/github-advisories.md
docs/_docs/datasources/internal-components.md
src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java

Also remove any remaining mentions of NPM audit.
Companion PR to https://github.com/DependencyTrack/frontend/pull/148

Update GHSA documentation

---

.github/release-workflow.adoc
.github/workflows/_meta-build.yaml
.github/workflows/ci-build.yaml
.github/workflows/ci-publish.yaml
.github/workflows/ci-release.yaml

This PR aims to fix and introduce the `latest` tag logic from my prior CI PRs, sorry for any inconvenience that this error may have caused.
* fixes #1644 on default branch (4.5.x to follow ASAP)

fix: latest tag logic in meta workflow

---

pom.xml

Bump frontend to 4.5.1

---

docs/_docs/getting-started/configuration.md
docs/_posts/2022-05-18-v4.5.0.md

As identified in https://github.com/DependencyTrack/frontend/issues/159

Document breaking change in `config.json` location

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java

Consider vuln source INTERNAL when applying VEX

---

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
src/test/java/org/dependencytrack/task/BomUploadProcessingTaskTest.java
src/test/resources/bom-1.xml

store author field from BOM in database

---

src/main/java/org/dependencytrack/notification/NotificationRouter.java
src/test/java/org/dependencytrack/notification/NotificationRouterTest.java

Add tests for level matching on notification rules

---

src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
src/main/java/org/dependencytrack/resources/v1/vo/AffectedComponent.java
src/test/java/org/dependencytrack/resources/v1/vo/AffectedComponentTest.java

Fix `AffectedComponent` mapping and improve load times of vulnerability details

---

src/main/java/org/dependencytrack/model/PolicyCondition.java
src/main/java/org/dependencytrack/parser/common/resolver/CweResolver.java
src/main/java/org/dependencytrack/policy/CwePolicyEvaluator.java
src/main/java/org/dependencytrack/policy/PolicyEngine.java
src/test/java/org/dependencytrack/policy/CwePolicyEvaluatorTest.java

Signed-off-by: Sahiba Mittal <sahibamittal98@gmail.com>
Issue: https://github.com/DependencyTrack/dependency-track/issues/1768
Front-end: https://github.com/DependencyTrack/frontend/pull/184
**New feature**: Policy conditions to include CWE(s).

Issue-1768-policy-condition-cwe

---

src/main/java/org/dependencytrack/tasks/scanners/VulnDbAnalysisTask.java

Issue description in DependencyTrack/dependency-track#1780

Fix persistence issue in VulnDbAnalysisTask.java scanner.

---

src/main/java/org/dependencytrack/resources/v1/VexResource.java

Signed-off-by: GUERROUDJ David <dgueroudj@gmail.com>

Fixing bug NPE/PUT_VEX_API

---

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/test/java/org/dependencytrack/persistence/PolicyQueryManagerTest.java

Fix exception when deleting projects that are associated with policies

---

.run/DataNucleus Enhance.run.xml
DEVELOPING.md

Add dev documentation for DataNucleus bytecode enhancement

---

src/main/java/org/dependencytrack/parser/osv/model/Ecosystem.java
src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java

New additions of missing ecosystems in OSV
For reference, you can get list of all by running `gsutil ls -lah 'gs://osv-vulnerabilities/'`

OSV - update ecosystems

---

docs/_docs/integrations/community-integrations.md

We at TRIMM created this plugin to fulfill our needs to see a summary in our Backstage environment.

docs: Added TRIMMs Backstage plugin to community-integrations

---

src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
src/main/java/org/dependencytrack/resources/v1/OsvEcosytemResource.java
src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
src/test/java/org/dependencytrack/resources/v1/OsvEcosystemResourceTest.java
src/test/java/org/dependencytrack/task/OsvDownloadTaskTest.java

Signed-off-by: Sahiba Mittal <sahibamittal98@gmail.com>
Issue: https://github.com/DependencyTrack/dependency-track/issues/1964

Issue 1964 : OSV feature - add base url as input 

---

src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
src/main/java/org/dependencytrack/upgrade/v460/v460Updater.java

Fix PURL mapping of GHSA vulnerabilities for PHP

---

src/main/docker/Dockerfile

Update container base images

---

docs/_posts/2022-xx-xx-v4.6.0.md
src/main/java/org/dependencytrack/model/Finding.java
src/test/java/org/dependencytrack/model/FindingTest.java

Fix NumberFormatException when assembling CWE list for findings

---

RELEASING.md

Add pre-release and post-release checklists

---

src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java

Fix wrong alias ID being used for OSV vulnerabilities

---

docs/_posts/2022-10-11-v4.6.0.md

Update changelog for 4.6.0 release

---

pom.xml

Bump frontend to 4.6.0

---

docs/_posts/2022-10-13-v4.6.1.md

Update hashes for API server 4.6.1 release artifacts

---

src/main/java/org/dependencytrack/tasks/NistMirrorTask.java

To support CIFS:
Updated these things in class NistMirrorTask:
(1) Replaced Files.Move with FIles.copy and Files.delete to avoid the exception
(2) Avoided "LastModified" attribute instead a timestamp file is created to save this modification time and reuse the time from this file in the rest of the workflow

ProposedSolution to Issue #2048

---

pom.xml

Fixes CVE-2022-3171
Closes #2051

Remove dependency on protobuf-java

---

src/test/java/org/dependencytrack/tasks/scanners/SnykMockServerTest.java
src/test/resources/unit/snyk.jsons/https---localhost-1080-api-v1-vulnerability-source-SNYK-vuln-snyk_vuln.json

Signed-off-by: Apurva <apurva.jain@gatech.edu>

Snyk Mock Server Test

---

src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java

Feature: Fetching maven latest release version preferably from release tag instead of latest

---

docs/_docs/getting-started/configuration.md
docs/_docs/getting-started/deploy-docker.md
pom.xml
src/main/java/org/dependencytrack/common/ConfigKey.java
src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
src/main/resources/application.properties

Component list is checked against analysis cache before pagination, page size is now configurable (default 128) and exponential backoff retry is implemented (#2023).

Feature: Improving OSS Index Analyzer batching and resilience mechanism

---

src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java

Signed-off-by: Sahiba Mittal <sahibamittal98@gmail.com>

Quick enhancement : add cacheable scan in Snyk analysis

---

docs/_docs/integrations/community-integrations.md

Add the dependency-track-exporter to the list of community integrations.
The exporter isn't in the list :smile:

Add dependency-track-exporter to community-integrations.md

---

docs/_docs/analysis-types/known-vulnerabilities.md
docs/_posts/2022-11-18-v4.6.3.md
src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
src/main/java/org/dependencytrack/upgrade/v463/v463Updater.java

Reset scanner cache validity period to 12h

---

docs/_posts/2022-11-18-v4.6.3.md

Updates build artifact hashes for 4.6.3.
N/A
N/A

Update build artifact hashes for 4.6.3

---

docs/_docs/integrations/notifications.md
docs/index.md
docs/odt-odc-comparison.html
src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
src/main/java/org/dependencytrack/notification/publisher/DefaultNotificationPublishers.java
src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
src/main/java/org/dependencytrack/notification/publisher/Publisher.java
src/main/resources/templates/notification/publisher/jira.peb
src/test/java/org/dependencytrack/notification/publisher/DefaultNotificationPublishersTest.java
src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/NotificationTestConfigProvider.java
src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java

Add a Jira Publisher to publish Dependency Track alerts to Jira tickets

---

src/main/resources/templates/notification/publisher/email.peb

Signed-off-by: ch8matt <g.matthieu49@gmail.com>

fix project URL in mail

---

docs/_docs/getting-started/openidconnect-configuration.md

A small change to the doc - specifying how to configure Google OIDC

feat: added google oidc

---

src/main/resources/templates/notification/publisher/email.peb

Update to #2220 
Adds the commenter of a `PROJECT_AUDIT_CHANGE` to an email notification, to easily see who made the decision change.
#2139

Add commenter to `PROJECT_AUDIT_CHANGE` emails

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Addresses https://github.com/DependencyTrack/dependency-track/issues/1717
Signed-off-by: ege-dw <enora.germond@deveryware.com>

Make project search by tags case insensitive

---

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java

When uploading a new BOM to a project with duplicated components, the `BomUploadProcessingTask` might throw exceptions while trying to recursively delete the old components, resulting in a failed upload, where the components from the new BOM are added, but not all old components are deleted.
By catching the exceptions which are thrown while recursively deleting old components, the `BomUploadProcessingTask`  can finish successfully and all of the old components are correctly deleted.
Workaround for #2131
~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
~- [ ] This PR introduces changes to the database model, and I have added corresponding …

Workaround for deleting duplicate components when uploading a new BOM

---

pom.xml

Bump the Alpine version to 2.2.0.
N/A
N/A

Bump Alpine to 2.2.0

---

pom.xml
src/main/java/org/dependencytrack/model/Finding.java
src/main/java/org/dependencytrack/model/Vulnerability.java
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
src/main/java/org/dependencytrack/resources/v1/CalculatorResource.java
src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
src/main/java/org/dependencytrack/util/NotificationUtil.java
src/main/java/org/dependencytrack/util/VulnerabilityUtil.java
src/test/java/org/dependencytrack/model/FindingTest.java
src/test/java/org/dependencytrack/resources/v1/CalculatorResourceTest.java
src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
src/test/java/org/dependencytrack/util/VulnerabilityUtilTest.java

Enhancing severity calculator API and data model to support OWASP RR.
#1493 
- Frontend PR : https://github.com/DependencyTrack/frontend/pull/362
- OWASP RR Calcultator PR : https://github.com/stevespringett/owasp-risk-rating-calculator/pull/54
~~- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~~
~~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~~

Feature : OWASP RR support

---

docs/_docs/getting-started/recurring-tasks.md

Adding forgotten IndexTask
N/A
N/A
~~- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~~
~~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~~
~~- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~~

doc: Adding forgotten IndexTask

---

src/main/docker/Dockerfile

Because Dependabot can't deal with Temurin's versioning scheme, manually bump the base image to its latest available `17.x` version.
N/A
N/A

Bump temurin base image to 17.0.5_8

---

pom.xml
src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java

This PR adds Vulnerability Disclosure Report (VDR) as additional CycloneDX export variant.
VDRs are a superset of the existing "Inventory with Vulnerabilities" variant.
The only addition being that VDRs also include analysis data, which was previously only included in VEX exports.
Closes #1800
Frontend PR: https://github.com/DependencyTrack/frontend/pull/363

Add VDR as CycloneDX export variant

---

src/main/java/org/dependencytrack/model/Component.java
src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java

Improvement to #2189.
Focusing on a component in the dependency graph can result in huge amounts of data being sent from the backend to pre-expand a graph, because in big nested graphs the same components can appear multiple times and the current approach of focusing on components includes every duplicate component in its response.
With this PR, the needed components for pre-expanding a graph are being de-duplicated before being sent as a response to the frontend, resulting in a huge reduction of sent data (e.g. ~50MB => ~60KB).
#1997
[Frontend PR](https://github.com/DependencyTrack/frontend/pull/365)
~-[ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~
~- [ ] This PR introduces changes to the database model, and I have added corresponding [update …

Improve focusing on components in dependency graph

---

pom.xml

Bump the frontend version for the bundled distribution to 4.7.0.
N/A
N/A

Bump frontend to 4.7.0

---

.github/ISSUE_TEMPLATE/defect-report.yml
docs/_posts/2022-12-16-v4.7.0.md

Bump versions in "Defect Report" issue template and update hashes of release artifacts for 4.7.0.
N/A
N/A

Update release artifact hashes in 4.7.0 changelog

---

.github/ISSUE_TEMPLATE/defect-report.yml
docs/_posts/2022-12-16-v4.7.0.md

Port the changes from #2302 to `master`
N/A
N/A

Port #2302 to `master`

---

pom.xml

Bump the project version to `4.8.0-SNAPSHOT`.
N/A
N/A

Bump version to 4.8.0-SNAPSHOT

---

src/main/java/org/dependencytrack/resources/v1/BomResource.java

Added missing support for BOMs with byte order markers on HTTP PUT

---

.gitignore

git: ignore .vscode folder

---

src/main/java/org/dependencytrack/model/Project.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

This PR adds support for updating a project's parent via `PATCH`.
Closes #2401 
N/A

Support updating project parent via PATCH

---

src/main/java/org/dependencytrack/tasks/NistMirrorTask.java

Instead of initializing the end year variable when the NistMirrorTask class is loaded (at application startup), initialize it when the class is instantiated (whenever a NistMirrorEvent is emitted).
Fixes #2349
N/A

Fix upper bound year for NistMirrorTask

---

.lift.toml

This PR adds a [Lift config file](https://help.sonatype.com/lift/configuring-lift/build-and-.toml-details) and disables some noisy rules I observed coming up in PRs.
N/A
N/A

Add Lift config and disable some noisy rules

---

src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java

Signed-off-by: mehab <meha.bhargava2@gmail.com>
This change is updating the column name for getting vulnerability aliases from vulndb 
**Current behaviour**
The current query for getting vulnerability aliases for vulndb as source  in the getVulnerabilityAliases method is `query = pm.newQuery(VulnerabilityAlias.class, "vulnDb== :vulnDb");` which has column name invalid. <br/>
**Expected behaviour**
The correct id column for vulndb id is **vulnDbId** and thus the query should be `query = pm.newQuery(VulnerabilityAlias.class, "vulnDbId == :vulnDb");` so that there is no error.
- [ x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [x ] This PR fixes a defect, and I have …

Fix vulndb column name in getVulnerabilityAliases method

---

docs/_posts/2023-01-31-v4.7.1.md

This PR adds the checksums for 4.7.1 release artifacts.
N/A
N/A

Update 4.7.1 release artifact checksums

---

.github/ISSUE_TEMPLATE/defect-report.yml
docs/_posts/2023-01-31-v4.7.1.md
pom.xml

This PR ports the changes made for 4.7.1 back to `master`.
N/A
N/A

Port changes from 4.7.1 to `master`

---

src/main/java/org/dependencytrack/model/Project.java

The serialization of the `parentUuid` field in `Project` is not necessary for displaying the hierarchical view in the frontend and therefore this PR removes the field.
Closes #2439
[Frontend PR](https://github.com/DependencyTrack/frontend/pull/410)
~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
~- [ ] This PR introduces new or alters existing behavior, and I have updated the …

Remove unnecessary field `parentUuid` in `Project`

---

src/main/java/org/dependencytrack/search/IndexManager.java
src/main/java/org/dependencytrack/search/IndexSubsystemInitializer.java

This PR fixes `AlreadyClosedException`s that occurred when search indexes were committed after the recurring index consistency check executed (every 72h per default). A more detailed analysis of this problem can be found in https://github.com/DependencyTrack/dependency-track/issues/2379#issuecomment-1416800378
Fixes #2379
N/A

Fix `AlreadyClosedException` when committing search indexes

---

.github/PULL_REQUEST_TEMPLATE.md

FIx link to contributing guidelines
FIx link to contributing guidelines
FIx link to contributing guidelines
FIx link to contributing guidelines

FIx link to contributing guidelines in PR template

---

src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java

Fixes an NPE introduced in #2473, which prevented OSV ecosystems from being displayed in DT instances that didn't have OSV enabled before.
N/A
When no ecosystems have been enabled yet (i.e. when DT was launched for the first time), the `google.osv.enabled` config property is not set (thus `null`).

Fix NPE in enabled OSV ecosystems computation

---

DEVELOPING.md
scripts/data-nist-generate-dummy.sh

Add developer docs and helper script for skipping NVD mirroring for local testing purposes.
This was born out of discussions in #2524 and https://owasp.slack.com/archives/C6R3R32H4/p1677659835644939.
Relates to #2524 
N/A

Add developer docs for skipping NVD mirroring

---

src/main/java/org/dependencytrack/policy/CpePolicyEvaluator.java
src/main/java/org/dependencytrack/policy/PackageURLPolicyEvaluator.java
src/main/java/org/dependencytrack/policy/SwidTagIdPolicyEvaluator.java
src/test/java/org/dependencytrack/policy/CpePolicyEvaluatorTest.java
src/test/java/org/dependencytrack/policy/PackageURLPolicyEvaluatorTest.java
src/test/java/org/dependencytrack/policy/SwidTagIdPolicyEvaluatorTest.java

Empty PURL and/or CPE' now are also checked in the PackageURLPolicyEvaluator/CpeURLPolicyEvaluator. 
Fixes: #2587
Also fixed SwidTagIdPolicyEvaluator

Support matching of nonexistent CPE, PURL, and SWID tag IDs in policy conditions

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

This PR fixes a defect in portfolio access control logic that could cause internal server errors when fetching the list of all projects a user or team has access to.
Fixes #2583
Refer to #2583 for details.

Fix invalid query filter assembly

---

.gitignore
README.md
docs/_docs/datasources/repositories.md
src/main/java/org/dependencytrack/model/RepositoryType.java
src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
src/main/java/org/dependencytrack/tasks/repositories/CpanMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java
src/test/java/org/dependencytrack/model/RepositoryTypeTest.java
src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
src/test/java/org/dependencytrack/tasks/repositories/CpanMetaAnalyzerTest.java

Support for CPAN repository
Closes #639 
Not quite sure if this is wat's  requested. Still looking for an SBOM example with Perl components...
Used by: https://github.com/DependencyTrack/frontend/pull/441

Support for CPAN repository

---

src/main/java/org/dependencytrack/upgrade/v480/v480Updater.java

Fix: Move jira configuration (upgrade script)
PR #2404 was missing upgrade script to address #2313.

Fix: Move jira configuration

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java

Fix a defect where the dependency graph of projects would be deleted when exporting them as CycloneDX.
Fixes #2494
Fixes #2546
This PR just fixes a defect. The reason (in part) for the defect however is that we currently do not include the dependency graph in any of the CDX export variants. Implementation of this is tracked separately in #2616. 
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-trac …

Prevent dependency graph deletion during CycloneDX export

---

pom.xml

Bumps Alpine to v2.2.1.
N/A
N/A

Bump Alpine to 2.2.1

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java

This PR re-implements proper support for including dependency graphs in CycloneDX exports.
Closes #2616
N/A

Add support for dependency graph in CycloneDX exports

---

src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java

Feat: Support Jira authentication with personal tokens
#2641

Feat: Support Jira authentication with personal tokens

---

docs/_posts/2023-04-18-v4.8.0.md

This PR adds the changelog for version 4.8.0.
N/A
N/A

Add changelog for v4.8.0

---

pom.xml

This PR bumps the frontend version for the bundled distribution to v4.8.0.
N/A
N/A

Bump frontend to v4.8.0

---

docs/_config.yml

Bumps version in docs to v4.8.
N/A
N/A

Bump version in docs

---

.github/ISSUE_TEMPLATE/defect-report.yml
docs/_posts/2023-04-18-v4.8.0.md

Update release artifact checksums and bumps version in defect report template.
N/A
N/A

v4.8.0 post release

---

.github/ISSUE_TEMPLATE/defect-report.yml
docs/_posts/2023-04-18-v4.8.0.md
pom.xml

Update release artifact checksums and bumps version in defect report template.
N/A
N/A

Port v4.8.0 post release

---

docs/_posts/2023-04-18-v4.8.0.md

Changelog: Nitpicking to add the full scope of one of my PRs :-)

Changelog Update 2023-04-18-v4.8.0.md

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Allow externalReference to be updated using PATCH project/{id}
fixes https://github.com/DependencyTrack/dependency-track/issues/2695

Issue #2695: Add externalReferences to PATCH project

---

pom.xml

This PR bumps Alpine to version 2.2.2.
Fixes #2696
N/A

Bump Alpine to 2.2.2

---

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java

Regression from https://github.com/DependencyTrack/dependency-track/pull/2658
Fixes #2766 
N/A

Fix missing project filter for `/api/v1/violation/project`

---

.github/workflows/_meta-build.yaml
.github/workflows/ci-publish.yaml
.github/workflows/ci-release.yaml

This PR fixes warnings in our GitHub Actions workflows due to deprecation of the `set-output` command.
N/A
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix GHA `set-output` deprecation warnings

---

docs/_docs/getting-started/configuration.md
pom.xml
src/main/resources/application.properties

This PR bumps Alpine to `2.2.3-SNAPSHOT`.
Includes https://github.com/stevespringett/Alpine/pull/494 among other changes so far.
Also added documentation for `alpine.datanucleus.cache.level2.type`.
Relates to #903, which mentions the default DataNucleus L2 cache as problematic for HA.
With this change, it is possible to disable the L2 cache entirely.
N/A …

Bump Alpine to `2.2.3-SNAPSHOT`

---

src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java

It's a follow up PR with #2872 , there another case may cause memory leak.
In `VexUploadProcessingTask`, there is a `QueryManager` never get call it's `close` method, it could also leads memory leak.
https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java#L62

Fix memory leak issue in vex upload processing task

---

DEVELOPING.md
dev/docker-compose.monitoring.yml
dev/monitoring/grafana/dashboards/apiserver.json
dev/monitoring/grafana/provisioning/dashboards/dashboards.yml
dev/monitoring/grafana/provisioning/datasources/datasources.yml
dev/monitoring/prometheus.yml
dev/scripts/copy-grafana-dashboard.sh

This PR adds auto-privisioning of Grafana to the Docker Compose development setup.
That way, the Prometheus datasource and Grafana dashboard do not have to be configured manually anymore.
N/A
N/A

Add auto-provisioning of Grafana to dev Compose setup

---

docs/_docs/datasources/snyk.md

This PR updates the Snyk datasource documentation to mention the required subscription plan.
Because Snyk has many products, and multiple API keys / tokens, it can be confusing as to what token will work for which product.
Relates to #2898
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/ …

Add note about required subscription plan for Snyk

---

.github/dependabot.yml
src/main/docker/Dockerfile

Updating debian image to latest stable slim; updating docker scan to …
addresses issue #2903 
changed to latest debian release
- [] This PR fixes a defect, and I have provided tests to verify that the fix is effective

Updating to latest debian image and docker scan to weekly

---

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java

Fix a defect that could cause an `Uncaught internal server error` being returned when fetching components by hash via `/v1/component/hash/{hash}`, while the *Portfolio Access Control* feature is enabled.
Fixes #2952 
N/A

Fix `Uncaught internal server error` when fetching components by hash if *Portfolio Access Control* is enabled

---

pom.xml
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java

Update `cyclonedx-core-java` to `7.4.0-SNAPSHOT`, which includes support for CycloneDX v1.5.
This is to allow users to test with CDX v1.5 BOMs using our `snapshot` images.
Addresses, but not yet fixes, #2850.
N/A

Bump `cyclonedx-core-java` to `7.4.0-SNAPSHOT`

---

src/main/java/org/dependencytrack/model/Component.java
src/main/java/org/dependencytrack/model/Project.java

A (more or less intentional) regression in Jackson 2.15 causes `@JsonIgnore` annotations on `transient` fields to be ignored. As a workaround, the annotation can be added to getters and setters instead (https://github.com/FasterXML/jackson-databind/issues/3909#issuecomment-1533857834).
This regression caused multiple failures in our test suite (e.g. https://github.com/DependencyTrack/dependency-track/actions/runs/6259255825/job/16994879257).
N/A
N/A
- ~This PR introduces new or alters …

Fix `@JsonIgnore` having no effect on `transient` fields

---

pom.xml

Bumps version of the Alpine framework from `2.2.3-SNAPSHOT` to `2.2.3`.
N/A
N/A

Bump Alpine to `2.2.3`

---

docs/_docs/getting-started/configuration.md
src/main/resources/application.properties

Adds documentation for the `alpine.api.key.prefix` configuration option, and sets the default for it to `odt_` (**O**WASP **D**ependency-**T**rack). Having a deterministic prefix makes scanning for leaked secrets more robust.
Closes https://github.com/DependencyTrack/dependency-track/issues/2543
Also fixes https://github.com/DependencyTrack/dependency-track/issues/3043 …

Add documentation for API key prefix, and set default to `odt_`

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
src/test/java/org/dependencytrack/ResourceTest.java
src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java

Fixes a regression introduced in #2657, causing VEX exports to contain dependency graph information.
VEX documents are scoped to projects, and do not contain individual components. It makes no sense to include the dependency graph.
N/A
N/A

Fix VEX export erroneously containing dependency graph

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes a `NullPointerException` when creating projects without version.
Regression introduced in #2966, which added a common logic to detect whether a project already exists.
N/A
N/A

Fix NPE in `doesProjectExist` when project version is `null`

---

src/main/docker/Dockerfile

Bump the temurin base image to `17.0.8.1_1`, as Dependabot is still unable to detect new versions for it automatically.
N/A
N/A

Bump temurin base image to `17.0.8.1_1`

---

src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java

The test is breaking because `NUnit` released version `4.0.0-beta.1`, but there's no published timestamp available for this version, causing the test to fail.
N/A
N/A

Fix `NugetMetaAnalyzerTest`

---

src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
src/main/java/org/dependencytrack/resources/v1/vo/DependencyGraphResponse.java
src/test/java/org/dependencytrack/resources/v1/DependencyGraphResourceTest.java

The `repositoryMetaComponentSearch` variable is reused when iterating over components, but is only populated when the respective component has a PURL.
If the first component has a PURL, and the second doesn't, the same `repositoryMetaComponentSearch` would be used for both.
N/A
N/A

Fix wrong `latestVersion` being assigned to dependency graph entries without PURL

---

pom.xml

Bumps all Cloud SQL connectors to the latest version `1.14.1`.
Closes #3087
N/A

Bump Cloud SQL connectors to `1.14.1`

---

docs/_config.yml
docs/_posts/2023-10-16-v4.9.0.md

Adds release notes for the v4.9.0 release.
N/A
N/A

Add changelog for 4.9.0 release

---

.github/workflows/_meta-build.yaml
.github/workflows/ci-publish.yaml
.github/workflows/ci-release.yaml
.github/workflows/ci-test.yaml
.github/workflows/dependency-review.yaml
.github/workflows/lock.yaml

Pins the digests of all GitHub Actions in our workflows.
To satisfy the scorecards Pinned-Dependencies check (https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies).
N/A
N/A

Pin digests of GitHub Actions

---

.github/workflows/_meta-build.yaml
.github/workflows/ci-build.yaml
.github/workflows/ci-publish.yaml
.github/workflows/ci-release.yaml
.github/workflows/ci-test.yaml
.github/workflows/dependency-review.yaml
.github/workflows/lock.yaml

Applies strict token permissions in GitHub Actions workflows.
To satisfy the scorecards Token-Permissions check (https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions).
N/A
N/A

Use strict token permissions in GitHub Actions workflows

---

pom.xml

Bumps `cyclonedx-core-java` to `8.0.2`, resolving multiple issues related to BOM parsing:
* https://github.com/CycloneDX/cyclonedx-core-java/issues/334
* https://github.com/CycloneDX/cyclonedx-core-java/issues/336
* https://github.com/CycloneDX/cyclonedx-core-java/issues/338
Fixes #3107
N/A

Backport: Bump `cyclonedx-core-java` to `8.0.2`

---

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java

JDOQL conditions like `field != null && field == :field` can result in the SQL `FIELD IS NOT NULL AND FIELD IS NULL` being generated when the `:field` parameter is `null`. Such SQL condition cause the database's query planner to be unable to use any indexes on affected columns.
This is now prevented by only including fields in the query if the parameter is not `null`.
Additionally, fixed another occurrence of #2540.
Thanks to Mikael Carneholm for reporting this on Slack: https://owasp.slack.com/archives/C6R3R32H4/p1698071932430299
N/A
N/A
- ~This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tre …

Backport: Fix impossible SQL query conditions causing DB indexes to be bypassed

---

pom.xml

Forces downgrade of `logstash-logback-encoder` to `7.3`.
Using a workaround until https://github.com/stevespringett/Alpine/pull/517 is ready to be used.
> **Note**  
> Needs to be backported to the `4.9.x` branch.
Fixes #3127
N/A …

Force downgrade of `logstash-logback-encoder` to `7.3`

---

pom.xml

Forces downgrade of `logstash-logback-encoder` to `7.3`.
Using a workaround until https://github.com/stevespringett/Alpine/pull/517 is ready to be used.
Fixes #3127
N/A

Backport: Force downgrade of `logstash-logback-encoder` to `7.3`

---

pom.xml

Fixes failures when parsing XML BOMs that contain empty `component>hashes` nodes: https://github.com/CycloneDX/cyclonedx-core-java/issues/343
> **Note**  
> Needs to be backported to the `4.9.x` branch.
N/A
N/A

Bump `cyclonedx-core-java` to `8.0.3`

---

pom.xml

Fixes failures when parsing XML BOMs that contain empty `component>hashes` nodes: https://github.com/CycloneDX/cyclonedx-core-java/issues/343
N/A
N/A

Backport: Bump `cyclonedx-core-java` to `8.0.3`

---

docs/_docs/datasources/github-advisories.md

This is supported, ref: https://github.blog/changelog/2023-04-27-graphql-improvements-for-fine-grained-pats-and-github-apps/
Fixes outdated docs

fixes(docs): outdated doc

---

docs/_posts/2023-10-30-v4.9.1.md

Adds the changelog for the v4.9.1 bugfix release.
N/A
N/A

Add changelog for v4.9.1

---

docs/_posts/2023-10-30-v4.9.1.md

Ports the changelog for version 4.9.1 to `master`.
N/A
N/A

Port changelog for v4.9.1

---

docs/_docs/FAQ.md

Here is some documentation, guidance, and recommendations for using DependencyTrack in a Kubernetes environment with Nginx.
Closes https://github.com/DependencyTrack/dependency-track/issues/2855
-  ~This PR fixes a defect, and I have provided tests to verify that the fix is effective~
- ~This PR introduces changes to the database model, and I have added corresponding [update logic]~(https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation]~(https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

guidance about 413 content to large

---

src/main/java/org/dependencytrack/tasks/NistMirrorTask.java

The NVD has been increasingly flaky recently, causing DT's mirroring operation to fail occasionally. Flakiness is a transient issue, and download attempts can simply be retried after a short backoff time.
This adds a retry behavior such that various well-known error conditions are handled gracefully. Retry backoff starts out with 1s, and builds up to 32s over the course of 6 total attempts, after which we give up.
Encounters of retryable exceptions are logged as `WARN`.
N/A
N/A
- ~This PR …

Add retry with exponential backoff for NVD feed downloads

---

src/main/resources/templates/notification/publisher/slack.peb
src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java

Fixes trailing comma in default Slack publisher template.
Fixes #3170 
N/A

Fix trailing comma in default Slack publisher template

---

pom.xml

Bumps Alpine to `2.2.4-SNAPSHOT`.
N/A
N/A

Bump Alpine to `2.2.4-SNAPSHOT`

---

dev/monitoring/grafana/dashboards/apiserver.json
dev/scripts/copy-grafana-dashboard.sh
docs/files/grafana-dashboard.json

Adds a new widget to the Grafana dashboard that displays the average time taken to process events.
N/A
N/A

Add average event processing duration to Grafana dashboard

---

pom.xml
src/main/java/org/dependencytrack/util/NotificationUtil.java
src/main/resources/templates/notification/publisher/webhook.peb
src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java

Fixes a `NullPointerException` for `BOM_PROCESSING_FAILED` notifications when parsing of the BOM failed.
Also add more tests for notification publishers.
Fixes #3197
N/A

Fix NPE for `BOM_PROCESSING_FAILED` notifications when parsing of the BOM failed

---

docs/_posts/2023-xx-xx-v4.10.0.md
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/test/java/org/dependencytrack/policy/PolicyEngineTest.java

Fixes a failure to delete `PolicyViolation`s when they have an audit trail (analysis, comments etc.).
Fixes #3226 
N/A

Fix failure to delete `PolicyViolation`s when they have an audit trail

---

docs/_posts/2023-xx-xx-v4.10.0.md
src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java

Fixes teams not being assignable to alerts with custom email publishers.
Closes #3227
N/A

Fix teams not being assignable to alerts with custom email publishers

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java

Fixes erroneous warning log during VEX import.
Fixes #3221
N/A

Fix erroneous warning log during VEX import

---

pom.xml

Bumps `open-vulnerability-clients` to `5.0.3`.
N/A
N/A

Bump `open-vulnerability-clients` to `5.0.3`

---

docs/_docs/datasources/repositories.md
src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java

Fixes NPEs in GitHub repository metadata analyzer, when the repository of the analyzed component does either:
* Not have a release associated with the component's version, or
* No release at all
N/A
N/A

Fix NPEs in GitHub repository metadata analyzer

---

src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java

Following the progress without it, especially on the initial mirroring operation, is not possible otherwise. Could be confusing for users as they won't have any indication of whether the task is making progress.
Current progress is logged every 2000 items. 2000 is the maximum number of items per page returned by the NVD REST API. More frequent progress logs would flood the logs unnecessarily.
#1861 
Example output:
```
WARN [NistApiMirrorTask] No API key configured; Aggressive rate limiting to be expected
INFO [NistApiMirrorTask] CVEs were not previously mirrored via NVD API; Will mirror all CVEs
INFO [NistApiMirrorTask] Mirrored 2000/231977 CVEs (0%)
INFO [NistApiMirrorTask] Mirrored 4000/231977 CVEs (1%)
INFO [NistApiMirrorTask] Mirrored 6000/231977 CVEs (2%)
INFO [NistApiMirrorTask] …
```

Log status of NVD mirroring via REST API

---

pom.xml
src/main/java/org/dependencytrack/common/AlpineHttpProxySelector.java
src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
src/test/java/org/dependencytrack/common/AlpineHttpProxySelectorTest.java

HTTP clients were not previously configurable in the NVD REST API client. To configure a proxy, users had to specify Java system properties, which is unintuitive given DT normally uses `HTTP_PROXY` and / or `ALPINE_HTTP_PROXY` environment variables.
With this change, the usual proxy settings offered by DT take effect for NVD mirroring via REST API as well.
N/A
N/A …

Honour proxy settings when mirroring CVEs via NVD REST API

---

pom.xml

Bumps Alpine to 2.2.4.
N/A
N/A

Bump Alpine to 2.2.4

---

src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java
src/test/java/org/dependencytrack/policy/VersionDistancePolicyEvaluatorTest.java

Fixes NPE in `VersionDistancePolicyEvaluator` when project has no direct dependencies.
Fixes #3295
N/A

Fix NPE in `VersionDistancePolicyEvaluator` when project has no direct dependencies

---

docs/_posts/2023-12-08-v4.10.0.md

Without the version field there is a NullPointerException
Relates to #3299
- ~[ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~
- ~[ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
- ~[ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
- ~[ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly ~

Fix GitHub purl example in v4.10.0 changelog

---

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java

Backports #3311 to v4.10.x.
Fixes #3309 
N/A

Backport: Fix `ClassCastException` when updating an existing `ProjectMetadata#authors` field

---

src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java

fixes #3299
Improves error handling in the GitHub Repository Handler.
Fixes https://github.com/DependencyTrack/dependency-track/issues/3299
- [x ] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [x ] This PR implements an enhancement, and I have provided tests to verify that it works as intended

feat: Improve Error handling and add default version type

---

src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java

Backports #3313 to v4.10.x.
Fixes #3299
N/A

Backport: Improve Error handling and add default version type

---

docs/_posts/2023-12-19-v4.10.1.md

Adds changelog for v4.10.1.
N/A
N/A

Add changelog for v4.10.1

---

docs/_docs/terminology.md

Updated terminology.md to describe the Risk Score calculation

---

src/main/java/org/dependencytrack/parser/github/graphql/GitHubSecurityAdvisoryParser.java
src/test/java/org/dependencytrack/parser/github/GitHubSecurityAdvisoryParserTest.java
src/test/resources/unit/github.jsons/GHSA-8v27-2fg9-7h62.json

Ignore withdrawn Github advisories similarly to [how OSV Parser works](https://github.com/DependencyTrack/dependency-track/blob/026b504d27c692674eeca0bad32fcb22428b8b02/src/main/java/org/dependencytrack/parser/osv/OsvAdvisoryParser.java#L45-L48).
Fixes #1693

Ignore withdrawn Github advisories

---

docs/_docs/getting-started/openidconnect-configuration.md

Improve configuration docs for large enterprises using Azure AD.  
See https://github.com/DependencyTrack/dependency-track/issues/2150#issuecomment-1613418934

docs(azure-ad): large enterprise group configuration

---

docs/_docs/getting-started/openidconnect-configuration.md

The image link in the markdown is indented - so it doesn't display the image
Show the image in the documentation page.

Fix image link on openidconnect-configuration.md

---

docs/_docs/getting-started/configuration.md
docs/_docs/getting-started/openidconnect-configuration.md
pom.xml
src/main/resources/application.properties

Bump Alpine to `2.2.5-SNAPSHOT`, which includes:
* Ability to assign default groups to OIDC users (https://github.com/stevespringett/Alpine/pull/535)
* Tracking of `created` and `lastUsed` timestamps for API keys (https://github.com/stevespringett/Alpine/pull/537)
* Addition of `comment` field to API keys (https://github.com/stevespringett/Alpine/pull/537)
Closes #1068
Fixes #1556
Closes #3349
N/A …

Bump Alpine to `2.2.5-SNAPSHOT`

---

src/main/java/org/dependencytrack/tasks/repositories/AbstractMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/NpmMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/NpmMetaAnalyzerTest.java

Fixes `URISyntaxException`s during repository metadata analysis, when NPM PURLs contain special characters.
https://github.com/DependencyTrack/dependency-track/pull/3357#issuecomment-1928690246
N/A

Fix `URISyntaxException` when NPM PURL contains special characters

---

pom.xml

Bumps various dependencies.
Weird how we didn't get any Dependabot PRs for any of these.

Bump various dependencies

---

dev/scripts/cwe-dictionary-generate.py
src/main/java/org/dependencytrack/parser/common/resolver/CweDictionary.java
src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java

Bumps the CWE dictionary to v4.13.
N/A
N/A

Bump CWE dictionary to v4.13

---

src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
src/main/java/org/dependencytrack/model/Finding.java
src/main/java/org/dependencytrack/model/GroupedFinding.java
src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
src/test/java/org/dependencytrack/model/FindingTest.java
src/test/java/org/dependencytrack/model/GroupedFindingTest.java

Applies consistent formatting to SQL queries, and utilizes Java text blocks instead of string concatenation for multi-line queries.
N/A
Formatting inspired by https://www.sqlstyle.guide/

Apply consistent formatting to SQL queries; Use text blocks instead of string concatenation

---

pom.xml
src/main/java/org/dependencytrack/model/Vulnerability.java
src/main/java/org/dependencytrack/parser/trivy/TrivyParser.java
src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java

Improves test coverage of the new Trivy integration.
N/A
In addition to unit tests with mocked Trivy server responses, we now also have basic integration tests that spin up a Trivy container image to test against. This should help us in identifying any breaking changes in Trivy's server API. …

Improve test coverage of Trivy integration

---

docs/_docs/datasources/nvd.md

Adds a disclaimer block on top of nvd.md
Fixes #3294

Adds NVD disclaimer at the top of the documentation page for NVD.

---

.github/release.yml
.github/workflows/ci-publish.yaml
.github/workflows/ci-release.yaml

Adds [auto-generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) to GitHub releases.
Generated notes include all pull requests contained in a given release. PR authors are tagged, giving them proper credit.
> [!NOTE]
> The generated notes are *appended* to the old format, they do not replace it.
N/A
N/A
- ~This PR …

Add auto-generated changelog to GitHub releases

---

.github/workflows/ci-test.yaml

Reports test coverage for all branches to Codacy, not just `master`.
This will allow us to enforce coverage quality gates on PRs.
N/A
N/A

Report test coverage for all branches, not just `master`

---

.github/workflows/ci-test-pr-coverage.yml
.github/workflows/ci-test.yaml

Uploads test coverage for PRs via separate workflow.
Relates to #3516
The procedure is detailed here: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Upload test coverage for PRs via separate workflow

---

pom.xml
src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Bumps Alpine to version `2.2.5`.
N/A
N/A

Bump Alpine to `2.2.5`

---

docs/_posts/2024-xx-xx-v4.11.0.md

Updates the changelog for v4.11.0 with recent changes.
N/A
N/A

Update changelog for v4.11.0

---

docs/_docs/getting-started/openidconnect-configuration.md
docs/_posts/2024-xx-xx-v4.11.0.md

Clarifies OpenID Connect group mapping to teams.
This hosts a couple of details which aren't immediately obvious out of the Keycloak walkthrough (which I had skimmed since we don't use that IdP) and clarifies that groups must match identically including case.
Originally contributed by @acdha via #3269. 
Supersedes and closes #3269
- ~This PR introduces new or alters existing behavior, and I have …

Clarify OpenID Connect group mapping to teams

---

docs/_posts/2024-xx-xx-v4.11.0.md
src/main/java/org/dependencytrack/resources/v1/TeamResource.java
src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java

Adds REST endpoint for updating API key comment.
Required for https://github.com/DependencyTrack/frontend/pull/768
N/A
This is a follow-up to https://github.com/stevespringett/Alpine/pull/537, where the underlying logic was implemented.

Add endpoint for updating API key comment

---

README.md
docs/_docs/datasources/repositories.md
docs/_posts/2018-12-22-v3.4.0.md
docs/index.md
docs/odt-odc-comparison.html

Update documentation to use "PyPI" rather than "PyPi" or "Pypi"
None
I was browsing the documentation site (https://docs.dependencytrack.org) and noticed this. I didn't bother creating an issue first, but let me know if you'd like me to for tracking purposes.

Normalize capitalization of PyPI

---

README.md
docs/_docs/getting-started/configuration.md
docs/_docs/getting-started/data-directory.md
docs/_docs/getting-started/database-support.md
docs/_docs/getting-started/deploy-exewar.md
docs/_docs/getting-started/deploy-kubernetes.md
docs/_docs/getting-started/initial-startup.md
docs/_docs/getting-started/internal-ca.md
docs/_docs/getting-started/ldap-configuration.md
docs/_docs/getting-started/monitoring.md
docs/_docs/getting-started/openidconnect-configuration.md
docs/_docs/getting-started/recurring-tasks.md

Advertises official Helm chart in docs.
Relates to #3080 
N/A

Advertise official Helm chart in docs

---

docs/_posts/2024-xx-xx-v4.11.0.md

Updates the changelog with recent changes for v4.11.
N/A
N/A

Update changelog for v4.11 with recent changes

---

docs/_posts/2024-xx-xx-v4.11.0.md
src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
src/main/java/org/dependencytrack/resources/v1/CweResource.java
src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
src/main/java/org/dependencytrack/resources/v1/TagResource.java
src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
src/main/java/org/dependencytrack/resources/v1/openapi/PaginatedApi.java

The query parameters for pagination (`pageNumber`, `pageSize` / `offset`, `limit`) were previously not included in the OpenAPI specification. This made it hard to work out how pagination works, and which endpoints support it.
This PR adds documentation for the mentioned parameters to all endpoints that support them.
Relates to #3608
- ~This PR introduces new or alters existing behavior, and I have …

Include pagination parameters in OpenAPI spec

---

src/main/docker/Dockerfile

Bumps the Temurin base image to version `21.0.3_9`.
N/A
N/A

Bump Temurin base image to `21.0.3_9`

---

docs/_docs/getting-started/configuration.md
src/main/java/org/dependencytrack/common/ConfigKey.java
src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
src/main/java/org/dependencytrack/notification/NotificationSubsystemInitializer.java
src/main/resources/application.properties

Adds support for worker pool drain timeout.
This surfaces the functionality introduced in https://github.com/stevespringett/Alpine/pull/508 to Dependency-Track. It was previously only integrated into Hyades.
N/A
N/A

Add support for worker pool drain timeout

---

docs/_posts/2024-xx-xx-v4.11.0.md

Updates the v4.11 changelog with recent changes.
N/A
N/A

Update v4.11 changelog with recent changes

---

docs/_posts/2024-xx-xx-v4.11.0.md
src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java

Adds a fallback to no authentication when OSS Index API token decryption fails.
Instead of causing a full-blown service disruption when API token decryption fails, fall back to unauthenticated API usage to limit the impact.
Relates to #2366
N/A

Fall back to no authentication when OSS Index API token decryption fails

---

src/main/java/org/dependencytrack/model/ComponentProperty.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
src/test/resources/unit/bom-1.xml

Truncates `ComponentProperty` values at 1024 characters.
This is both to prevent the database's length constraint from being violated, and to avoid storing unnecessary long values. Some tools may misuse properties, and in those cases having the complete value is usually not of interest to users.
N/A
N/A

Truncate `ComponentProperty` value at 1024 characters

---

src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
src/test/java/org/dependencytrack/tasks/NistMirrorTaskTest.java
src/test/resources/unit/nvd/feed/nvdcve-1.1-2021_duplicate-cpes.json

De-duplicates CPEs in NVD feed file parsing.
Some CVE records contain duplicate CPEs. The original parsing logic did not de-duplicate those, consequently causing duplicate `VulnerableSoftware` records in the database.
De-duplication was already handled in `NistApiMirrorTask`, but not `NistMirrorTask`.
Relates to #3663
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs …

De-duplicate CPEs in NVD feed file parsing

---

.github/workflows/_meta-build.yaml
.github/workflows/ci-build.yaml
.github/workflows/ci-publish.yaml
.github/workflows/ci-test.yaml
DEVELOPING.md

Runs builds and CI on `feature-*` branches.
This allows contributors to collaborate on branches that are not `master`, and still profit from CI runs and container images being published.
Names of feature branches are required to be prefixed with `feature-`. Container images built from them will be published using the branch name as tag.
This approach has been implemented in Hyades already:
* https://github.com/DependencyTrack/hyades-apiserver/pull/651
* https://github.com/DependencyTrack/hyades/pull/1192
Closes #2972
N/A
- ~This PR introduces changes to the database model, and I have added …

Run builds and CI on `feature-*` branches

---

pom.xml

Bumps dependencies to their latest version.
Also ensures that properties are used consistently to manage dependency versions.
N/A
N/A

Bump dependencies to their latest version

---

.github/workflows/_meta-build.yaml
.github/workflows/ci-release.yaml
.github/workflows/ci-test.yaml

Disables Maven transfer progress in CI.
The download logs are not useful at all, and instead clutter the build logs. Disable it to make inspection of CI build logs less annoying.
N/A
N/A

Disable Maven transfer progress in CI

---

docs/_config.yml
docs/_posts/2024-05-07-v4.11.0.md

Fixes changelog typo; Sets release date; Bumps docs version.
N/A
N/A

Fix changelog typo; Set release date; Bump docs version

---

src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java

Fixes missing default repos for Hackage and Nixpkgs.
This was missed in https://github.com/DependencyTrack/dependency-track/pull/3549
Relates to #3545
N/A

Fix missing default repos for Hackage and Nixpkgs

---

pom.xml
src/test/resources/logging.properties

Currently, every `ResourceTest` prints log statements along the lines of:
```
May 06, 2024 5:25:03 PM org.glassfish.jersey.test.grizzly.GrizzlyWebTestContainerFactory$GrizzlyWebTestContainer <init>
INFO: Creating GrizzlyWebTestContainer configured at the base URI http://localhost:9998/
May 06, 2024 5:25:03 PM org.glassfish.grizzly.servlet.WebappContext deploy
INFO: Starting application [TestContext] ...
May 06, 2024 5:25:05 PM org.glassfish.grizzly.servlet.WebappContext initServlets
INFO: [TestContext] Servlet [org.glassfish.jersey.servlet.ServletContainer] registered for url pattern(s) [[/*]].
May 06, 2024 5:25:05 PM org.glassfish.grizzly.servlet.WebappContext deploy
INFO: Application [TestContext] is ready to service requests.  Root: [].
May 06, 2024 5:25:05 PM …
```

Reduce verbosity of `ResourceTest`s

---

.github/workflows/_meta-build.yaml
.github/workflows/ci-release.yaml
.github/workflows/ci-test.yaml
DEVELOPING.md
docs/_posts/2024-xx-xx-v4.12.0.md
pom.xml
src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
src/test/java/org/dependencytrack/common/ManagedHttpClientFactoryTest.java

Raises the baseline Java version to 21.
This allows us to make use of new language features introduced since Java 17.
We've been shipping container images with JRE 21 since DT v4.10.0.
N/A
N/A

Raise baseline Java version to 21

---

docs/_docs/getting-started/configuration.md
docs/_docs/getting-started/database-support.md
src/main/resources/application.properties

Updates database support docs.
* Raise supported versions for PostgreSQL and SQL Server to non-EOL versions
* Add notice about deprecation of RDBMSes other than PostgreSQL in DT v5
N/A
N/A

Update database support docs

---

docs/_posts/2024-05-19-v4.11.1.md
docs/_posts/2024-05-xx-v4.11.1.md
pom.xml

Adds changelog for v4.11.1, and bumps the bundled frontend to v4.11.1.
N/A
N/A

Add changelog for v4.11.1 and bump bundled frontend

---

pom.xml

Fixes `jakarta.servlet-api` not being inherited from `alpine-server`.
For some reason the inheritance of this transitive dependency stopped working over night(?), despite nothing having changed in either Alpine or Dependency-Track since the last successful build.
Building an executable WAR succeeds, but other Maven goals such as `datanucleus:enhance` or `verify` fail due to the missing servlet API.
N/A
N/A …

Fix `jakarta.servlet-api` not being inherited from `alpine-server`

---

pom.xml

Bumps bundled frontend to 4.11.2.
N/A
https://github.com/DependencyTrack/frontend/releases/tag/4.11.2

Bump bundled frontend to 4.11.2

---

pom.xml

Bumps bundled frontend to 4.11.2.
N/A
https://github.com/DependencyTrack/frontend/releases/tag/4.11.2

Backport: Bump bundled frontend to 4.11.2

---

docs/_posts/2024-06-02-v4.11.2.md

Adds changelog for version 4.11.2.
N/A
N/A

Add changelog for v4.11.2

---

docs/_posts/2024-06-03-v4.11.3.md
pom.xml
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java

Fixes `JDODataStoreException` for unresolved licenses during BOM upload processing.
Fixes #3798
This change does not need to be ported to `master` / `4.12`, since the defect only affects the legacy `BomUploadProcessingTask`, which has been removed via #3722.

Fix `JDODataStoreException` for unresolved licenses during BOM upload processing

---

.github/ISSUE_TEMPLATE/adopt-dependency-track.yaml
ADOPTERS.md

Add an ADOPTERS file that lists people who are using OWASP Dependency Track in interesting ways.
Created a `ADOPTERS.md` file as well as `Adopt Dependency Track` issue template to submit to add organizations to the ADOPTERS list.

Creating ADOPTERS.md as well as ADOPTERS ISSUE Type for future adopters showcase

---

pom.xml

Bumps `cyclonedx-core-java` to `9.0.2`.
Since Dependabot appears to be unable to do so.
N/A
N/A

Bump `cyclonedx-core-java` to `9.0.2`

---

pom.xml
src/main/java/org/dependencytrack/util/XmlUtil.java
src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java

Fixes BOM validation failing when URL contains encoded `[` and `]` characters.
Fixes #3831
N/A

Fix BOM validation failing when URL contains encoded `[` and `]` characters

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java

Disables XXE support in the `XmlInputFactory` used for determining the schema version prior to validation.
N/A
N/A

Prevent XXE injection during CycloneDX validation and parsing

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java

Disables XXE support in the `XmlInputFactory` used for determining the schema version prior to validation.
Backports #3870 
N/A

Backport: Prevent XXE injection during CycloneDX validation and parsing

---

pom.xml

Bumps the bundled frontend to 4.11.4.
N/A
N/A

Bump bundled frontend to 4.11.4

---

pom.xml

Bumps the bundled frontend to 4.11.4.
Backports #3874 
N/A

Backport: Bump bundled frontend to 4.11.4

---

docs/_posts/2024-06-24-v4.11.4.md

Adds changelog for v4.11.4.
N/A
N/A

Add changelog for v4.11.4

---

src/main/java/org/dependencytrack/model/validation/LowerCase.java
src/main/java/org/dependencytrack/model/validation/LowerCaseValidator.java
src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/TagResource.java
src/main/java/org/dependencytrack/resources/v1/vo/TagListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedPolicyListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedProjectListResponseItem.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Adds REST endpoints for tag retrieval:
Relates to https://github.com/DependencyTrack/dependency-track/issues/586
Closes #3886
Response of `/api/v1/tag`:
Response of `/api/v1/tag/{name}/policy`:
Response of `/api/v1/tag/{name}/project`:
Frontend PR: https://github.com/DependencyTrack/frontend/pull/922

Add REST endpoints for tag retrieval

---

ADOPTERS.md

Added Air France-KLM as DT adopter, hoping it will help you gain some more visibility !

Added Air France-KLM as DT adopter

---

.idea/runConfigurations/Jetty with H2 Console.run.xml
.idea/runConfigurations/Jetty.run.xml
src/main/docker/Dockerfile

[String de-duplication](https://openjdk.org/jeps/192) was originally only supported with G1GC, but was ported to ParallelGC in Java 18: https://tschatzl.github.io/2022/03/14/jdk18-g1-parallel-gc-changes.html
Running DT with `-Xlog:stringdedup*=debug` (originally `-XX:+PrintStringDeduplicationStatistics`) tells me that the JVM is able to de-dupe >60% of strings on average.
N/A
N/A
- ~This PR …

Enable string de-duplication JVM option per default

---

src/main/java/org/dependencytrack/auth/Permissions.java
src/main/java/org/dependencytrack/exception/TagOperationFailedException.java
src/main/java/org/dependencytrack/model/Policy.java
src/main/java/org/dependencytrack/model/Tag.java
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
src/main/java/org/dependencytrack/resources/v1/TagResource.java
src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
src/main/java/org/dependencytrack/resources/v1/problems/TagOperationProblemDetails.java
src/main/java/org/dependencytrack/util/PersistenceUtil.java
src/test/java/org/dependencytrack/auth/PermissionsTest.java
src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Adds REST endpoint for tag deletion.
Relates to https://github.com/DependencyTrack/dependency-track/issues/586
Frontend PR: https://github.com/DependencyTrack/frontend/pull/928

Add REST endpoint for tag deletion

---

docs/_docs/getting-started/configuration.md

Adds documentation for the use of BASE_PATH, as added in https://github.com/DependencyTrack/frontend/pull/801

docs: add docs for base_path

---

src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
src/main/java/org/dependencytrack/resources/v1/TagResource.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Adds the new endpoints:
* `POST /api/v1/tag/{name}/policy`
* `DELETE /api/v1/tag/{name}/policy`
And deprecates the redundant endpoints:
* `POST /api/v1/policy/{uuid}/tag/{name}`
* `DELETE /api/v1/policy/{uuid}/tag/{name}`
Relates to #586 
N/A

Add REST endpoints to tag and untag policies in bulk

---

pom.xml

Bumps `io.github.jeremylong:open-vulnerability-clients` from 6.1.1 to 6.1.2.
Fixes #3927
Backports #3926 
N/A

Backport: Bump io.github.jeremylong:open-vulnerability-clients from 6.1.1 to 6.1.2

---

src/main/docker/Dockerfile

Bumps the debian base image from `0200978` to `f8bbfa0`.
Backports #3912 
Resolves a few vulnerabilities in OS packages.

Backport: Bump debian from `0200978` to `f8bbfa0`

---

pom.xml

Bumps `oauth2-oidc-sdk` from 10.15 to 11.13.
Resolves CVE-2023-52428. 
Note that the vulnerability is **not** exploitable in Dependency-Track, this update is performed for general project hygiene.
N/A

Bump `oauth2-oidc-sdk` from 10.15 to 11.13

---

pom.xml

Bumps the bundled frontend to 4.11.5.
N/A
N/A

Bump bundled frontend to 4.11.5

---

src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/main/java/org/dependencytrack/resources/v1/TagResource.java
src/main/java/org/dependencytrack/resources/v1/exception/JsonMappingExceptionMapper.java
src/main/java/org/dependencytrack/resources/v1/exception/NoSuchElementExceptionMapper.java
src/main/java/org/dependencytrack/resources/v1/exception/TagOperationFailedExceptionMapper.java
src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Some temporary changes have accumulated to work around issues in Alpine 3.0.0-SNAPSHOT. These issues have now been fixed, so this change removes those workarounds.
N/A
N/A

Cleanup temporary workarounds

---

src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Adds regression test for missing `parent` property in `/v1/project/{uuid}` response.
Fixes #3883
The behavior described in #3883 was reproducible with the v4.11.x codebase, but not the current `master`. 
I suspect that https://github.com/stevespringett/Alpine/pull/552 fixed this.

Add regression test for missing `parent` property in `/v1/project/{uuid}` response

---

src/main/java/org/dependencytrack/common/MdcKeys.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/main/java/org/dependencytrack/tasks/CloneProjectTask.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java

Adds regression test for #3895. The behavior itself does not reproduce on `master`, but does with `4.11.5`.
Wraps the project cloning in a transaction to make it more reliable. Adds MDC variables for `CloneProjectTask` (#3234).
Fixes #3895
Relates to #3981 
N/A

Ensure no unique constraint violation for `ProjectMetadata`

---

src/main/webapp/index.html

Added missing endpoints in index html for open api upgrade. This was a minor bug in the latest release of Dependency track

added missing endpoints in index html for open api upgrade

---

src/main/java/org/dependencytrack/parser/trivy/model/Options.java
src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java

Handles breaking change in Trivy v0.54.0 server API.
Fixes #4021
See https://github.com/DependencyTrack/dependency-track/issues/4021#issuecomment-2260758711 for details.

Handle breaking change in Trivy v0.54.0 server API

---

src/main/resources/templates/notification/publisher/email.peb
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java

Fixes the project URL for new vulnerabilities in email peb.
#3979

Fix project link for new vulnerable dependency for email

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
src/test/resources/unit/bom-issue4008.xml

Fixes validation error when XML BOM declares multiple namespaces.
Fixes #4008 
Backports #4020 
N/A

Backport: Fix validation error when XML BOM declares multiple namespaces

---

src/main/resources/templates/notification/publisher/email.peb
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java

Fixes project link for new vulnerable dependency for email.
Fixes #3979
Backports #4026
N/A

Backport: Fix project link for new vulnerable dependency for email

---

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java

Fixes `JDOUserException` when multiple licenses match a component's license name.
Fixes #3957
Backports #3958
N/A

Backport: Fix `JDOUserException` when multiple licenses match a component's license name

---

src/main/docker/Dockerfile

Bumps Temurin base image to `21.0.4_7`.
N/A
N/A

Bump Temurin base image to `21.0.4_7`

---

src/main/docker/Dockerfile

Bumps Temurin base image to `21.0.4_7`.
Backports #4055 
N/A

Backport: Bump Temurin base image to `21.0.4_7`

---

pom.xml

Bumps bundled frontend to v4.11.6.
N/A
N/A

Bump bundled frontend to v4.11.6

---

pom.xml
src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java

Fixes vex export returning invalid CycloneDX.
Fixes #3834
Backports #3948
N/A

Backport: Fix vex export returning invalid CycloneDX

---

docs/_posts/2024-08-10-v4.11.6.md

Adds changelog for v4.11.6.
N/A
N/A

Add changelog for v4.11.6

---

pom.xml

Bumps the bundled frontend to 4.11.7.
N/A
N/A

Bump bundled frontend to 4.11.7

---

pom.xml

Bumps Alpine to 3.0.1.
N/A
N/A

Bump Alpine to 3.0.1

---

src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java

In order to be sure about the behaviour when `license.name` is given with a content similar to the license's Id, I needed this (missing) test.

Add test for license finding by Id or Name

---

pom.xml

Bumps DataNucleus to 6.0.8.
Fixes #2061
N/A

Bump DataNucleus to 6.0.8

---

src/main/java/org/dependencytrack/tasks/repositories/CargoMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/CpanMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/GemMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/GoModulesMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/HackageMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/HexMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
src/main/java/org/dependencytrack/tasks/repositories/PypiMetaAnalyzer.java

Ensures URL-encoding of repository URL path segments.
PURLs containing special characters such as spaces could render the constructed repository URL invalid.
Fixes #3688
N/A

Ensure URL-encoding of repository URL path segments

---

src/main/resources/templates/notification/publisher/email.peb
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java

Fixes project being rendered as PURL in email notifications.
See https://github.com/DependencyTrack/dependency-track/issues/3978#issuecomment-2323046771 for details.
Fixes #3978
N/A

Fix project being rendered as PURL in email notifications

---

pom.xml
src/main/java/org/dependencytrack/model/BomValidationMode.java
src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java
src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java

Supports the inclusion or exclusion of projects from BOM validation, using tags.
* Removes the `artifact:bom.validation.enabled` config property
* Adds the new `artifact:bom.validation.mode` config property
* Valid options are `ENABLED`, `DISABLED`, `ENABLED_FOR_TAGS`, `DISABLED_FOR_TAGS`
* Existing `artifact:bom.validation.enabled` configs are migrated to their `artifact:bom.validation.mode` counterpart
* Adds the new `artifact:bom.validation.tags.exclusive` and `artifact:bom.validation.tags.inclusive` config properties to support the new `ENABLED_FOR_TAGS` and `DISABLED_FOR_TAGS` modes
Closes #3891
N/A …

Support inclusion/exclusion of projects from BOM validation with tags

---

docs/_posts/2024-xx-xx-v4.12.0.md

Updates changelog for v4.12.0 with recent changes.
N/A
N/A

Update changelog for v4.12.0 with recent changes

---

.github/workflows/_meta-build.yaml
pom.xml
src/main/resources/services.bom.json

Bump generated BOM to CycloneDX v1.5, and include more external references.
Closes #3602
N/A

Bump generated BOM to CycloneDX v1.5; Add external references

---

pom.xml
src/main/docker/logback-json.xml
src/main/docker/logback.xml
src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java
src/main/webapp/WEB-INF/jetty-context.xml
src/main/webapp/WEB-INF/web.xml

Bumps Alpine to version 3.1.0.
Adopts the following new framework features and changes:
* Raises the maximum length of the `TEAM.NAME` column from `50` to `255`
* Improve Jetty startup time by disabling classpath scanning
N/A
N/A

Bump Alpine to 3.1.0 and adopt new framework features

---

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java

Handles existing duplicate component properties, fixing `Duplicate Key` exceptions during BOM processing.
Fixes #4027

Handle existing duplicate component properties

---

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes `directDependencies` of cloned projects referring to original component UUIDs.
Fixes #4153
N/A

Fix `directDependencies` of cloned projects referring to original component UUIDs

---

docs/_docs/best-practices.md

Adds a missing parenthesis in the documentation
None
Documentation change

Fix missing parenthesis in documentation

---

src/main/java/org/dependencytrack/model/DependencyMetrics.java
src/main/java/org/dependencytrack/model/ProjectMetrics.java

Fixes metrics endpoint API docs erroneously claiming to return project and component data.
Fixes #3884
Supersedes #3918
N/A

Fix metrics endpoint API docs erroneously claiming to return project and component data

---

src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java

Projects are removed from the vulnerability, from which the principal has no access to so.
Fixes [#4200](https://github.com/DependencyTrack/dependency-track/issues/4200)
~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~

Fix: Unauthorized access to projects over /vulnerability/{source}/vuln/{vuln}(/projects) when ACL is enabled

---

src/test/java/org/dependencytrack/policy/PolicyEngineTest.java

Fixes potential race condition in `PolicyEngineTest#notificationTest`.
Since notification dispatch happens asynchronously, it's possible that the assertion happens before the notification is received. Await notifications with a small timeout instead.
N/A
Example test failure: https://github.com/DependencyTrack/dependency-track/actions/runs/11124919968/job/30911500389#step:4:486
- ~This PR …

Fix potential race condition in `PolicyEngineTest#notificationTest`

---

src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java

Fixes `getAffectedProjectACLDisabledTest` flakiness.
The projects array returned by this endpoint is not guaranteed to have consistent ordering, causing occasional test failures.
Example test failure: https://github.com/DependencyTrack/dependency-track/actions/runs/11126300521/job/30915909435?pr=4204
N/A
N/A …

Fix `getAffectedProjectACLDisabledTest` flakiness

---

pom.xml

Bumps mysql-connector-j to 8.2.0.
Note that 8.2.0 is the highest possible version that still supports MySQL 5.7. We cannot upgrade further without investing more time into ensuring compatibility with MySQL 8.
Addresses CVE-2023-22102
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_ …

Bump mysql-connector-j to 8.2.0

---

.github/workflows/_meta-build.yaml
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java

Work around ghcr.io rate limiting for Trivy database downloads.
N/A
See:
* https://github.com/aquasecurity/trivy-action/issues/389
* https://github.com/orgs/community/discussions/139074

Work around ghcr.io rate limiting for Trivy database downloads

---

src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
src/main/java/org/dependencytrack/tasks/AbstractNistMirrorTask.java
src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java

Fixes `affectedComponents` getting removed when updating an internal vulnerability.
Attributions were not correctly added for `VulnerableSoftware` records when creating or updating internal vulnerabilities via REST API.
Re-using the `synchronizeVulnerableSoftware` logic from NVD mirroring tasks fixes the issue.
Fixes #4175
Supersedes #4193
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/ …

Fix `affectedComponents` getting removed when updating an internal vulnerability

---

pom.xml

Bumps the bundled frontend to 4.12.0.
N/A
N/A

Bump bundled frontend to 4.12.0

---

src/main/java/org/dependencytrack/resources/v1/UserResource.java
src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java

Fixes logs not containing usernames of deleted users.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4219
Backports: https://github.com/DependencyTrack/dependency-track/pull/4222
N/A

Backport: Fix logs not containing usernames of deleted users

---

src/main/resources/application.properties

Fixes unintended manual flushing mode due to DataNucleus `ExecutionContext` pooling.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4220
Backports https://github.com/DependencyTrack/dependency-track/pull/4221
N/A

Backport: Fix unintended manual flushing mode due to DataNucleus `ExecutionContext` pooling

---

src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/test/java/org/dependencytrack/policy/PolicyEngineTest.java

Enhances the policy violation de-duplication logic introduced in https://github.com/DependencyTrack/dependency-track/pull/4216.
Instead of just discarding *any* duplicate, compare them first, and only keep the most "useful" one.
See https://github.com/DependencyTrack/dependency-track/issues/4215#issuecomment-2400099379 for context.
Relates to #4215
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-t …

Enhance policy violation de-duplication logic

---

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java

Fixes redundant query for "ignore unfixed" config during Trivy analysis.
N/A
N/A

Fix redundant query for "ignore unfixed" config during Trivy analysis

---

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java

Fixes inaccuracies of the Trivy analyzer, which could lead to both too many, or too few vulnerabilities being reported.
Relates to #4164
Fixes #4257
Backports #4245
N/A

Backport: Fix inaccuracies of Trivy analyzer

---

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java

Fixes redundant query for "ignore unfixed" config during Trivy analysis.
Backports #4246
N/A

Backport: Fix redundant query for "ignore unfixed" config during Trivy analysis

---

pom.xml

Bumps cyclonedx-core-java to 9.1.0.
Fixes #4144
Backports #4270
N/A

Backport: Bump cyclonedx-core-java to 9.1.0

---

ADOPTERS.md

Added the Dutch Tax office as an Adopter of Dependency-Track.

Added Dutch tax office as adopter

---

ADOPTERS.md

Adds World Kinect Corporation to `ADOPTERS.md` as requested via #3810.
Closes #3810
N/A

Add World Kinect to `ADOPTERS.md`

---

ADOPTERS.md

Adds Rohde & Schwarz to `ADOPTERS.md` as requested via #4295.
Closes #4295
N/A

Add Rohde & Schwarz to `ADOPTERS.md`

---

pom.xml

Bumps Alpine to 3.1.1.
Fixes #4238
N/A

Bump Alpine to 3.1.1

---

pom.xml

Bumps Alpine to 3.1.1.
Fixes #4238
Backports #4308
N/A

Backport: Bump Alpine to 3.1.1

---

.idea/runConfigurations/Jetty.run.xml

Restricts max heap size of `Jetty` IntelliJ run configuration to 2GB.
Prevents the heap to grow unreasonably large during local development.
N/A
N/A

Restrict max heap size of `Jetty` run config to 2GB

---

src/main/docker/Dockerfile

Bumps Temurin base image to 21.0.5_11.
N/A
N/A

Bump Temurin base image to 21.0.5_11

---

src/main/docker/Dockerfile

Bumps Temurin base image to 21.0.5_11.
Backports https://github.com/DependencyTrack/dependency-track/pull/4314
N/A

Backport: Bump Temurin base image to 21.0.5_11

---

src/main/java/org/dependencytrack/model/Component.java
src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java

Fixes excessive memory usage of portfolio repository meta analysis.
The task was fetching all projects of the entire portfolio at once, which couldn't be garbage collected until the task finished, causing excessive prolonged memory usage for larger portfolios.
Fetch components in batches of up to 1000 instead. There a lot more about this task that could be optimized, but for the time being, this change should fix the most pressing issue.
N/A
See https://github.com/DependencyTrack/dependency-track/discussions/4124#discussioncomment-10559195 for details. …

Fix excessive memory usage of portfolio repository meta analysis

---

pom.xml

Bumps the bundled frontend to 4.12.1.
Backports #4318 
N/A

Backport: Bump bundled frontend to 4.12.1

---

pom.xml

Bumps the bundled frontend to 4.12.1.
N/A
N/A

Bump bundled frontend to 4.12.1

---

docs/_posts/2024-10-25-v4.12.1.md

Adds changelog for v4.12.1.
N/A
N/A

Add changelog for v4.12.1

---

src/main/java/org/dependencytrack/common/ConfigKey.java
src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoClient.java
src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploader.java
src/main/resources/application.properties

Added a new configurable property to manage the "Verified" flag in DefectDojo integration. This allows users to control whether or not the "Verified" flag should be set when uploading findings to DefectDojo.
Closes #3389.

Add property to control `verified` flag in DefectDojo integration

---

src/main/java/org/dependencytrack/model/DependencyMetrics.java
src/main/java/org/dependencytrack/model/PortfolioMetrics.java
src/main/java/org/dependencytrack/model/ProjectMetrics.java

Fixes nullable metrics fields having getters of primitive type.
Prevents potential NPEs in case the fields have `null` values.
Fixes #3756
N/A

Fix nullable metrics fields having getters of primitive type

---

src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java

Fix NullPointerException when fetching findings.
Fixes #4351
N/A

Fix NullPointerException when fetching findings

---

src/main/java/org/dependencytrack/model/Vulnerability.java

Fixes incorrect CWE schema in OpenAPI spec.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4349
Backports #4350
N/A

Backport: Fix incorrect CWE schema in OpenAPI spec

---

src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java

Fixes NullPointerException when fetching findings.
Fixes #4351
Backports https://github.com/DependencyTrack/dependency-track/pull/4369
N/A

Backport: Fix NullPointerException when fetching findings

---

src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
src/test/java/org/dependencytrack/tasks/PolicyEvaluationTaskTest.java

Fixes policy evaluation not happening upon creation or update of individual components.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4373
Backports https://github.com/DependencyTrack/dependency-track/pull/4374
N/A

Backport: Fix policy evaluation not happening upon creation or update of individual components

---

src/main/java/org/dependencytrack/model/DependencyMetrics.java
src/main/java/org/dependencytrack/model/PortfolioMetrics.java
src/main/java/org/dependencytrack/model/ProjectMetrics.java

Fixes nullable metrics fields having getters of primitive type.
Fixes #3756
Backports https://github.com/DependencyTrack/dependency-track/pull/4326
N/A

Backport: Fix nullable metrics fields having getters of primitive type

---

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java

Fixes Trivy analyzer vulnerability matching for Go packages.
Fixes #4376
N/A

Fix Trivy analyzer vulnerability matching for Go packages

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes a `NullPointerException` when cloning projects with broken dependency graph.
Fixes #4413
N/A

Fix NPE when cloning projects with broken dependency graph

---

src/main/java/org/dependencytrack/resources/v1/BomResource.java

Adds cyclonedx json media type when exporting components.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4408
Backports #4409
N/A

Backport: Add cyclonedx json media type when exporting components

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes a `NullPointerException` when cloning projects with broken dependency graph.
Fixes #4413
Backports #4414
N/A

Backport: Fix NPE when cloning projects with broken dependency graph

---

src/main/java/org/dependencytrack/parser/common/resolver/CweResolver.java
src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java

Fixes broken pagination in `/api/v1/cwe` endpoint.
Fixes #3856
N/A

Fix broken pagination in `/api/v1/cwe` endpoint

---

pom.xml

Bump Alpine to 3.1.2

---

pom.xml

Bumps Alpine to 3.1.2.
Backports #4433
N/A

Backport: Bump Alpine to 3.1.2

---

docs/_docs/integrations/community-integrations.md

In November of 2023, after 11 years of working for GSoft, now know as Workleap, I have moved on to other projects. Because of this, I have no longer been unable to maintain the GSoft version of this extension. It is for this reason I have forked it and published a new one under my own name.
This PR is to replace the community integration for the maintained one.
No issues created for this PR.

Update Azure DevOps Extension

---

pom.xml

Bumps the bundled frontend to 4.12.2.
N/A
N/A

Bump bundled frontend to 4.12.2

---

pom.xml

Bumps the bundled frontend to 4.12.2.
Backports #4440
N/A

Backport: Bump bundled frontend to 4.12.2

---

pom.xml

Fixes incompatibility of swagger-core with newer jackson-databind versions.
N/A
https://github.com/swagger-api/swagger-core/issues/4755

Fix incompatibility of swagger-core with newer jackson-databind versions

---

docs/_posts/2024-12-04-v4.12.2.md

Adds changelog for v4.12.2.
N/A
N/A

Add changelog for v4.12.2

---

src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java

Fix notification tests not working for Jira
While assembling the configuration of the publisher under test, values defined on the notification rule config were partially dropped. This caused e.g. `jiraTicketType` to not be forwarded correctly.
Fixes #4237
N/A

Fix notification tests not working for Jira

---

src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
src/test/resources/unit/bom-issue4455.json

Fixes component de-duplication potentially causing duplicate dependency graph entries.
Fixes #4455
N/A

Fix component de-duplication potentially causing duplicate dependency graph entries

---

src/main/java/org/dependencytrack/parser/common/resolver/CweResolver.java
src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java

Fixes broken pagination in `/api/v1/cwe` endpoint.
Fixes #3856
Backports #4421
N/A

Backport: Fix broken pagination in `/api/v1/cwe` endpoint

---

DEVELOPING.md

Add command example to run a single unit test.

Update DEVELOPING.md with command for single unit-test

---

src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes component SWID tag ID not being considered in project cloning.
Fixes #4478
N/A

Fix component SWID tag ID not being considered in project cloning

---

src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Fixes REST endpoints for adding tags.
Fixes #4539
Backports #4541 
N/A

Backport: Fix REST endpoints for adding tags

---

src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
src/main/java/org/dependencytrack/upgrade/v4123/v4123Updater.java

Recreates outdated check constraints for `CLASSIFIER` columns.
Fixes #4446
Backports #4544 
N/A

Recreate outdated check constraints for `CLASSIFIER` columns

---

dev/docker-compose.postgres.yml
src/main/docker/docker-compose.yml

Updates quickstart Compose file to use Postgres instead of H2.
Since we don't recommend using H2, and H2 keeps causing issues, we shouldn't have it as a default for new users.
Relates to #4573
N/A

Update quickstart Compose file to use Postgres instead of H2

---

pom.xml

Bumps the bundled frontend to 4.12.3.
N/A
N/A

Bump bundled frontend to 4.12.3

---

pom.xml

Bump bundled frontend to 4.12.3.
Backports #4588 
N/A

Backport: Bump bundled frontend to 4.12.3

---

docs/_posts/2025-01-27-v4.12.3.md

Adds changelog for v4.12.3.
N/A
N/A

Add changelog for v4.12.3

---

src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes possible NPEs during tag binding.
Fixes #4593
N/A

Fix possible NPEs during tag binding

---

src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzerTest.java

Fix erroneous URL-encoding of the Maven groupId for repository metadata analysis.
Fixes #4601
N/A

Fix erroneous URL-encoding of the Maven groupId 

---

src/main/docker/Dockerfile

Bumps Temurin base image to 21.0.6_7.
N/A
N/A

Bump Temurin base image to 21.0.6_7

---

src/main/docker/Dockerfile

Bumps Temurin base image to 21.0.6_7.
Backports #4627
N/A

Backport: Bump Temurin base image to 21.0.6_7

---

src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzerTest.java

Fixes erroneous URL-encoding of the Maven groupId for repository metadata analysis.
Fixes #4601
N/A

Backport: Fix erroneous URL-encoding of the Maven groupId

---

src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java

Handles invalid CVSS vectors and processing failures for OSV.
https://owasp.slack.com/archives/C6R3R32H4/p1739174871949499
N/A

Handle invalid CVSS vectors and processing failures for OSV

---

src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java

Handles invalid CVSS vectors and processing failures for OSV.
https://owasp.slack.com/archives/C6R3R32H4/p1739174871949499
Backports #4636 
N/A

Backport: Handle invalid CVSS vectors and processing failures for OSV

---

pom.xml

Bumps bundled frontend to 4.12.4.
N/A
N/A

Backport: Bump bundled frontend to 4.12.4

---

docs/_posts/2025-02-10-v4.12.4.md

Adds changelog for v4.12.4.
N/A
N/A

Add changelog for v4.12.4

---

pom.xml

Bumps io.github.jeremylong:open-vulnerability-clients from 7.2.1 to 7.2.2.
Fixes #4654 
Backports #4653 
N/A

Backport: Bump io.github.jeremylong:open-vulnerability-clients from 7.2.1 to 7.2.2

---

pom.xml

Bumps bundled frontend to 4.12.5.
N/A
N/A

Bump bundled frontend to 4.12.5

---

pom.xml

Bumps bundled frontend to 4.12.5.
Backports #4658 
N/A

Backport: Bump bundled frontend to 4.12.5

---

docs/_posts/2025-02-17-v4.12.5.md

Adds changelog for v4.12.5.
N/A
N/A

Add changelog for v4.12.5

---

pom.xml

Bumps net.minidev:json-smart to 2.5.2.
Resolves CVE-2024-57699.
Highly unlikely to be exploitable in DT or Alpine, but we're bumping the
version anyway since the update is low-risk and reduces scanner noise.
N/A

Bump net.minidev:json-smart to 2.5.2

---

src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java

Analyzes all components of a project at once instead of in batches.
Unfortunately this is necessary to support Trivy properly, because it checks for the existence of `OPERATING_SYSTEM` components in a project. If we were to analyze components in batches, this logic might not work for large projects.
N/A
N/A

Analyze all components of a project at once instead of in batches

---

src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java

* Fixes possible NPEs in `TrivyAnalysisTask`.
* Execute Trivy integration tests against `VulnerabilityAnalysisTask`.
* Fix components being made transient when they should be detached in `VulnerabilityAnalysisTask`.
Fixes #4664
Backports #4668
N/A

Backport: Fix possible NPEs in TrivyAnalysisTask

---

pom.xml

Bumps net.minidev:json-smart to 2.5.2.
Resolves CVE-2024-57699.
Highly unlikely to be exploitable in DT or Alpine, but we're bumping the
version anyway since the update is low-risk and reduces scanner noise.
Backports #4669
N/A …

Backport: Bump net.minidev:json-smart to 2.5.2

---

src/main/resources/application.properties

chore: fix typos in properties file

---

src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java

Fixes notification webhook sending blank header.
Fixes #4344
Backports #4679
N/A

Backport: Fix notification webhook sending blank header

---

dev/docker-compose.yml
src/main/java/org/dependencytrack/resources/v1/TeamResource.java
src/main/java/org/dependencytrack/upgrade/PreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/UpgradeInitializer.java
src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
src/main/java/org/dependencytrack/upgrade/v4130/v4130PreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/v4130/v4130_1Updater.java
src/main/resources/META-INF/services/org.dependencytrack.upgrade.PreUpgradeHook
src/test/java/org/dependencytrack/ResourceTest.java
src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java

Fixes incomplete API key migration.
Fixes #4652
Fixes #4683
N/A

Fix incomplete API key migration

---

pom.xml
src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
src/main/java/org/dependencytrack/notification/publisher/ConsolePublisher.java
src/main/java/org/dependencytrack/notification/publisher/CsWebexPublisher.java
src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
src/main/java/org/dependencytrack/notification/publisher/MattermostPublisher.java
src/main/java/org/dependencytrack/notification/publisher/MsTeamsPublisher.java
src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
src/main/java/org/dependencytrack/notification/publisher/SlackPublisher.java
src/main/java/org/dependencytrack/notification/publisher/WebhookPublisher.java
src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java

Disables `include` tag for Pebble templates.
N/A
N/A

Disable `include` tag for Pebble templates

---

docs/_posts/2025-02-24-v4.12.6.md

Adds changelog for v4.12.6.
N/A
N/A

Add changelog for v4.12.6

---

src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java

Fixes NPE during NVD mirroring via REST API when encountering invalid CPEs.
Fixes #4731
Backports #4732 
N/A

Backport: Fix NPE during NVD mirroring via REST API when encountering invalid CPEs

---

src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java

Fixes tags from BOM upload request not being applied for existing projects.
Fixes #4713
N/A

Fix tags from BOM upload request not being applied for existing projects

---

src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java

Fixes tags from BOM upload request not being applied for existing projects.
Fixes #4713
Backports #4738 
N/A

Backport: Fix tags from BOM upload request not being applied for existing projects

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes component properties not being cloned.
Backports https://github.com/DependencyTrack/hyades-apiserver/pull/1089
N/A

Fix component properties not being cloned

---

src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Fixes component properties not being cloned.
Backports #4745
N/A

Backport: Fix component properties not being cloned

---

src/main/java/org/dependencytrack/model/Project.java
src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
src/test/java/org/dependencytrack/tasks/VulnerabilityAnalysisTaskTest.java

adds a "lastVulnerabilityAnalysis" field to the Project model.
Closes #4620

#4620 add "lastVulnerabilityAnalysis" to project

---

pom.xml

Bumps the bundled frontend to 4.12.7.
N/A
N/A

Bump bundled frontend to 4.12.7

---

pom.xml

Bumps the bundled frontend to 4.12.7.
N/A
N/A

Backport: Bump bundled frontend to 4.12.7

---

docs/_posts/2025-03-12-v4.12.7.md

Adds changelog for v4.12.7.
N/A
N/A

Add changelog for v4.12.7

---

src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java

To be frank, I'm not really sure about what I did here, but it fixes a corner case.
Closes #4662

handle corner case if no vulnerabilities have compatible aliases

---

docs/_docs/getting-started/openidconnect-configuration.md

This PR updates the Azure Active Directory to Microsoft Entra ID  app registration documentation to clarify the recommended configuration for group claims in token settings. It highlights the potential risks of including all security groups in tokens—especially in enterprise environments where users may be part of thousands of groups—and instead recommends selecting only groups assigned to the application. This change helps prevent token size overflow and Single Sign-On (SSO) issues.
Closes #4770
While testing Microsoft Entra ID integration with Dependency-Track, I encountered token bloat issues due to the inclusion of too many group claims. This update provides practical guidance for both testing scenarios and corporate environments, improving the reliability of Entra ID SSO integration …

docs: Update Azure AD configuration to Entra ID

---

src/main/java/org/dependencytrack/parser/common/resolver/CweDictionary.java
src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java

Bumps the CWE dictionary to v4.16.
N/A
Generated using:
```
jbang gen-cwe-dict@DependencyTrack --version 4.16 --package org.dependencytrack.parser.common.resolver --output src/main/java/org/dependencytrack/parser/common/resolver/CweDictionary.java --jakarta
```

Bump CWE dictionary to v4.16

---

pom.xml

Bumps dependencies that Dependabot missed.
N/A
N/A

Bump dependencies that Dependabot missed

---

pom.xml

Bumps Alpine to 3.2.0.
N/A
N/A

Bump Alpine to 3.2.0

---

src/main/java/org/dependencytrack/parser/snyk/SnykParser.java
src/main/java/org/dependencytrack/tasks/scanners/VulnDbAnalysisTask.java

Fixes regression in Snyk vulnerability assignment.
Fixes #4716
N/A

Fix regression in Snyk vulnerability assignment

---

src/main/java/org/dependencytrack/upgrade/v4130/v4130_1Updater.java

Fixes missing migration of the `CONFIGPROPERTY.PROPERTYVALUE` column.
The migration is required in order to support https://github.com/stevespringett/Alpine/pull/722.
N/A
N/A

Fix missing migration of CONFIGPROPERTY.PROPERTYVALUE

---

pom.xml

Bumps open-vulnerability-clients to v7.3.2.
N/A
N/A

Bump open-vulnerability-clients to v7.3.2

---

pom.xml

Bumps pebble to 3.2.4.
N/A
N/A

Bump pebble to 3.2.4

---

src/main/java/org/dependencytrack/upgrade/UpgradeInitializer.java

Fixes `UpgradeInitializer` halting the entire process upon failure.
Fixes #4724
N/A

Fix `UpgradeInitializer` halting the entire process upon failure

---

pom.xml

Bumps the bundled frontend to 4.13.0.
N/A
N/A

Bump bundled frontend to 4.13.0

---

src/main/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTask.java

Fixes `NEW_VULNERABILITIES_SUMMARY` notification dispatch failing for PostgreSQL.
The PostgreSQL JDBC driver does not accept `java.util.Date` (or subclasses of it) as query parameter, while H2 and MSSQL do.
Converting the respective date parameter to `java.sql.Timestamp` works with all JDBC drivers.
Fixes #4827
N/A …

Fix `NEW_VULNERABILITIES_SUMMARY` notification dispatch failing for PostgreSQL

---

src/main/java/org/dependencytrack/notification/NotificationRouter.java
src/main/java/org/dependencytrack/notification/publisher/PublishContext.java
src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java

Fixes team email addresses not being available when publishing scheduled notification emails.
**TODO**:
Fixes #4840
N/A

Fix team email addresses not being available when publishing scheduled notification emails

---

dev/docker-compose.postgres.yml
src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
src/main/java/org/dependencytrack/model/NotificationRule.java
src/main/java/org/dependencytrack/model/Policy.java
src/main/java/org/dependencytrack/model/Project.java
src/main/java/org/dependencytrack/model/Tag.java
src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
src/main/java/org/dependencytrack/upgrade/PreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/UpgradeInitializer.java
src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
src/main/java/org/dependencytrack/upgrade/v4130/v4130PreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/v4131/TagDeduplicationPreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/v4131/v4131Updater.java
src/main/java/org/dependencytrack/util/NotificationUtil.java
src/main/resources/META-INF/services/org.dependencytrack.upgrade.PreUpgradeHook
src/test/java/org/dependencytrack/model/PolicyTest.java
src/test/java/org/dependencytrack/model/TagTest.java
src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Prevents duplicate tag names and relationships.
* Adds missing (unique) index on tag names.
* Adds composite primary keys to all join tables of tag relationships.
* Changes tag relationships from ordered `List`s to `Set`s. We don't need ordering here, and it only adds overhead.
* Changes `equals` and `hashCode` of `Tag` to be based on `name`, rather than `id`.
* Removes and re-wires any duplicate records during the DB migration.
**TODO**:
Fixes #4831
N/A

Prevent duplicate tag names and relationships

---

src/main/java/org/dependencytrack/notification/NotificationRouter.java
src/main/java/org/dependencytrack/notification/publisher/PublishContext.java
src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java

Fixes team email addresses not being available when publishing scheduled notification emails.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4840
Backports https://github.com/DependencyTrack/dependency-track/pull/4845
N/A

Backport: Fix team email addresses not being available when publishing scheduled notification emails

---

dev/docker-compose.postgres.yml
src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
src/main/java/org/dependencytrack/model/NotificationRule.java
src/main/java/org/dependencytrack/model/Policy.java
src/main/java/org/dependencytrack/model/Project.java
src/main/java/org/dependencytrack/model/Tag.java
src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/BomResource.java
src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
src/main/java/org/dependencytrack/upgrade/PreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/UpgradeInitializer.java
src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
src/main/java/org/dependencytrack/upgrade/v4130/v4130PreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/v4131/TagDeduplicationPreUpgradeHook.java
src/main/java/org/dependencytrack/upgrade/v4131/v4131Updater.java
src/main/java/org/dependencytrack/util/NotificationUtil.java
src/main/resources/META-INF/services/org.dependencytrack.upgrade.PreUpgradeHook
src/test/java/org/dependencytrack/model/PolicyTest.java
src/test/java/org/dependencytrack/model/TagTest.java
src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java

Prevents duplicate tag names and relationships.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4831
Backports https://github.com/DependencyTrack/dependency-track/pull/4837
N/A

Backport: Prevent duplicate tag names and relationships

---

src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java

Improves the stability of tag binding.
This is mostly a preventative change than one based on actual issues encountered.
Removing from a collection that is being iterated over is not supported and should usually lead to a `ConcurrentModificationException` being thrown. Using an `Iterator` prevents this from happening.
N/A
N/A
- ~This PR introduces new or alters existing behavior, and I have updated …

Improve the stability of tag binding

---

src/main/java/org/dependencytrack/upgrade/v4131/v4131Updater.java

Fixes missing `NONE` value in classifier check constraint.
Fixes #4844

Fix missing `NONE` value in classifier check constraint

---

src/main/docker/Dockerfile

Bumps Temurin base image to 21.0.7.
Backports https://github.com/DependencyTrack/dependency-track/pull/4883
N/A

Backport: Bump Temurin base image to 21.0.7

---

src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java

Improves the stability of tag binding.
This is mostly a preventative change than one based on actual issues encountered.
Removing from a collection that is being iterated over is not supported and should usually lead to a `ConcurrentModificationException` being thrown. Using an `Iterator` prevents this from happening.
Backports https://github.com/DependencyTrack/dependency-track/pull/4882
N/A
- …

Backport: Improve the stability of tag binding

---

src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/TagResource.java
src/main/java/org/dependencytrack/resources/v1/vo/TagListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedCollectionProjectListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedNotificationRuleListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedPolicyListResponseItem.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Fixes tag deletion failing when tag is used by project collection logic.
N/A
N/A

Fix tag deletion failing when tag is used by project collection logic

---

src/main/java/org/dependencytrack/persistence/QueryManager.java
src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/main/java/org/dependencytrack/resources/v1/TagResource.java
src/main/java/org/dependencytrack/resources/v1/vo/TagListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedCollectionProjectListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedNotificationRuleListResponseItem.java
src/main/java/org/dependencytrack/resources/v1/vo/TaggedPolicyListResponseItem.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

Fixes tag deletion failing when tag is used by project collection logic.
Backports https://github.com/DependencyTrack/dependency-track/pull/4858
N/A

Backport: Fix tag deletion failing when tag is used by project collection logic

---

pom.xml

Bumps bundled frontend to 4.13.1.
N/A
N/A

Bump bundled frontend to 4.13.1

---

docs/_posts/2025-04-30-v4.13.1.md

Adds changelog for v4.13.1.
N/A
N/A

Add changelog for v4.13.1

---

pom.xml

Migrates to maintained [protobuf-maven-plugin](https://github.com/ascopes/protobuf-maven-plugin).
[protoc-jar-maven-plugin](https://github.com/os72/protoc-jar-maven-plugin) which we have been using so far is not maintained since ~5 years.
protobuf-maven-plugin is under active development and has more features, such as incremental compilation.
N/A
N/A …

Migrate to maintained protobuf-maven-plugin

---

pom.xml

Bumps bundled frontend to 4.13.2.
N/A
N/A

Bump bundled frontend to 4.13.2

---

pom.xml

Bumps bundled frontend to 4.13.2.
Backports https://github.com/DependencyTrack/dependency-track/pull/4930
N/A

Backport: Bump bundled frontend to 4.13.2

---

docs/_posts/2025-05-09-v4.13.2.md

Adds changelog for v4.13.2.
N/A
N/A

Add changelog for v4.13.2

---

src/main/resources/templates/notification/publisher/email.peb

Added component name, version, and URL as well as the name of the broken policy to the email template. This should make it easier for an end-user to diagnose a violation.
This just adds a handful of rows to the default pebble template for emails. With this change, the default emails should include more info on the violating component as well as the license.
Improves the email portion of #4520. I did not make any changes to the Jira template, as I was unable to set up the platform, however the changes should be easily portable. 
I felt no need to update any docs, as the changes are very small and do not majorly affect behavior. I also tried to add the policy trigger/definition, however I had trouble getting consistent results with that.
The emails before:
```
Policy Violation on Project: …
```

Make POLICY_VIOLATION emails more informative

---

src/main/java/org/dependencytrack/resources/v1/FindingResource.java
src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
src/test/resources/unit/sarif/expected-all.sarif.json
src/test/resources/unit/sarif/expected-internal.sarif.json

Enable missing source filtering for SARIF format in resource `\finding\project\{uuid}`
Fixes #4816

Enable source filtering in SARIF format for /finding/project/{UUID}

---

src/main/java/org/dependencytrack/resources/v1/BomResource.java

This is my first approach, but I'm not sure about the wording: are components "linked" to a project, "included" in a project?
Also are they "unlinked" or "dropped" from a project?
I will update the https://github.com/DependencyTrack/dependency-track/blob/master/docs/_docs/usage/cicd.md?plain=1 once the wording is clarified
Closes #4868

docs: More specific description of BOM upload

---

docs/_docs/getting-started/openidconnect-configuration.md

Add AWS Cognito configuration example for OpenID Connect. Documentation change only.
https://github.com/DependencyTrack/dependency-track/issues/4407
I had some difficulties in configuring OpenID Connect with AWS Cognito same as author of issue  https://github.com/DependencyTrack/dependency-track/issues/4407. I saw proposition to add documentation in comments, so decided to do so once figured this out.

Add AWS Cognito configuration example

---

dev/docker-compose.yml
src/main/docker/docker-compose.yml

Adds apiserver health check to Compose files.
It seems Podman / Podman Compose doesn't pick up the health check from the container itself.
Fixes https://github.com/DependencyTrack/dependency-track/issues/1388
N/A

Add apiserver health check to Compose files

---

src/main/java/org/dependencytrack/model/validation/SpdxExpressionValidator.java
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java
src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java
src/test/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParserTest.java

Handles dangling SPDX expression operators.
Also addresses deprecated `getLicenseChoice` / `setLicenseChoice` methods of CycloneDX.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5025
N/A

Handle dangling SPDX expression operators

---

src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java

Fixes too many query parameters when retrieving vulnerability aliases.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5096
N/A

Fix too many query parameters when retrieving vuln aliases

---

src/main/java/org/dependencytrack/upgrade/v4131/v4131Updater.java

Fixes failing v4.13.1 migration for H2 deployments that pre-date v4.11.0.
Relates to https://github.com/DependencyTrack/dependency-track/issues/4906
N/A

Fix failing v4.13.1 migration for H2 deployments that pre-date v4.11.0

---

src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
src/main/java/org/dependencytrack/resources/v1/FindingResource.java
src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java

Related issue: #5092
This PR adds EPSS (Exploit Prediction Scoring System) filtering capabilities to the findings API, enabling users to filter vulnerability findings based on EPSS metrics for improved risk-based vulnerability prioritization.
**New Features:**
- Add `epssFrom` and `epssTo` query parameters for EPSS score filtering (0.0 to 1.0 range)
- Add `epssPercentileFrom` and `epssPercentileTo` query parameters for EPSS percentile filtering (0.0 to 1.0 range)
- Support range-based filtering for both individual findings and grouped findings endpoints
- Enable filtering on both EPSS score and percentile values independently or in combination
**API Endpoints Enhanced:**
- `GET /api/v1/finding` - Individual findings with EPSS filtering
- `GET /api/v1/finding/grouped` - Grouped findings …

feat(findings): Add EPSS filtering support to findings API

---

src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java

Ensure VulnerableSoftware query is able to leverage indexes.
https://owasp.slack.com/archives/C6R3R32H4/p1751638533458859
See code comments.
The [CPE matching test suite](https://github.com/DependencyTrack/dependency-track/blob/e89dee2001405345eed057e08cf5760631d84d3b/src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java) still completes successfully. …

Ensure VulnerableSoftware query is able to leverage indexes

---

src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java

Bulk loads component relationships for BOM export.
Fixes #5107
N/A

Bulk load component relationships for BOM export

---

src/main/java/org/dependencytrack/parser/osv/OsvAdvisoryParser.java
src/test/java/org/dependencytrack/parser/osv/OsvAdvisoryParserTest.java
src/test/java/org/dependencytrack/tasks/OsvDownloadTaskTest.java
src/test/resources/unit/osv.jsons/osv-UBUNTU-CVE-2025-6297.json

Fixes OSV ubuntu advisory containing severity without type.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5105
Backports https://github.com/DependencyTrack/dependency-track/pull/5106
N/A

Backport: Fix OSV ubuntu advisory containing severity without type

---

pom.xml
src/main/java/org/dependencytrack/util/CompressUtil.java

Bumps [org.apache.commons:commons-compress](https://github.com/apache/commons-compress) from 1.27.1 to 1.28.0.
Backports https://github.com/DependencyTrack/dependency-track/pull/5156
N/A

Backport: bump org.apache.commons:commons-compress

---

docs/_docs/getting-started/openidconnect-configuration.md

Adds AWS Cognito configuration example.
Backports https://github.com/DependencyTrack/dependency-track/pull/5032
N/A

Backport: Add AWS Cognito configuration example

---

src/main/java/org/dependencytrack/model/validation/SpdxExpressionValidator.java
src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java
src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java
src/test/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParserTest.java

Fixes https://github.com/DependencyTrack/dependency-track/issues/5025
Backports https://github.com/DependencyTrack/dependency-track/pull/5033
N/A

Backport: Handle dangling SPDX expression operators

---

src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java

Fixes BOM export failing for projects of type NONE.
Fixes #4988
N/A

Backport: Fix BOM export failing for projects of type NONE

---

src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java

Adds whitespace sanitization in fuzzySearch CPE to fix CPE validation errors.
Fixes https://github.com/DependencyTrack/dependency-track/issues/4920
Backports https://github.com/DependencyTrack/dependency-track/pull/5061
N/A

Backport: Add whitespace sanitization in fuzzySearch CPE to fix CPE validation errors

---

src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzerTest.java
src/test/resources/unit/tasks/repositories/https---composer.include.com.metadata-galaxy-cow-arrayentry.json

Improves Composer meta analyzer's ability to deal with minified metadata.
Backports https://github.com/DependencyTrack/dependency-track/pull/5019
N/A

Backport: Improve Composer meta analyzer's ability to deal with minified metadata

---

pom.xml

Bumps bundled frontend to 4.13.3.
N/A
N/A

Bump bundled frontend to 4.13.3

---

src/main/docker/Dockerfile

Bumps Docker base images to latest digests.
N/A
N/A

Bump Docker base images to latest digests

---

pom.xml

Bumps bundled frontend to 4.13.3.
Backports #5183 
N/A

Backport: Bump bundled frontend to 4.13.3

---

src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java

Fixes failing `TrivyAnalysisTaskIntegrationTest`.
N/A
CVE-2016-20013 is no longer reported because Ubuntu has changed its status to "ignored": https://ubuntu.com/security/CVE-2016-20013#status

Fix failing TrivyAnalysisTaskIntegrationTest

---

src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java

Handles URLs in composer package metadata pattern.
It seems that it was originally supposed to only contain paths, but it now returns complete URLs for some packages.
Backports #5233
N/A

Backport: Handle URLs in composer package metadata pattern

---

pom.xml

Bumps commons-lang3 to 3.18.0.
Resolves CVE-2025-48924
Supersedes #5220
N/A

Bump commons-lang3 to 3.18.0

---

src/main/docker/Dockerfile
src/main/docker/Dockerfile.alpine

Bumps Temurin base image to 21.0.8_9.
N/A
N/A

Bump Temurin base image to 21.0.8_9

---

src/main/docker/Dockerfile

Bumps Debian base image to latest digest.
Resolves a few CVEs in the base image.
N/A

Bump Debian base image to latest digest

---

pom.xml

Resolves CVE-2025-7962
Backports #5237 
N/A

Backport: Bump angus-mail to 2.0.4

---

src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java

Fixes failing Trivy OS matching for distro versions with special characters.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5216
N/A

Fix failing Trivy OS matching for distro versions with special characters

---

docs/_posts/2025-08-26-v4.13.4.md

Adds changelog for v4.13.4.
N/A
N/A

Add changelog for v4.13.4

---

src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java

Fix null when computing latest version for NuGet package that has only pre-released versions
Fixes #5075

fix null when NuGet package has only pre-released versions

---

src/main/java/org/dependencytrack/model/VulnerableSoftware.java
src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java
src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java
src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java
src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
src/main/java/org/dependencytrack/upgrade/v4135/v4135Updater.java
src/test/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManagerTest.java
src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java

Backports #5280. Includes the fix #5292 (sorry about that).

Backport: Make CPE matching case-insensitive

---

pom.xml

Bumps open-vulnerability-clients to 9.0.1.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5262
Backports https://github.com/DependencyTrack/dependency-track/pull/5298
Backports https://github.com/DependencyTrack/dependency-track/pull/5300
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-t …

Backport: Bump open-vulnerability-clients to 9.0.1

---

src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java

Fixes https://github.com/DependencyTrack/dependency-track/issues/4945
Backports https://github.com/DependencyTrack/dependency-track/pull/5265
N/A

Backport: improve detection if version is commit sha or release tag for github purl

---

src/main/java/org/dependencytrack/persistence/TagQueryManager.java
src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java

only return tags directly associated with a policy.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5196
Backport https://github.com/DependencyTrack/dependency-track/pull/5314
N/A

Backport: only return tags directly associated with a policy

---

pom.xml

Bumps cyclonedx-core-java to 11.0.0.
Fixes https://github.com/DependencyTrack/dependency-track/issues/5272
Fixes https://github.com/DependencyTrack/dependency-track/issues/4908
Backports https://github.com/DependencyTrack/dependency-track/pull/5336
N/A
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tre …

Backport: Bump cyclonedx-core-java to 11.0.0
